### ISSUE TITLE
Mekanism intergration with AE2 causes Server Crash on load

### ISSUE THREAD

**Issue by Morpheus1101** [AppliedEnergistics/Applied-Energistics-2#1098]
The following error only occurs when Mekanism is alowed via the config of AE2, once its disabled, the server works perfectly fine and loads aok.

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 3/26/15 7:25 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at thaumicenergistics.registries.AEAspectRegister.registerTEItems(AEAspectRegister.java:1001)
	at thaumicenergistics.registries.AEAspectRegister.registerAEAspects(AEAspectRegister.java:1119)
	at thaumicenergistics.ThaumicEnergistics.postInit(ThaumicEnergistics.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694)
	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by yueh** [comment]
This is actually a Thaumic Energistics issue.

It might be caused by the mekanism API break, but it can potentially occur under different conditions.
I would assume that Thaumic Energistics can also crash, if certain items from AE2 are disabled.
So you should probably report it also to them.

Otherwise #1061

**Comment by Morpheus1101** [comment]
Note this requires a small edit in AE2: /src/main//java/appeng/integration/modules/Mekanism.java
from: 
import mekanism.api.RecipeHelper;
to:
import mekanism.api.recipe.RecipeHelper;

(Thats apparently everything thats being reported about the issues)
