### ISSUE TITLE
AE2 rv17 Client Crash when Loading

### ISSUE THREAD

**Issue by Morpheus1101** [AppliedEnergistics/Applied-Energistics-2#1099]
[Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 3/26/15 10:01 PM
Description: There was a severe problem during mod loading that has caused the game to fail

 cpw.mods.fml.common.LoaderException: java.lang.ExceptionInInitializerError
at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
at cpw.mods.fml.common.Loader.initializeMods(Loader.java:695)
at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ExceptionInInitializerError
at appeng.core.AppEng.postInit(AppEng.java:175)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694)
... 10 more
 Caused by: java.lang.NullPointerException
at appeng.core.sync.GuiBridge.getGui(GuiBridge.java:217)
at appeng.core.sync.GuiBridge.<init>(GuiBridge.java:240)
at appeng.core.sync.GuiBridge.<clinit>(GuiBridge.java:127)
... 37 more

**Comment by erkro1** [comment]
I have thesame crash, please fix this.

**Comment by XFactHD** [comment]
Because there is cpw.mods.fml in the first line I would think that you aren't using the latest forge.

**Comment by Morpheus1101** [comment]
Im using Forge v10.13.2.1291

**Comment by erkro1** [comment]
And I'm using v10.13.2.1342, same crash

**Comment by XFactHD** [comment]
Have you tried to downgrade your forge?

**Comment by Morpheus1101** [comment]
Why would prev vers work with .1291 and this version suddenly not ... that makes completely no sense

**Comment by jznomoney** [comment]
I too am getting a crash http://pastebin.com/g26jgdct

**Comment by oks1998** [comment]
I also got crash: http://pastebin.com/hRhy4UJS
forge:1.7.10-Forge10.13.2.1291

**Comment by MasterTeixi** [comment]
Well, seems to be a little bug on the version.

I was playing with v14 and mekanism 8.0.0.526 (for the recipes of AE2 to work) and now, the v17 that is supposed to fix the recipes bug (i really don't know why 8.0.0.526 was working and 8.0.1 or even 8.0.2 weren't) seems to has a problem on the startup.

By the way, with 8.0.0.526 of mekanism, the recipes were working but with Shift+Clicking on a recipe with some processors in it was putting whatever it found in your inventory/cells (for example, after crafting a 64k cpu and a 64k cell, it was using them if i didn't have the processor crafted and of course it wasn't "giving" me the item that needed the processor.

PS: Sorry if i make mistakes. I'm not english and that's why i speak in third person/past tense, to avoid making more than i'm actually doing.

**Comment by halvors** [comment]
Same here: http://pastebin.com/tnaVaDCx
