### ISSUE TITLE
AE rv2 B-22 crash with NEI

### ISSUE THREAD

**Issue by LucyDemooon** [AppliedEnergistics/Applied-Energistics-2#1166]
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213)
	at com.google.common.base.Optional.of(Optional.java:85)
	at appeng.core.features.ItemDefinition.maybeItem(ItemDefinition.java:46)
	at appeng.core.features.DefinitionConverter$AEItem.item(DefinitionConverter.java:117)
	at li.cil.oc.integration.appeng.DriverController$.getTileEntityClass(DriverController.scala:49)
	at li.cil.oc.integration.nei.CallbackDocHandler$$anonfun$getUsageHandler$1$$anonfun$1.applyOrElse(CallbackDocHandler.scala:32)
	at li.cil.oc.integration.nei.CallbackDocHandler$$anonfun$getUsageHandler$1$$anonfun$1.applyOrElse(CallbackDocHandler.scala:30)
	at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:136)
	at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:135)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.collect(TraversableLike.scala:282)
	at scala.collection.AbstractTraversable.collect(Traversable.scala:104)
	at li.cil.oc.integration.nei.CallbackDocHandler$$anonfun$getUsageHandler$1.applyOrElse(CallbackDocHandler.scala:30)
	at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:136)
	at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:135)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at scala.collection.TraversableLike$class.collect(TraversableLike.scala:282)
	at scala.collection.AbstractTraversable.collect(Traversable.scala:104)
	at li.cil.oc.integration.nei.CallbackDocHandler.getUsageHandler(CallbackDocHandler.scala:25)
	at li.cil.oc.integration.nei.CallbackDocHandler.getUsageHandler(CallbackDocHandler.scala:14)
	at codechicken.nei.recipe.GuiUsageRecipe.openRecipeGui(GuiUsageRecipe.java:20)
	at codechicken.nei.recipe.RecipeItemInputHandler.lastKeyTyped(RecipeItemInputHandler.java:20)
	at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:307)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java)
	at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java)
	at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:474)
	at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:464)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1628)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213)
	at com.google.common.base.Optional.of(Optional.java:85)
	at appeng.core.features.ItemDefinition.maybeItem(ItemDefinition.java:46)
	at appeng.core.features.DefinitionConverter$AEItem.item(DefinitionConverter.java:117)
	at li.cil.oc.integration.appeng.DriverController$.getTileEntityClass(DriverController.scala:49)
	at li.cil.oc.integration.nei.CallbackDocHandler$$anonfun$getUsageHandler$1$$anonfun$1.applyOrElse(CallbackDocHandler.scala:32)
	at li.cil.oc.integration.nei.CallbackDocHandler$$anonfun$getUsageHandler$1$$anonfun$1.applyOrElse(CallbackDocHandler.scala:30)
	at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:136)
	at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:135)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.collect(TraversableLike.scala:282)
	at scala.collection.AbstractTraversable.collect(Traversable.scala:104)
	at li.cil.oc.integration.nei.CallbackDocHandler$$anonfun$getUsageHandler$1.applyOrElse(CallbackDocHandler.scala:30)
	at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:136)
	at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:135)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at scala.collection.TraversableLike$class.collect(TraversableLike.scala:282)
	at scala.collection.AbstractTraversable.collect(Traversable.scala:104)
	at li.cil.oc.integration.nei.CallbackDocHandler.getUsageHandler(CallbackDocHandler.scala:25)
	at li.cil.oc.integration.nei.CallbackDocHandler.getUsageHandler(CallbackDocHandler.scala:14)
	at codechicken.nei.recipe.GuiUsageRecipe.openRecipeGui(GuiUsageRecipe.java:20)
	at codechicken.nei.recipe.RecipeItemInputHandler.lastKeyTyped(RecipeItemInputHandler.java:20)
	at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:307)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java)
	at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java)
	at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:474)
	at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:464)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiInventory

NotEnoughItems-1.7.10-1.0.4.95-universal.jar
appliedenergistics2-rv2-beta-22.jar

**Comment by yueh** [comment]
Duplicate
