### ISSUE TITLE
Issue with terminal gui

### ISSUE THREAD

**Issue by Nirealto** [AppliedEnergistics/Applied-Energistics-2#1172]
When i am clicking(right-click, left-click) on empty slot(with or without items) in gui, client closes with error: A fatal error has occured, this connection is terminated.
Version: Beta 22
Server: Single-player
Mods: Forge, AE2

UPDATE
Forge-log: http://pastebin.com/FePvpBCq

**Comment by novy92** [comment]
I have the same problem ;/ also while using space to insert all from eq. the same fatal error. Its not killing mc but only disconnect and go to server list (not worlds in single player, but multiplayer server list...)

**Comment by Be-Cool-Man** [comment]
I have the same problem. Noticed it is me after a update from Buildcraft Additions to version 2.2.0 (and Eureka to version 3.0) A Downgrade do not solve the problem.

_____________________
My Mods:

[ - ]
[1.7.10]bspkrsCore-universal-6.16
[1.7.10]Treecapitator-universal-2.0.4

[ A ]
appliedenergistics2-rv2-beta-22

[ B ]
bamsgrave-1.7.2-1.4.2_01
buildcraft-6.4.6
buildcraft-compat-6.4.2
BuildcraftAdditions-1.7.10-2.1.0

[ C ]
ChickenChunks-1.7.10-1.3.4.19-universal
CodeChickenCore-1.7.10-1.0.4.35-universal (1)
CodeChickenLib-1.7.10-1.1.3.127-universal

[ E ]
EnderIO-1.7.10-2.2.8.344
EnderStorage-1.7.10-1.4.5.29-universal
Eureka-1.7.10-3.0
extrautilities-1.2.2

[ F ]
forge-1.7.10-10.13.2.1343-1.7.10-installer
ForgeMultipart-1.7.10-1.1.1.326-universal

[ N ]
neiaddons-mc1710-1.12.3.11
NEIIntegration-MC1.7.10-1.0.6
NotEnoughItems-1.7.10-1.0.4.94-universal

[ O ]
OpenEye-0.6-1.7.10

[ Q ]
QuarryPlus-1.7.10-2.1.0

[ S ]
simplefluidtanks-1.7.10-1.2.0.5

[ T ]
Telepads-1.7.2_1.7

[ W ]
Waila-1.5.10_1.7.10

**Comment by Teduce** [comment]
I am also having this issue looking at the server log i'm getting this error
Invalid Itemstack.
	at appeng.util.item.AEItemStack.<init>(AEItemStack.java:81) ~[AEItemStack.class:?]
	at appeng.util.item.AEItemStack.create(AEItemStack.java:119) ~[AEItemStack.class:?]
	at appeng.container.AEBaseContainer.updateHeld(AEBaseContainer.java:1036) ~[AEBaseContainer.class:?]
	at appeng.container.AEBaseContainer.doAction(AEBaseContainer.java:938) ~[AEBaseContainer.class:?]
	at appeng.core.sync.packets.PacketInventoryAction.serverPacketData(PacketInventoryAction.java:93) ~[PacketInventoryAction.class:?]
	at appeng.core.sync.network.AppEngServerPacketHandler.onPacketData(AppEngServerPacketHandler.java:46) ~[AppEngServerPacketHandler.class:?]
	at appeng.core.sync.network.NetworkHandler.serverPacket(NetworkHandler.java:99) ~[NetworkHandler.class:?]

**Comment by yueh** [comment]
#1127
