### ISSUE TITLE
Using Craftguide freezes the game

### ISSUE THREAD

**Issue by JackTheRedCreeper** [AppliedEnergistics/Applied-Energistics-2#1403]
title says it. I was going to use craftguide when suddenly everything froze. This is it's log:
(re)loading themes...
  Trying to load directory: base
    Found theme.xml
    Loaded base
  Trying to load directory: dark
    Found theme.xml
    Loaded dark
  Trying to load directory: texpack_support
    Found theme.xml
    Loaded texpack_support
(re)loading recipe list...
  Getting recipes...
    Generating recipes from appeng.integration.modules.CraftGuide
(re)loading recipe list...
  Getting recipes...
    Generating recipes from appeng.integration.modules.CraftGuide
java.lang.NullPointerException
	at appeng.integration.modules.CraftGuide.addCraftingRecipes(CraftGuide.java:124)
	at appeng.integration.modules.CraftGuide.generateRecipes(CraftGuide.java:105)
	at uristqwerty.CraftGuide.RecipeCache.generateRecipes(RecipeCache.java:223)
	at uristqwerty.CraftGuide.RecipeCache.reset(RecipeCache.java:47)
	at uristqwerty.CraftGuide.RecipeCache.<init>(RecipeCache.java:39)
	at uristqwerty.CraftGuide.GuiCraftGuide.<init>(GuiCraftGuide.java:41)
	at uristqwerty.CraftGuide.GuiCraftGuide.getInstance(GuiCraftGuide.java:64)
	at uristqwerty.CraftGuide.client.fml.CraftGuideClient_FML.openGUI(CraftGuideClient_FML.java:102)
	at uristqwerty.CraftGuide.ItemCraftGuide.func_77659_a(ItemCraftGuide.java:43)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146)
	at net.minecraft.server.management.ItemInWorldManager.func_73085_a(ItemInWorldManager.java:316)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:539)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
java.lang.NullPointerException

And a ton more NullPointers.

Any help? I've tried using the latest beta version but no luck..

**Comment by yueh** [comment]
These are actually log entries indicating invalid recipes.
I cannot say which ones, but I would suspect something like minetweaker/modtweaker adding them.

Maybe CraftGuide itself has issues with them.

**Comment by JackTheRedCreeper** [comment]
Nono, it's AE2. if I remove it, craftguide won't crash :/

**Comment by thatsIch** [comment]
Need the whole log

**Comment by JackTheRedCreeper** [comment]
Uploading to dropbox because this is 1.714 KBs of text.

**Comment by thatsIch** [comment]
ok, I am already working on that, 
but I need another patch first, before I can commit it.

**Comment by JackTheRedCreeper** [comment]
Another patch? What do you mean?

**Comment by JackTheRedCreeper** [comment]
Sooo, anything? I wanna update my base with Ae2 but I cant check any of the recipes anymore ^^p

**Comment by thatsIch** [comment]
means I need to work on another feature first, before I can fix that.. and its a bit.. annoying to deal with. You can use NEI for now instead of CraftGuide, if that is applicable for you.

**Comment by yueh** [comment]
I can also not reproduce it crashing. After it generates the recipe the first time, which if course takes some time, it works just fine.

Sure it prints some stacktraces to the log, but as said these are just notices that something is wrong with the recipes. But we could make them a bit better, like actually printing the offending recipe/item.

**Comment by JackTheRedCreeper** [comment]
Hmh... I'll do a brute force check and test what mod is causing the crash, along AE2 and craftguide.
Also I don't use NEI because every time I open the inventory, it has to load all the items and blocks and causes a lagspike.

**Comment by JackTheRedCreeper** [comment]
Back, and it just freezes for a while until the recipes fully load ._.
As without AE2 that load freeze didn't happen, I thought it was a crash...
I also can't find the AE2 recipes, wtf?

**Comment by JackTheRedCreeper** [comment]
I've noticed that most recipes don't appear. At least when I search for the item itself :l I'll check if it's possible to make craftguide omit searching for AE2 recipes.

**Comment by thatsIch** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/1513
