### ISSUE TITLE
Black screen 

### ISSUE THREAD

**Issue by KIllSHot3765** [AppliedEnergistics/Applied-Energistics-2#1492]
These are the errors I got in my report after shutting the game from a 5 minute long black screen.
I did not want to wait any longer to see if it would work after 5 minutes.
[17:22:07] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[17:22:07] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[17:22:07] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[17:22:07] [main/INFO] [FML]: Forge Mod Loader version 7.10.140.1401 for Minecraft 1.7.10 loading
[17:22:07] [main/INFO] [FML]: Java is Java HotSpot(TM) Client VM, version 1.8.0_25, running on Windows Vista:x86:6.0, installed at C:\Users\Sean Spence\Desktop\runtime\jre-x32\1.8.0_25
[17:22:08] [main/INFO] [FML]: [AppEng] Core Init
[17:22:08] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:22:08] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[17:22:08] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:22:08] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:22:08] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:22:10] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[17:22:10] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[17:22:10] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:22:10] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:22:10] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[17:22:11] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[17:22:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[17:22:11] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[17:22:12] [main/INFO] [AE2-CORE]: func_146977_a(Lnet/minecraft/inventory/Slot;)V - Transformed
[17:22:12] [main/INFO] [AE2-CORE]: func_146977_a_original(Lnet/minecraft/inventory/Slot;)V - New Method
[17:22:12] [main/INFO] [AE2-CORE]: func_146977_a(Lnet/minecraft/inventory/Slot;)V - Invoke Virtual
[17:22:12] [main/INFO]: Setting user: KIllSHot3765
[17:22:14] [Client thread/INFO]: LWJGL Version: 2.9.1
[17:22:16] [Client thread/INFO] [FML]: Could not load splash.properties, will create a default one
[17:22:16] [Client thread/INFO] [STDOUT]: [cpw.mods.fml.client.SplashProgress:start:178]: ---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 5/20/15 5:22 PM
Description: Loading screen debug info

java.lang.Throwable
	at cpw.mods.fml.client.SplashProgress.start(SplashProgress.java:177)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:191)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows Vista (x86) version 6.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 23587032 bytes (22 MB) / 180191232 bytes (171 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '2.1.2' Renderer: 'GeForce 6150SE nForce 430/PCI/SSE2/3DNOW!'
[17:22:17] [Client thread/INFO] [MinecraftForge]: Attempting early MinecraftForge initialization
[17:22:17] [Client thread/INFO] [FML]: MinecraftForge v10.13.3.1401 Initialized
[17:22:17] [Client thread/INFO] [FML]: Replaced 183 ore recipies
[17:22:17] [Client thread/INFO] [FML]: Preloading CrashReport classes
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.world.World$1
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.world.World$2
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.world.World$3
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.world.World$4
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.world.chunk.Chunk$1
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.crash.CrashReportCategory$1
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.crash.CrashReportCategory$2
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.crash.CrashReportCategory$3
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.entity.Entity$1
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.entity.Entity$2
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.entity.EntityTracker$1
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.world.gen.layer.GenLayer$1
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.world.gen.layer.GenLayer$2
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.entity.player.InventoryPlayer$1
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.world.gen.structure.MapGenStructure$1
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.world.gen.structure.MapGenStructure$2
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.world.gen.structure.MapGenStructure$3
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.server.MinecraftServer$3
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.server.MinecraftServer$4
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.server.MinecraftServer$5
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.nbt.NBTTagCompound$1
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.nbt.NBTTagCompound$2
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.network.NetHandlerPlayServer$2
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.network.NetworkSystem$3
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.tileentity.TileEntity$1
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.tileentity.TileEntity$2
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.tileentity.TileEntity$3
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$1
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$2
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$3
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$4
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$5
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$6
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$7
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$8
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.world.storage.WorldInfo$9
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$3
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$4
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$5
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$6
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$7
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$8
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$9
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$10
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$11
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$12
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$13
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$14
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.client.Minecraft$15
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.client.multiplayer.WorldClient$1
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.client.multiplayer.WorldClient$2
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.client.multiplayer.WorldClient$3
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.client.multiplayer.WorldClient$4
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.client.particle,EffectRenderer$1
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.client.particle,EffectRenderer$2
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.client.particle,EffectRenderer$3
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.client.particle,EffectRenderer$4
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.EntityRenderer$1
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.EntityRenderer$2
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.EntityRenderer$3
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.server.integrated.IntegratedServer$1
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.server.integrated.IntegratedServer$2
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.RenderGlobal$1
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.entity.RenderItem$1
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.entity.RenderItem$2
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.entity.RenderItem$3
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.entity.RenderItem$4
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.texture.TextureAtlasSprite$1
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.texture.TextureManager$1
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.texture.TextureMap$1
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.texture.TextureMap$2
[17:22:17] [Client thread/INFO] [FML]: 	net.minecraft.client.renderer.texture.TextureMap$3
[17:22:17] [Client thread/INFO] [MinecraftForge]: Completed early MinecraftForge initialization
[17:22:18] [Client thread/INFO] [FML]: [AppEng] Core Init
[17:22:18] [Client thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[17:22:18] [Client thread/INFO] [FML]: Searching C:\Users\Sean Spence\AppData\Roaming\.minecraft\mods for mods
[17:22:23] [Client thread/INFO] [FML]: Forge Mod Loader has identified 5 mods to load
[17:22:24] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, appliedenergistics2-core, appliedenergistics2] at CLIENT
[17:22:24] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, appliedenergistics2-core, appliedenergistics2] at SERVER
[17:22:25] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Applied Energistics 2
[17:22:25] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[17:22:25] [Client thread/INFO] [FML]: Found 341 ObjectHolder annotations
[17:22:25] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[17:22:25] [Client thread/INFO] [AE2:C]: Pre Initialization ( started )
[17:22:26] [Client thread/INFO] [AE2-CORE]: func_145839_a(Lnet/minecraft/nbt/NBTTagCompound;)V - Transformed
[17:22:26] [Client thread/INFO] [AE2-CORE]: func_145841_b(Lnet/minecraft/nbt/NBTTagCompound;)V - Transformed
[17:22:26] [Client thread/INFO] [AE2-CORE]: Removing Interface ic2.api.energy.tile.IEnergySink from appeng/tile/powersink/IC2 because IC2 integration is disabled.
[17:22:26] [Client thread/INFO] [AE2-CORE]: Updated appeng/tile/powersink/IC2
[17:22:26] [Client thread/INFO] [AE2-CORE]: Removing Interface Reika.RotaryCraft.API.Power.AdvancedShaftPowerReceiver from appeng/tile/powersink/RotaryCraft because RotaryCraft integration is disabled.
[17:22:26] [Client thread/INFO] [AE2-CORE]: Removing Interface Reika.RotaryCraft.API.Interfaces.Transducerable from appeng/tile/powersink/RotaryCraft because RotaryCraft integration is disabled.
[17:22:26] [Client thread/INFO] [AE2-CORE]: Removing Method Tick_RotaryCraft from appeng/tile/powersink/RotaryCraft because RotaryCraft integration is disabled.
[17:22:26] [Client thread/INFO] [AE2-CORE]: Updated appeng/tile/powersink/RotaryCraft
[17:22:26] [Client thread/INFO] [AE2-CORE]: Removing Interface cofh.api.energy.IEnergyReceiver from appeng/tile/powersink/RedstoneFlux because RF integration is disabled.
[17:22:26] [Client thread/INFO] [AE2-CORE]: Updated appeng/tile/powersink/RedstoneFlux
[17:22:26] [Client thread/INFO] [AE2-CORE]: Removing Interface mekanism.api.energy.IStrictEnergyAcceptor from appeng/tile/powersink/MekJoules because Mekanism integration is disabled.
[17:22:26] [Client thread/INFO] [AE2-CORE]: Updated appeng/tile/powersink/MekJoules
[17:22:26] [Client thread/INFO] [AE2-CORE]: Removing Interface powercrystals.minefactoryreloaded.api.rednet.connectivity.IRedNetConnection from appeng/block/networking/BlockCableBus because MFR integration is disabled.
[17:22:26] [Client thread/INFO] [AE2-CORE]: Removing Method getConnectionType from appeng/block/networking/BlockCableBus because MFR integration is disabled.
[17:22:26] [Client thread/INFO] [AE2-CORE]: Updated appeng/block/networking/BlockCableBus
[17:22:26] [Client thread/INFO] [AE2-CORE]: Removing Interface buildcraft.api.tools.IToolWrench from appeng/items/tools/quartz/ToolQuartzWrench because BC integration is disabled.
[17:22:26] [Client thread/INFO] [AE2-CORE]: Updated appeng/items/tools/quartz/ToolQuartzWrench
[17:22:26] [Client thread/INFO] [AE2-CORE]: Removing Interface ic2.api.item.ISpecialElectricItem from appeng/items/tools/powered/powersink/IC2 because IC2 integration is disabled.
[17:22:26] [Client thread/INFO] [AE2-CORE]: Removing Interface ic2.api.item.IElectricItemManager from appeng/items/tools/powered/powersink/IC2 because IC2 integration is disabled.
[17:22:26] [Client thread/INFO] [AE2-CORE]: Removing Method getManager from appeng/items/tools/powered/powersink/IC2 because IC2 integration is disabled.
[17:22:26] [Client thread/INFO] [AE2-CORE]: Updated appeng/items/tools/powered/powersink/IC2
[17:22:26] [Client thread/INFO] [AE2-CORE]: Removing Interface cofh.api.energy.IEnergyContainerItem from appeng/items/tools/powered/powersink/RedstoneFlux because RFItem integration is disabled.
[17:22:26] [Client thread/INFO] [AE2-CORE]: Updated appeng/items/tools/powered/powersink/RedstoneFlux
[17:22:26] [Client thread/INFO] [AE2-CORE]: Removing Interface buildcraft.api.tools.IToolWrench from appeng/items/tools/ToolNetworkTool because BC integration is disabled.
[17:22:26] [Client thread/INFO] [AE2-CORE]: Updated appeng/items/tools/ToolNetworkTool
[17:22:27] [Client thread/INFO] [AE2-CORE]: Removing Interface buildcraft.api.transport.IPipeConnection from appeng/parts/misc/PartStorageBus because BC integration is disabled.
[17:22:27] [Client thread/INFO] [AE2-CORE]: Removing Method overridePipeConnection from appeng/parts/misc/PartStorageBus because BC integration is disabled.
[17:22:27] [Client thread/INFO] [AE2-CORE]: Updated appeng/parts/misc/PartStorageBus
[17:22:27] [Client thread/INFO] [AE2-CORE]: Removing Interface buildcraft.api.transport.IPipeConnection from appeng/parts/p2p/PartP2PItems because BC integration is disabled.
[17:22:27] [Client thread/INFO] [AE2-CORE]: Removing Method overridePipeConnection from appeng/parts/p2p/PartP2PItems because BC integration is disabled.
[17:22:27] [Client thread/INFO] [AE2-CORE]: Updated appeng/parts/p2p/PartP2PItems
[17:22:27] [Client thread/INFO] [AE2-CORE]: Removing Interface ic2.api.energy.tile.IEnergySink from appeng/parts/p2p/PartP2PIC2Power because IC2 integration is disabled.
[17:22:27] [Client thread/INFO] [AE2-CORE]: Removing Interface ic2.api.energy.tile.IEnergySource from appeng/parts/p2p/PartP2PIC2Power because IC2 integration is disabled.
[17:22:27] [Client thread/INFO] [AE2-CORE]: Updated appeng/parts/p2p/PartP2PIC2Power
[17:22:27] [Client thread/INFO] [AE2-CORE]: Removing Interface cofh.api.energy.IEnergyReceiver from appeng/parts/p2p/PartP2PRFPower because RF integration is disabled.
[17:22:27] [Client thread/INFO] [AE2-CORE]: Updated appeng/parts/p2p/PartP2PRFPower
[17:22:27] [Client thread/INFO] [AE2:C]: Starting AE2 VersionChecker
[17:22:27] [Client thread/INFO] [AE2:C]: Pre Initialization ( ended after 2364ms )
[17:22:27] [Client thread/INFO] [FML]: Applying holder lookups
[17:22:27] [Client thread/INFO] [FML]: Holder lookups applied
[17:22:27] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[17:22:27] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Starting up SoundSystem...
[17:22:28] [Thread-9/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Initializing LWJGL OpenAL
[17:22:28] [Thread-9/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
Exception in thread "AE2 VersionChecker" [17:22:29] [AE2 VersionChecker/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.IllegalArgumentException: Raw channel stable did not contain any of the pre-programmed types.
[17:22:29] [AE2 VersionChecker/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at appeng.services.version.VersionParser.parseChannel(VersionParser.java:117)
[17:22:29] [AE2 VersionChecker/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at appeng.services.version.VersionParser.parseVersion(VersionParser.java:72)
[17:22:29] [AE2 VersionChecker/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at appeng.services.version.VersionParser.parse(VersionParser.java:34)
[17:22:29] [AE2 VersionChecker/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at appeng.services.version.ModVersionFetcher.get(ModVersionFetcher.java:34)
[17:22:29] [AE2 VersionChecker/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at appeng.services.VersionChecker.processInterval(VersionChecker.java:106)
[17:22:29] [AE2 VersionChecker/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at appeng.services.VersionChecker.run(VersionChecker.java:86)
[17:22:29] [AE2 VersionChecker/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Thread.run(Thread.java:745)
[17:22:30] [Thread-9/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: OpenAL initialized.
[17:22:30] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[17:22:30] [Sound Library Loader/INFO]: Sound engine started
[17:22:31] [Client thread/INFO]: Created: 512x512 textures/blocks-atlas
[17:22:31] [Client thread/INFO]: Created: 512x256 textures/items-atlas
[17:22:31] [Client thread/INFO] [AE2:C]: Initialization ( started )
[17:22:31] [Client thread/INFO] [AE2:C]: Recipes Loading: Shapeless: 56 loaded.
[17:22:31] [Client thread/INFO] [AE2:C]: Recipes Loading: HCCrusher: 9 loaded.
[17:22:31] [Client thread/INFO] [AE2:C]: Recipes Loading: Macerator: 8 loaded.
[17:22:31] [Client thread/INFO] [AE2:C]: Recipes Loading: OreRegistration: 12 loaded.
[17:22:31] [Client thread/INFO] [AE2:C]: Recipes Loading: MekCrusher: 3 loaded.
[17:22:31] [Client thread/INFO] [AE2:C]: Recipes Loading: Pulverizer: 9 loaded.
[17:22:31] [Client thread/INFO] [AE2:C]: Recipes Loading: GrindFZ: 7 loaded.
[17:22:31] [Client thread/INFO] [AE2:C]: Recipes Loading: Press: 3 loaded.
[17:22:31] [Client thread/INFO] [AE2:C]: Recipes Loading: MekEnrichment: 2 loaded.
[17:22:31] [Client thread/INFO] [AE2:C]: Recipes Loading: Smelt: 6 loaded.
[17:22:31] [Client thread/INFO] [AE2:C]: Recipes Loading: Inscribe: 8 loaded.
[17:22:31] [Client thread/INFO] [AE2:C]: Recipes Loading: Shaped: 203 loaded.
[17:22:31] [Client thread/INFO] [AE2:C]: Recipes Loading: Grind: 4 loaded.
[17:22:31] [Client thread/INFO] [AE2:C]: Recipes Loading: Crusher: 9 loaded.
[17:22:31] [Client thread/INFO] [AE2:C]: Initialization ( ended after 343ms )
[17:22:32] [Client thread/INFO] [AE2:C]: Post Initialization ( started )
[17:22:32] [Client thread/INFO] [AE2:C]: Layer: appeng/parts/layers/LayerISidedInventory_TileCableBus loaded successfully - 5294 bytes
[17:22:32] [Client thread/INFO] [AE2:C]: Layer: appeng/parts/layers/LayerIFluidHandler_TileCableBus loaded successfully - 2442 bytes
[17:22:32] [Client thread/INFO] [AE2:C]: Layer: appeng/parts/layers/LayerITileStorageMonitorable_TileCableBus loaded successfully - 1070 bytes
[17:22:32] [Client thread/INFO] [AE2:C]: Layer: appeng/parts/layers/LayerISidedInventory_TileCableBusTESR loaded successfully - 5306 bytes
[17:22:32] [Client thread/INFO] [AE2:C]: Layer: appeng/parts/layers/LayerIFluidHandler_TileCableBusTESR loaded successfully - 2454 bytes
[17:22:32] [Client thread/INFO] [AE2:C]: Layer: appeng/parts/layers/LayerITileStorageMonitorable_TileCableBusTESR loaded successfully - 1082 bytes
[17:22:32] [Client thread/INFO] [AE2:C]: Industrial Craft 2 - Integration Disabled
[17:22:32] [Client thread/INFO] [AE2:C]: Rotary Craft - Integration Disabled
[17:22:32] [Client thread/INFO] [AE2:C]: Railcraft - Integration Disabled
[17:22:32] [Client thread/INFO] [AE2:C]: BuildCraft - Integration Disabled
[17:22:32] [Client thread/INFO] [AE2:C]: RedstoneFlux Power - Tiles - Integration Disabled
[17:22:32] [Client thread/INFO] [AE2:C]: RedstoneFlux Power - Items - Integration Disabled
[17:22:32] [Client thread/INFO] [AE2:C]: Mine Factory Reloaded - Integration Disabled
[17:22:32] [Client thread/INFO] [AE2:C]: Deep Storage Unit - Integration Disabled
[17:22:32] [Client thread/INFO] [AE2:C]: Factorization - Integration Disabled
[17:22:32] [Client thread/INFO] [AE2:C]: Forge MultiPart - Integration Disabled
[17:22:32] [Client thread/INFO] [AE2:C]: Rotatable Blocks - Integration Disabled
[17:22:32] [Client thread/INFO] [AE2:C]: Colored Lights Core - Integration Disabled
[17:22:32] [Client thread/INFO] [AE2:C]: Waila - Integration Disabled
[17:22:32] [Client thread/INFO] [AE2:C]: Inventory Tweaks - Integration Disabled
[17:22:32] [Client thread/INFO] [AE2:C]: Not Enough Items - Integration Disabled
[17:22:32] [Client thread/INFO] [AE2:C]: Craft Guide - Integration Disabled
[17:22:32] [Client thread/INFO] [AE2:C]: Mekanism - Integration Disabled
[17:22:32] [Client thread/INFO] [AE2:C]: ImmibisMicroblocks - Integration Disabled
[17:22:32] [Client thread/INFO] [AE2:C]: BetterStorage - Integration Disabled
[17:22:32] [Client thread/INFO] [AE2:C]: Post Initialization ( ended after 759ms )
[17:22:32] [Client thread/INFO] [FML]: Forge Mod Loader has successfully loaded 5 mods
[17:22:32] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Applied Energistics 2
[17:22:33] [Client thread/INFO]: Created: 512x512 textures/blocks-atlas
[17:22:34] [Client thread/INFO]: Created: 512x256 textures/items-atlas
[17:22:34] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[17:22:34] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: SoundSystem shutting down...
[17:22:34] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:importantMessage:90]:     Author: Paul Lamb, www.paulscode.com
[17:22:34] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[17:22:34] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[17:22:34] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Starting up SoundSystem...
[17:22:34] [Thread-11/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Initializing LWJGL OpenAL
[17:22:34] [Thread-11/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[17:22:37] [Thread-11/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: OpenAL initialized.
[17:22:37] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[17:22:37] [Sound Library Loader/INFO]: Sound engine started
[17:26:05] [Client thread/INFO]: Stopping!
[17:26:05] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[17:26:05] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: SoundSystem shutting down...
[17:26:05] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:importantMessage:90]:     Author: Paul Lamb, www.paulscode.com
[17:26:05] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:

**Comment by yueh** [comment]
That is a FML/Forge issue.

**Comment by KIllSHot3765** [comment]
Any way to fix it?

**Comment by yueh** [comment]
No idea, you should probably ask them.
