### ISSUE TITLE
Selecting incorrect item resulting in crash

### ISSUE THREAD

**Issue by Razaekel** [AppliedEnergistics/Applied-Energistics-2#1534]
The terminals have a tendency to select a random item if the selected item doesn't exist in the system, but appears to have a replacement. This has resulted in crashes when the items have different, non-compatible classes, resulting in a class cast exception.

Uploaded the crashlog here: http://paste.ee/p/lnIlt

**Comment by yueh** [comment]
That is an issue in the rfdrills recipe handling.

**Comment by Razaekel** [comment]
I'll let the RFDrills guy know.

**Comment by Razaekel** [comment]
and you're sure it has nothing to do with the following section related to packets from AE?

	at appeng.core.sync.packets.PacketNEIRecipe.serverPacketData(PacketNEIRecipe.java:129) ~[PacketNEIRecipe.class:?]
	at appeng.core.sync.network.AppEngServerPacketHandler.onPacketData(AppEngServerPacketHandler.java:46) ~[AppEngServerPacketHandler.class:?]
	at appeng.core.sync.network.NetworkHandler.serverPacket(NetworkHandler.java:99) ~[NetworkHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_988_NetworkHandler_serverPacket_ServerCustomPacketEvent.invoke(.dynamic) ~[?:?]
