### ISSUE TITLE
Replace rv1 stable 1 on rv2 stable 10 crash

### ISSUE THREAD

**Issue by slayerain** [AppliedEnergistics/Applied-Energistics-2#1815]
I just try replace my rv1 with latest rv2 since rv1 crash whenever i use monitor for liquids.
Game crash:
 
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 8/17/15 12:19 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: appeng.api.features.IRegistryContainer.moveable()Lappeng/api/movable/IMovableRegistry;
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: appeng.api.features.IRegistryContainer.moveable()Lappeng/api/movable/IMovableRegistry;
	at extracells.proxy.CommonProxy.registerMovables(CommonProxy.java:20)
	at extracells.Extracells.init(Extracells.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 194966872 bytes (185 MB) / 581373952 bytes (554 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 Optifine OptiFine_1.7.10_HD_B5 46 mods loaded, 46 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHI	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHI	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHI	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
	UCHI	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) 
	UCHI	IC2{2.2.760-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.760-experimental.jar) 
	UCHI	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel-1.7.10-3.5.1.jar) 
	UCHI	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHI	BuildCraft|Core{7.0.20} [BuildCraft] (buildcraft-7.0.20.jar) 
	UCHI	BuildCraft|Silicon{7.0.20} [BC Silicon] (buildcraft-7.0.20.jar) 
	UCHI	BuildCraft|Transport{7.0.20} [BC Transport] (buildcraft-7.0.20.jar) 
	UCHI	BuildCraft|Builders{7.0.20} [BC Builders] (buildcraft-7.0.20.jar) 
	UCHI	BuildCraft|Robotics{7.0.20} [BC Robotics] (buildcraft-7.0.20.jar) 
	UCHI	BuildCraft|Energy{7.0.20} [BC Energy] (buildcraft-7.0.20.jar) 
	UCHI	BuildCraft|Factory{7.0.20} [BC Factory] (buildcraft-7.0.20.jar) 
	UCHI	ComputerCraft{1.65} [ComputerCraft] (ComputerCraft1.65.jar) 
	UCHI	craftguide{1.6.8.1} [CraftGuide] (CraftGuide-Mod-1.7.10.zip) 
	UCHI	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UCHE	extracells{2.1.10} [ExtraCells] (ExtraCells-Mod-1.7.2.jar) 
	UCHI	flansmod{4.9.0} [Flan's Mod] (Flans Mod-1.7.10-4.9.0.jar) 
	UCHI	Forestry{3.6.3.20} [Forestry for Minecraft] (forestry_1.7.10-3.6.3.20.jar) 
	UCHI	WaslieCore{1.1} [WaslieCore] (WaslieCore-1.7.10.jar) 
	UCHI	ForestryExtras{3.1} [Forestry Extras] (ForestryExtras-2-3.1_B24.jar) 
	UCHI	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite-1.7.10-2.0.3.jar) 
	UCHI	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) 
	UCHI	IronChest{6.0.62.742} [Iron Chest] (Iron-Chests-Mod-1.7.10.jar) 
	UCHI	MouseTweaks{2.4.4} [Mouse Tweaks] (Mouse-Tweaks-Mod-1.7.10.jar) 
	UCHI	NEIAddons{1.12.3.11} [NEI Addons] (neiaddons-mc1710-1.12.3.11.jar) 
	UCHI	NEIAddons|Botany{1.12.3.11} [NEI Addons: Botany] (neiaddons-mc1710-1.12.3.11.jar) 
	UCHI	NEIAddons|Forestry{1.12.3.11} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.3.11.jar) 
	UCHI	NEIAddons|CraftingTables{1.12.3.11} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.3.11.jar) 
	UCHI	NEIAddons|ExNihilo{1.12.3.11} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.3.11.jar) 
	UCHI	ForgeMultipart{1.1.0.296} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.296-universal.jar) 
	UCHI	ProjRed|Core{4.4.5.44} [ProjectRed] (ProjectRed-Base-1.7.10-4.4.5.44.jar) 
	UCHI	ProjRed|Transmission{4.4.5.44} [ProjectRed-Transmission] (ProjectRed-Integration-1.7.10-4.4.5.44.jar) 
	UCHI	ProjRed|Transportation{4.4.5.44} [ProjectRed-Transportation] (ProjectRed-Mechanical-1.7.10-4.4.5.44.jar) 
	UCHI	ProjRed|Exploration{4.4.5.44} [ProjectRed-Exploration] (ProjectRed-World-1.7.10-4.4.5.44.jar) 
	UCHI	ProjRed|Compatibility{4.4.5.44} [ProjectRed-Compatibility] (ProjectRed-Compat-1.7.10-4.4.5.44.jar) 
	UCHI	ProjRed|Integration{4.4.5.44} [ProjectRed-Integration] (ProjectRed-Integration-1.7.10-4.4.5.44.jar) 
	UCHI	ProjRed|Illumination{4.4.5.44} [ProjectRed-Illumination] (ProjectRed-Lighting-1.7.10-4.4.5.44.jar) 
	UCHI	ProjRed|Expansion{4.4.5.44} [ProjectRed-Expansion] (ProjectRed-Mechanical-1.7.10-4.4.5.44.jar) 
	UCHI	ReiMinimap{1.7.10} [Rei's Minimap] (Reis-Minimap-Mod-1.7.10.jar) 
	UCHI	chunkbase_villageinfo_ssp{2.1} [Village Info (SSP)] (VillageInfoSSP-1.7.10-2.1.jar) 
	UCHI	McMultipart{1.1.0.296} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.296-universal.jar) 
	UCHI	ForgeMicroblock{1.1.0.296} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.296-universal.jar) 
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Optifine
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.

**Comment by yueh** [comment]
Update EC2

**Comment by slayerain** [comment]
it worked. thx and sorry for disturb. when u have so much mods, hard to keep up updates for everyone)
