### ISSUE TITLE
Spam World Generation Error

### ISSUE THREAD

**Issue by trismegistis** [AppliedEnergistics/Applied-Energistics-2#1871]
[Server thread/ERROR] [AE2:S]: Error: java.io.EOFException : null
[16:33:02] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.io.EOFException
[16:33:02] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.util.zip.GZIPInputStream.readUByte(Unknown Source)
[16:33:02] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.util.zip.GZIPInputStream.readUShort(Unknown Source)
[16:33:02] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.util.zip.GZIPInputStream.readHeader(Unknown Source)
[16:33:02] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.util.zip.GZIPInputStream.<init>(Unknown Source)
[16:33:02] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.util.zip.GZIPInputStream.<init>(Unknown Source)
[16:33:02] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.nbt.CompressedStreamTools.func_74796_a(CompressedStreamTools.java:29)
[16:33:02] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at appeng.core.worlddata.SpawnData.loadSpawnData(SpawnData.java:151)
[16:33:02] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at appeng.core.worlddata.SpawnData.getNearByMeteorites(SpawnData.java:115)
[16:33:02] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at appeng.worldgen.MeteoriteWorldGen.getNearByMeteorites(MeteoriteWorldGen.java:113)
[16:33:02] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at appeng.worldgen.MeteoriteWorldGen.access$000(MeteoriteWorldGen.java:40)
[16:33:02] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at appeng.worldgen.MeteoriteWorldGen$MeteoriteSpawn.call(MeteoriteWorldGen.java:139)
[16:33:02] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at appeng.hooks.TickHandler.processQueue(TickHandler.java:283)
[16:33:02] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at appeng.hooks.TickHandler.onTick(TickHandler.java:251)
[16:33:02] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.eventhandler.ASMEventHandler_865_TickHandler_onTick_TickEvent.invoke(.dynamic)
[16:33:02] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[16:33:02] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
[16:33:02] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:268)
[16:33:02] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:620)
[16:33:02] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[16:33:02] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[16:33:02] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at fastcraft.K.a(F:21)
[16:33:02] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at fastcraft.H.aq(F:157)
[16:33:02] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
[16:33:02] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by trismegistis** [comment]
This spams the screen and it's undetermined yet what players on my server are doing but I'm assuming it is walking around the world loading meteors from applied energistics. It raises tick time to 35ms from 11ms when this spam is occurring.

**Comment by thatsIch** [comment]
Version?

**Comment by trismegistis** [comment]
Sorry, havent seen it since rv3 -6 i think it was resolved either from 7 or
mod conflict was removed
