### ISSUE TITLE
crash with chromaticraft

### ISSUE THREAD

**Issue by Kenshij** [AppliedEnergistics/Applied-Energistics-2#1975]
r2-stable-10 and r3-alpha-9 have this problem, v9b chromaticraft

on item export ae2 runs in null pointer exeption in ChromaResearchManager class, after this chromaticraft can't load the class and the game crashes 

reduced log : http://pastebin.com/VhNAfRrw

**Comment by mindforger** [comment]
please tell me if i am wrong but doesn't 
`[01:37:50] [Client thread/ERROR] [FML/]: Caught exception from ChromatiCraft
java.lang.NoClassDefFoundError: Could not initialize class Reika.ChromatiCraft.Registry.ChromaResearchManager$ResearchLevel
`
is telling me that chromaticraft is doing seomthign to AE that backfires badly ?

and the earlier exceptions look like an accident following this backfire

**Comment by yueh** [comment]
The item exporter was only added with rv3-alpha-9, thus it is impossible to happen with any older version. It also handles it gracefully without crashing your game, but still logging any possible issues to the log.

Otherwise the stacktrace with the `NoClassDefFoundError` is only containing chromaticraft and if a `NullPointerException` earlier leads to a `NoClassDefFoundError`, than there is something really wrong going on in chromaticraft.

Please report it to their tracker and if they actually can identify that AE2 fetching the name of an item is horribly wrong, we will reopen this issue.

**Comment by Kenshij** [comment]
Sorry with r2-stable-10 the game runs.
Have tested a clean install with only your mod(rv3-alpha-9) and raikas, same crash. 
Without ae2 it runs. Will report it today to reika.

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 10/29/15 11:24 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: Could not initialize class Reika.ChromatiCraft.Registry.ChromaResearchManager$ResearchLevel
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class Reika.ChromatiCraft.Registry.ChromaResearchManager$ResearchLevel
	at Reika.ChromatiCraft.Registry.ChromaResearch.<clinit>(ChromaResearch.java:76)
	at Reika.ChromatiCraft.ChromaRecipes.addRecipes(ChromaRecipes.java:61)
	at Reika.ChromatiCraft.ChromatiCraft.load(ChromatiCraft.java:383)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	... 18 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_65, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1423237208 bytes (1357 MB) / 2765094912 bytes (2637 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx4096m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
	UCHI	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
	UCHI	appliedenergistics2-core{rv3-alpha-9} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHI	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHI	appliedenergistics2{rv3-alpha-9} [Applied Energistics 2] (appliedenergistics2-rv3-alpha-9.jar) 
	UCHI	DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V9b.jar) 
	UCHE	ChromatiCraft{1.0} [ChromatiCraft] (ChromatiCraft 1.7.10 V9b.jar) 
	UCHI	GeoStrata{1.0} [GeoStrata] (GeoStrata 1.7.10 V9a.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.2.0 - Build 10.18.10.3496' Renderer: 'Intel(R) HD Graphics 4400'
	AE2 Version: alpha rv3-alpha-9 for Forge 10.13.4.1448

**Comment by thatsIch** [comment]
If all fails deactivate the feature in the config
