### ISSUE TITLE
AE2+Botania = Client crash with channels=false when viewing Quantum Ring recipe "Unnamed" cable item tooltip.

### ISSUE THREAD

**Issue by lossycrypt** [AppliedEnergistics/Applied-Energistics-2#1992]
[This issue at Botania issue tracker](https://github.com/Vazkii/Botania/issues/1517)

##### Description:
When channels are disabled in AE2 config the "ME Dense Cable - Fluix" required for crafting a "ME Quantum Ring" is replaced by "Unnamed" with same ID and metadata. Trying to view the item tooltip if Botania is also installed crashes the client but has no effect on the server.

##### Steps to reproduce:
- Have required mods.
- Disable channels in AppliedEnergistics2.cfg: "networkfeatures {B:Channels=false}"
- Open recipe for "ME Quantum Ring" in NEI.
- Hover mouse over "Unnamed" cable.
- Client crashes to Desktop.

##### Minimal mods to reproduce:
Forge 10.13.4.1448
```
│  appliedenergistics2-rv2-stable-10.jar
│  Botania r1.7-230.jar
│  CodeChickenCore-1.7.10-1.0.7.47-universal.jar
│  NotEnoughItems-1.7.10-1.0.5.118-universal.jar
└─1.7.10
        Baubles-1.7.10-1.0.1.10.jar
        CodeChickenLib-1.7.10-1.1.3.140-universal.jar
```

##### Crash log [(Full Log)](https://gist.github.com/lossycrypt/f1a6db52a66ae4f5f394):
```
java.lang.NullPointerException
	at appeng.items.parts.ItemMultiPart$PartTypeWithVariant.access$200(ItemMultiPart.java:355) ~[ItemMultiPart$PartTypeWithVariant.class:?]
	at appeng.items.parts.ItemMultiPart.func_77653_i(ItemMultiPart.java:206) ~[ItemMultiPart.class:?]
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427) ~[add.class:?]
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:489) ~[add.class:?]
	at vazkii.botania.client.core.handler.TooltipAdditionDisplayHandler.render(TooltipAdditionDisplayHandler.java:62) ~[TooltipAdditionDisplayHandler.class:?]
	at vazkii.botania.client.core.handler.ClientTickHandler.renderTick(ClientTickHandler.java:54) ~[ClientTickHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_98_ClientTickHandler_renderTick_RenderTickEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onRenderTickEnd(FMLCommonHandler.java:340) [FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1003) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_80]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_80]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_80]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_80]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]

```

##### How it looks without Botania:
![Picture](https://cloud.githubusercontent.com/assets/14168854/10976165/ac01da4a-83ea-11e5-90d4-696fa6f23e0f.jpg)

**Comment by yueh** [comment]
#1450
