### ISSUE TITLE
Audio bug autocrafting with gregtech

### ISSUE THREAD

**Issue by PikPik4654** [AppliedEnergistics/Applied-Energistics-2#2171]
he has got a probleme with autocraft and gregtech tools,a hammer sound is played continuously during the preparation of the craft and sometimes the game crash with this error:

java.util.ConcurrentModificationException
	at com.google.common.collect.HashBiMap$Itr.checkForConcurrentModification(HashBiMap.java:339)
	at com.google.common.collect.HashBiMap$Itr.hasNext(HashBiMap.java:345)
	at net.minecraft.client.audio.SoundManager.func_148605_d(SoundManager.java:212)
	at net.minecraft.client.audio.SoundHandler.func_73660_a(SourceFile:179)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2013)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

someone have the same problem than me or have an idea to fix this problem ?

**Comment by thatsIch** [comment]
I do not think we can prevent the sound from playing since it is injected into the crafting process on his side.

**Comment by PikPik4654** [comment]
okay, thank you for your response :)
