### ISSUE TITLE
Metter Cannon and Color Aplicator server & client crash

### ISSUE THREAD

**Issue by BlayzerQ** [AppliedEnergistics/Applied-Energistics-2#2200]
If Metter Cannon and Color Aplicator place at Dispencer and use Dispencer - server or client crash.

java.lang.NullPointerException: Exception while ticking a block
	at net.minecraft.entity.player.EntityPlayerMP.func_145747_a(EntityPlayerMP.java:1270)
	at appeng.items.tools.powered.ToolMassCannon.func_77659_a(ToolMassCannon.java:182)
	at appeng.hooks.DispenserMatterCannon.func_82487_b(DispenserMatterCannon.java:68)
	at net.minecraft.dispenser.BehaviorDefaultDispenseItem.func_82482_a(BehaviorDefaultDispenseItem.java:20)
	at net.minecraft.block.BlockDispenser.func_149941_e(BlockDispenser.java:149)
	at net.minecraft.block.BlockDispenser.func_149674_a(BlockDispenser.java:183)
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:697)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:279)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:931)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Thread.java:745)

**Comment by ensirius** [comment]
Can confirm on r2

**Comment by BlayzerQ** [comment]
Fix; https://yadi.sk/d/kH02jGtnqFxvr

**Comment by ensirius** [comment]
How about creating PR?

**Comment by XFactHD** [comment]
@BlayzerQ Update AE2 to the latest beta before providing any "fixes". The latest beta is very stable, probably in terms of bugs even more stable than the "rv2 stable" versions.

**Comment by ensirius** [comment]
@XFactHD Before saying anything maybe try latest beta?

**Comment by mindforger** [comment]
@ensirius i am using it(rv3 beta5), don't know where your problem is

**Comment by XFactHD** [comment]
@ensirius The file with the "fix" is versioned as "rv2-stable10", so I suspect that @BlayzerQ didn't even try the latest beta. Also, I didn't say that it is fixed in the latest beta I just told him to test it and provide the fix for the latest version if necessary.

**Comment by thatsIch** [comment]
I guess it is resolved then
