### ISSUE TITLE
Server crashing with export buses

### ISSUE THREAD

**Issue by DigitalSniperz** [AppliedEnergistics/Applied-Energistics-2#2202]
My server seems to be crashing because of export buses,

version: appliedenergistics2-rv2-stable-10
forge: forge-1.7.10-10.13.4.1448-1.7.10

Crash-report:
`java.lang.NoClassDefFoundError: scala/NotImplementedError
	at appeng.helpers.MultiCraftingTracker.getRequestedJobs(MultiCraftingTracker.java:212)
	at appeng.parts.automation.PartExportBus.getRequestedJobs(PartExportBus.java:327)
	at appeng.me.cache.CraftingGridCache.addNode(CraftingGridCache.java:218)
	at appeng.me.GridCacheWrapper.addNode(GridCacheWrapper.java:55)
	at appeng.me.Grid.add(Grid.java:205)
	at appeng.me.GridNode.setGrid(GridNode.java:256)
	at appeng.me.Grid.<init>(Grid.java:71)
	at appeng.me.GridNode.getInternalGrid(GridNode.java:151)
	at appeng.me.GridNode.updateState(GridNode.java:218)
	at appeng.me.helpers.AENetworkProxy.getNode(AENetworkProxy.java:150)
	at appeng.me.helpers.AENetworkProxy.onReady(AENetworkProxy.java:141)
	at appeng.parts.AEBasePart.addToWorld(AEBasePart.java:309)
	at appeng.parts.CableBusContainer.addToWorld(CableBusContainer.java:605)
	at appeng.tile.networking.TileCableBus.onReady(TileCableBus.java:221)
	at appeng.hooks.TickHandler.onTick(TickHandler.java:231)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_417_TickHandler_onTick_TickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:251)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:874)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:674)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: scala.NotImplementedError
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 22 more
Caused by: java.lang.NullPointerException`

**Comment by mindforger** [comment]
full crashlog via pastebin or as attachement please

**Comment by DigitalSniperz** [comment]
http://pastebin.com/btG4fiWz

**Comment by SephirothWS** [comment]
Is Modded: Definitely; Server brand changed to 'thermos,cauldron,craftbukkit,mcpc,kcauldron,fml,forge'

Does this happen on a non-cauldron/kcauldron/mcpc server?

**Comment by DigitalSniperz** [comment]
Yes

**Comment by mindforger** [comment]
can you post a crashlog with the forge server?

**Comment by yueh** [comment]
Broken forge installation. Also no support for any bukkit derivate.
