### ISSUE TITLE
Conflict (On Server) With Project Superhuman

### ISSUE THREAD

**Issue by FEPVanceLee** [AppliedEnergistics/Applied-Energistics-2#2243]
I'm running (or trying to) a server (Cauldron). I'm trying to install Applied Energistics And Project Superhuman. I apologize if this seems like the wrong place to post this, but project superhuman is on hiatus, so they can't do much, and i can't find any other occurences of this. Anyways, here are the relevant logs;
`---- Minecraft Crash Report ----
// There are four lights!

Time: 16/04/16 20:49
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/herosuits/item/ItemUtilityBelt
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:535)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:318)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:176)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: net/herosuits/item/ItemUtilityBelt
	at net.herosuits.HeroSuits.preInit(HeroSuits.java:555)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:533)
	... 5 more
Caused by: java.lang.ClassNotFoundException: net.herosuits.item.ItemUtilityBelt
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 33 more
Caused by: java.lang.NoClassDefFoundError: net/herosuits/item/ItemBaubleEquipment
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 35 more
Caused by: java.lang.ClassNotFoundException: net.herosuits.item.ItemBaubleEquipment
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 39 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 4.2.0-27-generic
	Java Version: 1.7.0_95, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1934696784 bytes (1845 MB) / 2058878976 bytes (1963 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 2 total; -Xmx6G -Xms2G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.114.1388 Minecraft Forge 10.13.3.1403 7 mods loaded, 7 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{7.10.114.1388} [Forge Mod Loader] (cauldron-1.7.10-2.1403.1.54-server.jar) Unloaded->Constructed->Pre-initialized
	Forge{10.13.3.1403} [Minecraft Forge] (cauldron-1.7.10-2.1403.1.54-server.jar) Unloaded->Constructed->Pre-initialized
	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) Unloaded->Constructed->Pre-initialized
	HeroSuits{1.2} [Project Superhuman] (ProjectSuperhuman - v1.2 - 1.7.10.jar) Unloaded->Constructed->Errored
	zoocraftia{0.2} [Zoocraftia] (zoocraftia-0.2.jar) Unloaded->Constructed->Pre-initialized
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'cauldron,craftbukkit,mcpc,fml,forge'
	Type: Dedicated Server (map_server.txt)`

`[20:49:20] [main/INFO] [FML/]: Forge Mod Loader version 7.10.114.1388 for Minecraft 1.7.10 loading
[20:49:21] [main/INFO] [FML/]: Java is OpenJDK 64-Bit Server VM, version 1.7.0_95, running on Linux:amd64:4.2.0-27-generic, installed at /usr/lib/jvm/java-7-openjdk-amd64/jre
[20:49:21] [main/INFO] [FML/]: [AppEng] Core Init
[20:49:21] [main/INFO] [LaunchWrapper/]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:49:21] [main/INFO] [LaunchWrapper/]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[20:49:21] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:49:21] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:49:21] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:49:24] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:49:24] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:49:24] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[20:49:26] [main/INFO] [LaunchWrapper/]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[20:49:26] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[20:49:28] [main/INFO] [LaunchWrapper/]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[20:49:35] [Server thread/INFO] [MinecraftForge/]: Attempting early MinecraftForge initialization
[20:49:35] [Server thread/INFO] [FML/]: MinecraftForge v10.13.3.1403 Initialized
[20:49:35] [Server thread/INFO] [FML/]: Replaced 183 ore recipies
[20:49:35] [Server thread/INFO] [FML/]: Preloading CrashReport classes
[20:49:35] [Server thread/INFO] [FML/]: 	net.minecraft.world.World$1
[20:49:35] [Server thread/INFO] [FML/]: 	net.minecraft.world.World$2
[20:49:35] [Server thread/INFO] [FML/]: 	net.minecraft.world.World$3
[20:49:35] [Server thread/INFO] [FML/]: 	net.minecraft.world.World$4
[20:49:35] [Server thread/INFO] [FML/]: 	net.minecraft.world.chunk.Chunk$1
[20:49:35] [Server thread/INFO] [FML/]: 	net.minecraft.crash.CrashReportCategory$1
[20:49:35] [Server thread/INFO] [FML/]: 	net.minecraft.crash.CrashReportCategory$2
[20:49:35] [Server thread/INFO] [FML/]: 	net.minecraft.crash.CrashReportCategory$3
[20:49:35] [Server thread/INFO] [FML/]: 	net.minecraft.entity.Entity$1
[20:49:35] [Server thread/INFO] [FML/]: 	net.minecraft.entity.Entity$2
[20:49:35] [Server thread/INFO] [FML/]: 	net.minecraft.entity.EntityTracker$1
[20:49:35] [Server thread/INFO] [FML/]: 	net.minecraft.world.gen.layer.GenLayer$1
[20:49:35] [Server thread/INFO] [FML/]: 	net.minecraft.world.gen.layer.GenLayer$2
[20:49:35] [Server thread/INFO] [FML/]: 	net.minecraft.entity.player.InventoryPlayer$1
[20:49:35] [Server thread/INFO] [FML/]: 	net.minecraft.world.gen.structure.MapGenStructure$1
[20:49:35] [Server thread/INFO] [FML/]: 	net.minecraft.world.gen.structure.MapGenStructure$2
[20:49:35] [Server thread/INFO] [FML/]: 	net.minecraft.world.gen.structure.MapGenStructure$3
[20:49:35] [Server thread/INFO] [FML/]: 	net.minecraft.server.MinecraftServer$3
[20:49:35] [Server thread/INFO] [FML/]: 	net.minecraft.server.MinecraftServer$4
[20:49:35] [Server thread/INFO] [FML/]: 	net.minecraft.server.MinecraftServer$5
[20:49:35] [Server thread/INFO] [FML/]: 	net.minecraft.nbt.NBTTagCompound$1
[20:49:35] [Server thread/INFO] [FML/]: 	net.minecraft.nbt.NBTTagCompound$2
[20:49:36] [Server thread/INFO] [FML/]: 	net.minecraft.network.NetHandlerPlayServer$2
[20:49:36] [Server thread/INFO] [FML/]: 	net.minecraft.network.NetworkSystem$3
[20:49:36] [Server thread/INFO] [FML/]: 	net.minecraft.tileentity.TileEntity$1
[20:49:36] [Server thread/INFO] [FML/]: 	net.minecraft.tileentity.TileEntity$2
[20:49:36] [Server thread/INFO] [FML/]: 	net.minecraft.tileentity.TileEntity$3
[20:49:36] [Server thread/INFO] [FML/]: 	net.minecraft.world.storage.WorldInfo$1
[20:49:36] [Server thread/INFO] [FML/]: 	net.minecraft.world.storage.WorldInfo$2
[20:49:36] [Server thread/INFO] [FML/]: 	net.minecraft.world.storage.WorldInfo$3
[20:49:36] [Server thread/INFO] [FML/]: 	net.minecraft.world.storage.WorldInfo$4
[20:49:36] [Server thread/INFO] [FML/]: 	net.minecraft.world.storage.WorldInfo$5
[20:49:36] [Server thread/INFO] [FML/]: 	net.minecraft.world.storage.WorldInfo$6
[20:49:36] [Server thread/INFO] [FML/]: 	net.minecraft.world.storage.WorldInfo$7
[20:49:36] [Server thread/INFO] [FML/]: 	net.minecraft.world.storage.WorldInfo$8
[20:49:36] [Server thread/INFO] [FML/]: 	net.minecraft.world.storage.WorldInfo$9
[20:49:36] [Server thread/INFO] [FML/]: 	net.minecraft.server.dedicated.DedicatedServer$3
[20:49:36] [Server thread/INFO] [FML/]: 	net.minecraft.server.dedicated.DedicatedServer$4
[20:49:36] [Server thread/INFO] [MinecraftForge/]: Completed early MinecraftForge initialization
[20:49:36] [Server thread/INFO] [FML/]: [AppEng] Core Init
[20:49:36] [Server thread/INFO] [FML/]: Found 0 mods from the command line. Injecting into mod discoverer
[20:49:36] [Server thread/INFO] [FML/]: Searching /home/minecraft/Desktop/Cauldron 1.7.10 - 2/mods for mods
[20:49:37] [Server thread/INFO] [FML/]: Forge Mod Loader has identified 7 mods to load
[20:49:38] [Server thread/INFO] [FML/]: FML has found a non-mod file Baubles-1.7.10-1.0.1.10-api.zip in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
[20:49:38] [Server thread/INFO] [FML/FML]: Attempting connection with missing mods [mcp, FML, Forge, appliedenergistics2-core, appliedenergistics2, HeroSuits, zoocraftia] at CLIENT
[20:49:38] [Server thread/INFO] [FML/FML]: Attempting connection with missing mods [mcp, FML, Forge, appliedenergistics2-core, appliedenergistics2, HeroSuits, zoocraftia] at SERVER
[20:49:38] [Server thread/INFO] [FML/]: Processing ObjectHolder annotations
[20:49:38] [Server thread/INFO] [FML/]: Found 341 ObjectHolder annotations
[20:49:38] [Server thread/INFO] [FML/Forge]: Configured a dormant chunk cache size of 0
[20:49:39] [Server thread/INFO] [AE2:S/appliedenergistics2]: Pre Initialization ( started )
[20:49:39] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: func_145839_a(Lnet/minecraft/nbt/NBTTagCompound;)V - Transformed
[20:49:39] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: func_145841_b(Lnet/minecraft/nbt/NBTTagCompound;)V - Transformed
[20:49:39] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: Removing Interface ic2.api.energy.tile.IEnergySink from appeng/tile/powersink/IC2 because IC2 integration is disabled.
[20:49:39] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: Updated appeng/tile/powersink/IC2
[20:49:39] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: Removing Interface Reika.RotaryCraft.API.Power.AdvancedShaftPowerReceiver from appeng/tile/powersink/RotaryCraft because RotaryCraft integration is disabled.
[20:49:39] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: Removing Interface Reika.RotaryCraft.API.Interfaces.Transducerable from appeng/tile/powersink/RotaryCraft because RotaryCraft integration is disabled.
[20:49:39] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: Removing Method Tick_RotaryCraft from appeng/tile/powersink/RotaryCraft because RotaryCraft integration is disabled.
[20:49:39] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: Updated appeng/tile/powersink/RotaryCraft
[20:49:39] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: Removing Interface cofh.api.energy.IEnergyReceiver from appeng/tile/powersink/RedstoneFlux because RF integration is disabled.
[20:49:39] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: Updated appeng/tile/powersink/RedstoneFlux
[20:49:39] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: Removing Interface mekanism.api.energy.IStrictEnergyAcceptor from appeng/tile/powersink/MekJoules because Mekanism integration is disabled.
[20:49:39] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: Updated appeng/tile/powersink/MekJoules
[20:49:39] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: Removing Interface powercrystals.minefactoryreloaded.api.rednet.connectivity.IRedNetConnection from appeng/block/networking/BlockCableBus because MFR integration is disabled.
[20:49:39] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: Removing Method getConnectionType from appeng/block/networking/BlockCableBus because MFR integration is disabled.
[20:49:39] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: Updated appeng/block/networking/BlockCableBus
[20:49:39] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: Removing Interface buildcraft.api.tools.IToolWrench from appeng/items/tools/quartz/ToolQuartzWrench because BC integration is disabled.
[20:49:39] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: Updated appeng/items/tools/quartz/ToolQuartzWrench
[20:49:39] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: Removing Interface ic2.api.item.ISpecialElectricItem from appeng/items/tools/powered/powersink/IC2 because IC2 integration is disabled.
[20:49:39] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: Removing Interface ic2.api.item.IElectricItemManager from appeng/items/tools/powered/powersink/IC2 because IC2 integration is disabled.
[20:49:39] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: Removing Method getManager from appeng/items/tools/powered/powersink/IC2 because IC2 integration is disabled.
[20:49:39] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: Updated appeng/items/tools/powered/powersink/IC2
[20:49:39] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: Removing Interface cofh.api.energy.IEnergyContainerItem from appeng/items/tools/powered/powersink/RedstoneFlux because RFItem integration is disabled.
[20:49:39] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: Updated appeng/items/tools/powered/powersink/RedstoneFlux
[20:49:40] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: Removing Interface buildcraft.api.tools.IToolWrench from appeng/items/tools/ToolNetworkTool because BC integration is disabled.
[20:49:40] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: Updated appeng/items/tools/ToolNetworkTool
[20:49:40] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: Removing Interface buildcraft.api.transport.IPipeConnection from appeng/parts/misc/PartStorageBus because BC integration is disabled.
[20:49:40] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: Removing Method overridePipeConnection from appeng/parts/misc/PartStorageBus because BC integration is disabled.
[20:49:40] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: Updated appeng/parts/misc/PartStorageBus
[20:49:40] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: Removing Interface buildcraft.api.transport.IPipeConnection from appeng/parts/p2p/PartP2PItems because BC integration is disabled.
[20:49:40] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: Removing Method overridePipeConnection from appeng/parts/p2p/PartP2PItems because BC integration is disabled.
[20:49:40] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: Updated appeng/parts/p2p/PartP2PItems
[20:49:40] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: Removing Interface ic2.api.energy.tile.IEnergySink from appeng/parts/p2p/PartP2PIC2Power because IC2 integration is disabled.
[20:49:40] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: Removing Interface ic2.api.energy.tile.IEnergySource from appeng/parts/p2p/PartP2PIC2Power because IC2 integration is disabled.
[20:49:40] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: Updated appeng/parts/p2p/PartP2PIC2Power
[20:49:40] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: Removing Interface cofh.api.energy.IEnergyReceiver from appeng/parts/p2p/PartP2PRFPower because RF integration is disabled.
[20:49:40] [Server thread/INFO] [AE2-CORE/appliedenergistics2]: Updated appeng/parts/p2p/PartP2PRFPower
[20:49:40] [Server thread/INFO] [AE2:S/appliedenergistics2]: Starting AE2 VersionChecker
[20:49:40] [Server thread/INFO] [AE2:S/appliedenergistics2]: Pre Initialization ( ended after 1428ms )
[20:49:40] [AE2 VersionChecker/WARN] [/appliedenergistics2]: Exception in thread "AE2 VersionChecker" 
[20:49:40] [AE2 VersionChecker/WARN] [/appliedenergistics2]: java.lang.IllegalArgumentException: Raw channel stable did not contain any of the pre-programmed types.
[20:49:40] [AE2 VersionChecker/WARN] [/appliedenergistics2]: 	at appeng.services.version.VersionParser.parseChannel(VersionParser.java:117)
[20:49:40] [AE2 VersionChecker/WARN] [/appliedenergistics2]: 	at appeng.services.version.VersionParser.parseVersion(VersionParser.java:72)
[20:49:40] [AE2 VersionChecker/WARN] [/appliedenergistics2]: 	at appeng.services.version.VersionParser.parse(VersionParser.java:34)
[20:49:40] [AE2 VersionChecker/WARN] [/appliedenergistics2]: 	at appeng.services.version.ModVersionFetcher.get(ModVersionFetcher.java:34)
[20:49:40] [AE2 VersionChecker/WARN] [/appliedenergistics2]: 	at appeng.services.VersionChecker.processInterval(VersionChecker.java:106)
[20:49:40] [AE2 VersionChecker/WARN] [/appliedenergistics2]: 	at appeng.services.VersionChecker.run(VersionChecker.java:86)
[20:49:40] [AE2 VersionChecker/WARN] [/appliedenergistics2]: 	at java.lang.Thread.run(Thread.java:745)
[20:49:40] [Server thread/INFO] [FML/]: Applying holder lookups
[20:49:40] [Server thread/INFO] [FML/]: Holder lookups applied
[20:49:40] [Server thread/ERROR] [FML/]: Fatal errors were detected during the transition from PREINITIALIZATION to INITIALIZATION. Loading cannot continue
[20:49:40] [Server thread/ERROR] [FML/]: 
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{7.10.114.1388} [Forge Mod Loader] (cauldron-1.7.10-2.1403.1.54-server.jar) Unloaded->Constructed->Pre-initialized
	Forge{10.13.3.1403} [Minecraft Forge] (cauldron-1.7.10-2.1403.1.54-server.jar) Unloaded->Constructed->Pre-initialized
	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) Unloaded->Constructed->Pre-initialized
	HeroSuits{1.2} [Project Superhuman] (ProjectSuperhuman - v1.2 - 1.7.10.jar) Unloaded->Constructed->Errored
	zoocraftia{0.2} [Zoocraftia] (zoocraftia-0.2.jar) Unloaded->Constructed->Pre-initialized
[20:49:40] [Server thread/ERROR] [FML/]: The following problems were captured during this phase
[20:49:40] [Server thread/ERROR] [FML/]: Caught exception from HeroSuits
java.lang.NoClassDefFoundError: net/herosuits/item/ItemUtilityBelt
	at net.herosuits.HeroSuits.preInit(HeroSuits.java:555) ~[HeroSuits.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_95]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_95]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_95]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_95]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:KCauldron-1.7.10-2.1403.1.54]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_95]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_95]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_95]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_95]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:KCauldron-1.7.10-2.1403.1.54]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:KCauldron-1.7.10-2.1403.1.54]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_95]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_95]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_95]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_95]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:KCauldron-1.7.10-2.1403.1.54]
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:533) [Loader.class:KCauldron-1.7.10-2.1403.1.54]
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88) [FMLServerHandler.class:KCauldron-1.7.10-2.1403.1.54]
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:318) [FMLCommonHandler.class:KCauldron-1.7.10-2.1403.1.54]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:176) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_95]
Caused by: java.lang.ClassNotFoundException: net.herosuits.item.ItemUtilityBelt
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_95]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_95]
	... 33 more
Caused by: java.lang.NoClassDefFoundError: net/herosuits/item/ItemBaubleEquipment
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_95]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_95]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_95]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_95]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_95]
	... 33 more
Caused by: java.lang.ClassNotFoundException: net.herosuits.item.ItemBaubleEquipment
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_95]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_95]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_95]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_95]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_95]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_95]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_95]
	... 33 more
[20:49:40] [Server thread/WARN] [FML/]: Can't revert to frozen GameData state without freezing first.
[20:49:40] [Server thread/INFO] [FML/]: Applying holder lookups
[20:49:40] [Server thread/INFO] [FML/]: Holder lookups applied
[20:49:40] [Server thread/INFO] [FML/]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[20:49:40] [Server thread/INFO] [FML/]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.`

**Comment by parzivail** [comment]
@FEPVanceLee That looks like a Project Superhumam problem. If they require a specific Java version or dependency mod, make sure you have it

**Comment by thatsIch** [comment]
It requires herosuits mod or from whatever mod it is from
