### ISSUE TITLE
[Crash] java.lang.NoClassDefFoundError: appeng/parts/networking/PartCableCovered

### ISSUE THREAD

**Issue by vadimyer** [AppliedEnergistics/Applied-Energistics-2#2273]
I got this crash, not really sure what cause it. AE2 rv3 beta5. Running on server, Thermos B55.

```
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 5/8/16 6:32 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: appeng/parts/networking/PartCableCovered$1
	at appeng.parts.networking.PartCableCovered.getBoxes(PartCableCovered.java:96)
	at appeng.parts.CableBusContainer.getSelectedBoundingBoxesFromPool(CableBusContainer.java:736)
	at appeng.tile.networking.TileCableBus.getSelectedBoundingBoxesFromPool(TileCableBus.java:286)
	at appeng.tile.networking.TileCableBus.addCollidingBlockToList(TileCableBus.java:343)
	at appeng.block.AEBaseBlock.func_149743_a(AEBaseBlock.java:231)
	at net.minecraft.world.World.func_72945_a(World.java:2000)
	at cofh.asmhooks.HooksCore.getEntityCollisionBoxes(HooksCore.java:102)
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:747)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:526)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36)
	at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.func_148833_a(C03PacketPlayer.java:144)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1013)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:831)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: appeng.parts.networking.PartCableCovered$1
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Thermos Version: ca.tcpr:Thermos:1.7.10-1614.55
	Plugins: WorldEdit, JoinCommand, Skript, DupeFixer, OpenInv, ChunkFixer, ClearLag, AutoMessage, iPAddressViewer, WorldBorder, LokiBlockerLite, BanManager, VoidSpawn, WorldGuard, AutoSaveWorld, MultiWorld, RedstoneClockDetector, Setblock, MachineGuard_Reloaded, iConomy, PermissionsEx, SQLibrary, AnimalProtect, CustomHelp, ReactionRewards, Vault, HideStream, Prism, MyWarp, ChestShop, ShoppingCartReloaded, MultiHome, ColorMe, NoobProtector, Essentials, BattleTracker, BattleArena, Scavenger, ProtocolLib, PayDay, EssentialsProtect, ModFixNG, SuperVanish, ArenaSpleef, EssentialsSpawn
	Disabled Plugins: 
	Operating System: Linux (amd64) version 3.16.0-4-amd64
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2003288720 bytes (1910 MB) / 5064097792 bytes (4829 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 1 total; -Xmx12G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 55 mods loaded, 55 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (Thermos.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (Thermos.jar) 
	UCHIJAAAA	kimagine{0.2} [KImagine] (minecraft.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv3-beta-5} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJAAAA	IC2{2.2.817-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.817-experimental.jar) 
	UCHIJAAAA	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel-1.7.10-3.5.1.jar) 
	UCHIJAAAA	appliedenergistics2{rv3-beta-5} [Applied Energistics 2] (appliedenergistics2-rv3-beta-5.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
	UCHIJAAAA	BigReactors{0.4.5B} [Big Reactors] (BigReactors-0.4.5B.jar) 
	UCHIJAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1364.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenters-Blocks-3.3.7.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	Railcraft{9.8.0.0} [Railcraft] (Railcraft-1.7.10-9.8.0.0.jar) 
	UCHIJAAAA	chisel{2.5.1.44} [Chisel 2] (Chisel2-2.5.1.44.jar) 
	UCHIJAAAA	cmd{1.4} [Custom Music Discs] (Custom Music Discs-1.4 Server.jar) 
	UCHIJAAAA	DragonsRadioMod{1.7.1} [Dragon's Radio Mod] (Dragon's Radio Mod-MC1.7.10-1.7.1.jar) 
	UCHIJAAAA	endercore{1.7.10-0.2.0.32_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.32_beta.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) 
	UCHIJAAAA	EnderTech{1.7.10-0.3.2.405} [EnderTech] (EnderTech-1.7.10-0.3.2.405.jar) 
	UCHIJAAAA	EventHelper{1.6} [EventHelper] (EventHelper-1.6.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHIJAAAA	Forestry{4.2.10.58} [Forestry for Minecraft] (forestry_1.7.10-4.2.10.58.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
	UCHIJAAAA	MCFrames{1.0} [MCFrames] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
	UCHIJAAAA	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
	UCHIJAAAA	gvc{0.6.1} [�aGliby's�f Voice Chat Mod] (GlibysVC-1.7.10-0.6.2a.jar) 
	UCHIJAAAA	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite-1.7.10-2.0.3.jar) 
	UCHIJAAAA	GraviSuiteReloaded{1.7.10-0.9.1} [GraviSuiteReloaded] (GraviSuite_Reloaded-1.7.10-0.9.1.jar) 
	UCHIJAAAA	IC2CA{1.14.5.06} [IndustrialCraft 2 Combo Armors] (ic2ca-1.7.10-1.14.5.06.jar) 
	UCHIJAAAA	IC2NuclearControl{2.3.4a} [Nuclear Control 2] (IC2NuclearControl-2.3.4a.jar) 
	UCHIJAAAA	ImmersiveEngineering{0.7.5} [Immersive Engineering] (ImmersiveEngineering-0.7.5.jar) 
	UCHIJAAAA	IronChest{6.0.41.729} [Iron Chest] (Iron-Chests-Mod-1.7.10.jar) 
	UCHIJAAAA	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
	UCHIJAAAA	cfm{3.4.7} [�9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
	UCHIJAAAA	MrTJPCoreMod{1.1.0.31} [MrTJPCore] (MrTJPCore-1.7.10-1.1.0.31-universal.jar) 
	UCHIJAAAA	ProjRed|Core{4.7.0pre9.92} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre9.92-Base.jar) 
	UCHIJAAAA	ProjRed|Transmission{4.7.0pre9.92} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
	UCHIJAAAA	ProjRed|Transportation{4.7.0pre9.92} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre9.92-Mechanical.jar) 
	UCHIJAAAA	ProjRed|Exploration{4.7.0pre9.92} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre9.92-World.jar) 
	UCHIJAAAA	ProjRed|Compatibility{4.7.0pre9.92} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre9.92-Compat.jar) 
	UCHIJAAAA	ProjRed|Integration{4.7.0pre9.92} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
	UCHIJAAAA	ProjRed|Fabrication{4.7.0pre9.92} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre9.92-Fabrication.jar) 
	UCHIJAAAA	ProjRed|Illumination{4.7.0pre9.92} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre9.92-Lighting.jar) 
	UCHIJAAAA	ProjRed|Expansion{4.7.0pre9.92} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre9.92-Mechanical.jar) 
	UCHIJAAAA	RedstoneArsenal{1.7.10R1.1.1} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.1-89.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	AE2 Version: beta rv3-beta-5 for Forge 10.13.4.1448
	CoFHCore: -[1.7.10]3.0.3-303
	ThermalFoundation: -[1.7.10]1.2.0-102
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	RedstoneArsenal: -[1.7.10]1.1.1-89
	ThermalDynamics: -[1.7.10]1.1.0-161
	Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Bukkit, Cauldron, or other Bukkit replacement
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
Info: The following plugins have been disabled in the config: mail, agricraft, enderio, erebus, extrautilities, growthcraft, harvestcraft, immersiveengineering, magicalcrops, natura, plantmegapack, witchery
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BuildCraftCore:OFF, BuildCraftTransport:OFF, BuildCraftBuilder:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 31 / 100; [EntityPlayerMP['Aza7777'/332, l='world', x=1267.96, y=63.00, z=-2748.65](Aza7777 at 1267.9634761585032,63.0,-2748.6472250956986), EntityPlayerMP['Miha91137'/1192, l='world', x=-614.51, y=5.79, z=3365.52](Miha91137 at -614.5100511200134,5.785027703789236,3365.5239942351936), EntityPlayerMP['CATANA'/2078, l='world', x=5358.25, y=117.00, z=-7135.53](CATANA at 5358.252243320581,117.0,-7135.533029431573), EntityPlayerMP['krivedka'/2623, l='world', x=-1662.68, y=65.00, z=-1598.35](krivedka at -1662.6798806069398,65.0,-1598.352698779778), EntityPlayerMP['MbICb'/5413, l='world', x=4165.65, y=72.59, z=-5490.88](MbICb at 4165.648210532607,72.58593214059276,-5490.880953435356), EntityPlayerMP['Vencedor'/5166, l='world', x=-1241.95, y=69.00, z=-1207.84](Vencedor at -1241.9494355569707,69.0,-1207.8367205690056), EntityPlayerMP['Budeikoo'/6442, l='world', x=7576.70, y=60.11, z=1106.70](Budeikoo at 7576.699999988079,60.11163302697389,1106.699999988079), EntityPlayerMP['g1pokrat'/7268, l='world', x=-1325.98, y=66.00, z=750.36](g1pokrat at -1325.9753524978385,66.0,750.3603412138341), EntityPlayerMP['DikkeryDok'/7496, l='world', x=-3342.70, y=79.00, z=5959.30](DikkeryDok at -3342.699999988079,79.0,5959.300000011921), EntityPlayerMP['Anrel'/8174, l='world', x=3676.90, y=8.00, z=-2473.91](Anrel at 3676.898746164397,8.0,-2473.913395541933), EntityPlayerMP['gorodko'/8700, l='world', x=6105.63, y=68.71, z=7373.24](gorodko at 6105.626355296745,68.70822344761972,7373.2384980296465), EntityPlayerMP['lir'/9177, l='world', x=-8810.30, y=42.00, z=2103.26](lir at -8810.300000011921,42.0,2103.2640937167903), EntityPlayerMP['Detonator'/10428, l='world', x=-301.48, y=66.00, z=2511.22](Detonator at -301.47785643755003,66.0,2511.220964911179), EntityPlayerMP['GandalfJesus'/11276, l='world', x=150.61, y=74.00, z=302.82](GandalfJesus at 150.61156307230164,74.0,302.8171991376038), EntityPlayerMP['molchanov'/12126, l='world', x=-2582.90, y=53.00, z=4616.93](molchanov at -2582.8967737512553,53.0,4616.934767079894), EntityPlayerMP['Flexx97'/12321, l='world', x=-1253.59, y=61.21, z=-1218.40](Flexx97 at -1253.5892768809788,61.212234493193264,-1218.397053015447), EntityPlayerMP['morgraz'/13820, l='world', x=-5431.74, y=73.00, z=-146.54](morgraz at -5431.742475685612,73.0,-146.542841092689), EntityPlayerMP['xcenetron'/14856, l='world', x=-1726.57, y=79.00, z=-1580.13](xcenetron at -1726.5679287576704,79.0,-1580.1340131717923), EntityPlayerMP['Real'/14908, l='world', x=6131.53, y=73.49, z=7555.50](Real at 6131.527287601691,73.49064318920136,7555.499837985353), EntityPlayerMP['Flash'/19182, l='world', x=-266.41, y=69.00, z=2526.27](Flash at -266.4071041275563,69.0,2526.2709016604035), EntityPlayerMP['AVEL'/21735, l='world', x=-941.30, y=47.48, z=-1511.30](AVEL at -941.3000000119209,47.47888393155094,-1511.300000011921), EntityPlayerMP['vlad228'/22483, l='world', x=-1259.46, y=62.39, z=-1242.89](vlad228 at -1259.4561052873637,62.38522997479442,-1242.893090014698), EntityPlayerMP['zhangfei'/24733, l='world', x=-677.88, y=17.00, z=1238.35](zhangfei at -677.879797215812,17.0,1238.3453228027815), EntityPlayerMP['Exe'/24136, l='world', x=-2577.49, y=63.00, z=4614.84](Exe at -2577.492326977664,63.0,4614.842814800659), EntityPlayerMP['Encore'/25620, l='world', x=-1683.92, y=66.00, z=700.77](Encore at -1683.9219653004031,66.0,700.767096271444), EntityPlayerMP['Mozart'/29555, l='world', x=-945.77, y=64.00, z=-1516.95](Mozart at -945.7657272319883,64.0,-1516.9488003300542), EntityPlayerMP['akaSpiritus'/30592, l='world', x=-5450.53, y=79.00, z=-156.14](akaSpiritus at -5450.532595105955,79.0,-156.1425058091018), EntityPlayerMP['KanYouMan'/30859, l='world', x=-2244.63, y=65.00, z=-2349.23](KanYouMan at -2244.625512894499,65.0,-2349.228521804741), EntityPlayerMP['Ve1rT'/32387, l='world', x=-1700.94, y=69.00, z=-4542.02](Ve1rT at -1700.9377349008173,69.0,-4542.024759429652), EntityPlayerMP['SK0P'/36871, l='world', x=-1249.93, y=63.00, z=-1213.46](SK0P at -1249.9338272786006,63.0,-1213.4611510301784), EntityPlayerMP['Mojang'/41219, l='world', x=-1697.30, y=69.00, z=-4521.70](Mojang at -1697.300000011921,69.0,-4521.696422245179)]
	Is Modded: Definitely; Server brand changed to 'thermos,cauldron,craftbukkit,mcpc,kcauldron,fml,forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by yueh** [comment]
Will reopen, if you can reproduce it without any bukkit fork.
