### ISSUE TITLE
Crafting terminal crash

### ISSUE THREAD

**Issue by mightydanp** [AppliedEnergistics/Applied-Energistics-2#2380]
After placing a crafting terminal. After a unloading and loading a world multiple tumes the terminal becomes just a box that is see throw with black edges. If you right click on it i get this crash

java.lang.IllegalStateException: Already building!
	at net.minecraft.client.renderer.VertexBuffer.func_181668_a(VertexBuffer.java:291)
	at net.minecraft.client.shader.Framebuffer.func_178038_a(Framebuffer.java:264)
	at net.minecraft.client.shader.Framebuffer.func_147615_c(Framebuffer.java:229)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1103)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by mightydanp** [comment]
http://imgur.com/a/OxeuT

**Comment by mightydanp** [comment]
after placing a terminal and breaking it. It seems to give me the same error

**Comment by mightydanp** [comment]
update: when i open my inventroy it displays the error also

**Comment by shartte** [comment]
You need to include at least the Minecraft and AE2 version numbers.

**Comment by mightydanp** [comment]
1.10.2 minecraft i dont believe it has a version yet

**Comment by yueh** [comment]
No support for unreleased versions.
