### ISSUE TITLE
Autocrafting with a custom MineTweaker-Recipe causes Nullpointer Exception

### ISSUE THREAD

**Issue by TheVanoq** [AppliedEnergistics/Applied-Energistics-2#2441]
I added a new recipe to craft processors in the crafting grid without the use of inscribers. Automating it using the "Crafting Unit" and "Molecular Assembler" causes this problem:

http://minetweaker3.powerofbytes.com/forum/viewtopic.php?f=8&t=168

Minecraft: 1.7.10
Forge: 10.13.4.1614-1.7.10
AE2: rv2-stable-10

Any hopes of fixing this in the 1.7.10 version?

**Comment by leagris** [comment]
No issue with that in rv3.beta6

This script is perfectly functional:
```Javascript
val circuitCalculation = <appliedenergistics2:item.ItemMultiMaterial:16>;
val piston = <minecraft:piston>;
val pressCalculation = <appliedenergistics2:item.ItemMultiMaterial:13>;
val pureCertus = <appliedenergistics2:item.ItemMultiMaterial:10>;
//Make the Pressed Raw Material.
recipes.addShaped(circuitCalculation * 1, [
    [null, piston.reuse(), null],
    [null, pureCertus, null],
    [null, pressCalculation.reuse(), null]
]);
```

Now, instead of MT script, use AE2 native custom recipes instead, to save on need to synchronize client-side recipes on server join.

**Comment by TheVanoq** [comment]
Thanks for the quick reply! Does the possibility of AE2 native custom recipes work in the version I am using? If so, would you mind sending me some info on how to do it? I tried Google but couldn't find anything that doesn't use MineTweaker/ModTweaker.

**Comment by leagris** [comment]
I'd advise you to upgrade to rv3.beta6 as it has been more stable than rv2 or even rv1.

Custom Recipes: http://ae-mod.info/Custom-Recipes/
There is also an important README: `config/AppliedEnergistics2/recipes/README.html`

**Comment by TheVanoq** [comment]
Thanks. I just upgraded to the latest version and I'm creating a custom recipe for what I want to do. Sadly, it doesn't seem to work right. Would you mind pointing me in the right direction? I'm obviously doing something wrong and the README didn't help yet.

`
shapeless = oredictionary:ingotGold ae2:ItemMaterial.LogicProcessorPress -> ae2:ItemMaterial.LogicProcessorPrint
shapeless = ae2:ItemMaterial.PurifiedCertusQuartzCrystal ae2:ItemMaterial.CalcProcessorPress -> ae2:ItemMaterial.CalcProcessorPrint
shapeless = oredictionary:gemDiamond ae2:ItemMaterial.EngProcessorPress -> ae2:ItemMaterial.EngProcessorPrint
shapeless = oredictionary:itemSilicon ae2:ItemMaterial.SiliconPress -> ae2:ItemMaterial.SiliconPrint

shapeless = oredictionary:dustRedstone ae2:ItemMaterial.LogicProcessorPrint ae2:ItemMaterial.SiliconPrint -> ae2:ItemMaterial.LogicProcessor
shapeless = oredictionary:dustRedstone ae2:ItemMaterial.CalcProcessorPrint ae2:ItemMaterial.SiliconPrint -> ae2:ItemMaterial.CalcProcessor
shapeless = oredictionary:dustRedstone ae2:ItemMaterial.EngProcessorPrint ae2:ItemMaterial.SiliconPrint -> ae2:ItemMaterial.EngProcessor
`

And that's the exception I get:

`java.lang.RuntimeException: Invalid shaped ore recipe: XXX, XYX, XXX, X, null, Y, net.minecraft.item.Item@6ff415ad, 1xitem.appliedenergistics2.ItemMaterial@13
        at net.minecraftforge.oredict.ShapedOreRecipe.<init>(ShapedOreRecipe.java:116) ~[ShapedOreRecipe.class:?]
        at com.mark719.magicalcrops.handlers.ModCompat.loadCompat(ModCompat.java:1079) ~[ModCompat.class:?]
        at com.mark719.magicalcrops.MagicalCrops.init(MagicalCrops.java:55) ~[MagicalCrops.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:?]
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
        at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737) [Loader.class:?]
        at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97) [FMLServerHandler.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]`
