### ISSUE TITLE
Crashed in 1.10.2

### ISSUE THREAD

**Issue by sun-xu** [AppliedEnergistics/Applied-Energistics-2#2442]
I have doweloaded the code from branch"1.10" and built it,but it .........

mods:![mods](https://cloud.githubusercontent.com/assets/14010993/19148635/4655e7fe-8bf0-11e6-925f-ba327aef79d3.JPG)

forge version:1.10.2-12.18.1.2095

(please forget my poor English)
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AppEngCore (appliedenergistics2-rv4-alpha-0.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 16-10-6 下午6:05
Description: Unexpected error

java.lang.IllegalStateException: Already building!
	at net.minecraft.client.renderer.VertexBuffer.func_181668_a(VertexBuffer.java:284)
	at net.minecraft.client.renderer.RenderGlobal.func_174976_a(RenderGlobal.java:1902)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1625)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1556)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1335)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by shartte** [comment]
Optifine is not supported, and leads to this crash!

Sorry

**Comment by sun-xu** [comment]
Thanks!!
But Minecraft will be slower without Optifine.
Can you fix it??

**Comment by shartte** [comment]
Not at the Moment, sorry.

**Comment by sun-xu** [comment]
OK!
I have to use my intel core i7.haha.

By the way,the zh_CN.lang has some mistakes,I will fix it in my free time.
