### ISSUE TITLE
1.10.2 RV4 A4 Energy Acceptor causing server crash on join.

### ISSUE THREAD

**Issue by TheSkuggi** [AppliedEnergistics/Applied-Energistics-2#2587]
Noticed server crashed on join when updating to rv4 alpha 4 on 1.10.2 with forge 2122.  I am by no means a expert but I believe it's in the energy acceptor connection with ender io.  This does not happen in rv4 Alpha 3.  Hope this helps.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.58-beta.jar)
  AppEngCore (appliedenergistics2-rv4-alpha-4.jar)
  LoadingPlugin (Quark-r1.0-57.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 11/6/16 12:38 PM
Description: Ticking block entity

java.lang.NoClassDefFoundError: ic2/api/recipe/IRecipeInput
	at appeng.tile.powersink.AERootPoweredTile.<init>(AERootPoweredTile.java:68)
	at appeng.tile.powersink.AEBasePoweredTile.<init>(AEBasePoweredTile.java:22)
	at appeng.tile.grid.AENetworkPowerTile.<init>(AENetworkPowerTile.java:36)
	at appeng.tile.networking.TileEnergyAcceptor.<init>(TileEnergyAcceptor.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at appeng.block.AEBaseTileBlock.func_149915_a(AEBaseTileBlock.java:166)
	at net.minecraft.block.Block.createTileEntity(Block.java:1206)
	at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:766)
	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:784)
	at net.minecraft.world.World.func_175625_s(World.java:2402)
	at crazypants.enderio.conduit.power.PowerConduit.getExternalPowerReceptor(PowerConduit.java:451)
	at crazypants.enderio.conduit.power.PowerConduitNetwork.addConduit(PowerConduitNetwork.java:59)
	at crazypants.enderio.conduit.power.PowerConduitNetwork.addConduit(PowerConduitNetwork.java:20)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:50)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.init(AbstractConduitNetwork.java:37)
	at crazypants.enderio.conduit.power.PowerConduitNetwork.init(PowerConduitNetwork.java:34)
	at crazypants.enderio.conduit.ConduitUtil.ensureValidNetwork(ConduitUtil.java:57)
	at crazypants.enderio.conduit.AbstractConduit.updateNetwork(AbstractConduit.java:456)
	at crazypants.enderio.conduit.AbstractConduit.updateEntity(AbstractConduit.java:403)
	at crazypants.enderio.conduit.TileConduitBundle.doUpdate(TileConduitBundle.java:235)
	at com.enderio.core.common.TileEntityBase.func_73660_a(TileEntityBase.java:36)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: ic2.api.recipe.IRecipeInput
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 54 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at appeng.tile.powersink.AERootPoweredTile.<init>(AERootPoweredTile.java:68)
	at appeng.tile.powersink.AEBasePoweredTile.<init>(AEBasePoweredTile.java:22)
	at appeng.tile.grid.AENetworkPowerTile.<init>(AENetworkPowerTile.java:36)
	at appeng.tile.networking.TileEnergyAcceptor.<init>(TileEnergyAcceptor.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at appeng.block.AEBaseTileBlock.func_149915_a(AEBaseTileBlock.java:166)
	at net.minecraft.block.Block.createTileEntity(Block.java:1206)
	at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:766)
	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:784)
	at net.minecraft.world.World.func_175625_s(World.java:2402)
	at crazypants.enderio.conduit.power.PowerConduit.getExternalPowerReceptor(PowerConduit.java:451)
	at crazypants.enderio.conduit.power.PowerConduitNetwork.addConduit(PowerConduitNetwork.java:59)
	at crazypants.enderio.conduit.power.PowerConduitNetwork.addConduit(PowerConduitNetwork.java:20)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:50)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:55)
	at crazypants.enderio.conduit.AbstractConduitNetwork.init(AbstractConduitNetwork.java:37)
	at crazypants.enderio.conduit.power.PowerConduitNetwork.init(PowerConduitNetwork.java:34)
	at crazypants.enderio.conduit.ConduitUtil.ensureValidNetwork(ConduitUtil.java:57)
	at crazypants.enderio.conduit.AbstractConduit.updateNetwork(AbstractConduit.java:456)
	at crazypants.enderio.conduit.AbstractConduit.updateEntity(AbstractConduit.java:403)
	at crazypants.enderio.conduit.TileConduitBundle.doUpdate(TileConduitBundle.java:235)
	at com.enderio.core.common.TileEntityBase.func_73660_a(TileEntityBase.java:36)

-- Block entity being ticked --
Details:
	Name: blockConduitBundleTileEntity // crazypants.enderio.conduit.TileConduitBundle
	Block type: ID #1051 (tile.blockConduitBundle // crazypants.enderio.conduit.BlockConduitBundle)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-732,60,982), Chunk: (at 4,3,6 in -46,61; contains blocks -736,0,976 to -721,255,991), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
	Actual block type: ID #1051 (tile.blockConduitBundle // crazypants.enderio.conduit.BlockConduitBundle)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['TheSkuggi'/175, l='world', x=-735.93, y=66.00, z=982.89]]
	Chunk stats: ServerChunkCache: 684 Drop: 0
	Level seed: -4172967342145255235
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (11,64,215), Chunk: (at 11,4,7 in 0,13; contains blocks 0,0,208 to 15,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 48466227 game time, 9505301 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 26604 (now: false), thunder time: 83074 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 2.6.32-042stab112.15
	Java Version: 1.8.0_102, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 50409520 bytes (48 MB) / 1091543040 bytes (1040 MB) up to 5096538112 bytes (4860 MB)
	JVM Flags: 10 total; -Xms32M -Xmx5027M -XX:OnOutOfMemoryError=curl https://api.creeper.host/callbacks/minecraft/outofmemory.php?instance=mc-57f13a182df17 -k -XX:OnError=curl http://api.creeper.host/callbacks/minecraft/crash.php?instance=mc-57f13a182df17 -k -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:+CMSClassUnloadingEnabled -XX:ParallelGCThreads=4 -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.32 Powered by Forge 12.18.2.2122 39 mods loaded, 39 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2122-universal.jar) 
	UCHIJAAAA	Forge{12.18.2.2122} [Minecraft Forge] (forge-1.10.2-12.18.2.2122-universal.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv4-alpha-4} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.1.194} [Mantle] (Mantle-1.10.2-1.1.1.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.5.6b.jenkins424} [Tinkers' Construct] (TConstruct-1.10.2-2.5.6b.jar) 
	UCHIJAAAA	immersiveengineering{0.10-48} [Immersive Engineering] (ImmersiveEngineering-0.10-48.jar) 
	UCHIJAAAA	JEI{3.13.2.359} [Just Enough Items] (jei_1.10.2-3.13.2.359.jar) 
	UCHIJAAAA	abyssalcraft{1.9.3.4} [AbyssalCraft] (AbyssalCraft-1.10.2-1.9.3.4.jar) 
	UCHIJAAAA	acintegration{1.4.5} [AbyssalCraft Integration] (AbyssalCraft Integration-1.9.4-1.4.5.jar) 
	UCHIJAAAA	appliedenergistics2{rv4-alpha-4} [Applied Energistics 2] (appliedenergistics2-rv4-alpha-4.jar) 
	UCHIJAAAA	Quark{r1.0-57} [Quark] (Quark-r1.0-57.jar) 
	UCHIJAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAAAA	bagginses{2.4.2d} [Bagginses] (Bagginses-1.10.2-3.0.4e.jar) 
	UCHIJAAAA	Baubles{1.3.2} [Baubles] (Baubles-1.10.2-1.3.2.jar) 
	UCHIJAAAA	bdlib{1.12.2.17} [BD Lib] (bdlib-1.12.2.17-mc1.10.2.jar) 
	UCHIJAAAA	BiomesOPlenty{5.0.0.2091} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2091-universal.jar) 
	UCHIJAAAA	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.2-45.jar) 
	UCHIJAAAA	BloodMagic{1.9.4-2.1.0-66} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.1.0-66.jar) 
	UCHIJAAAA	Botania{r1.9-337} [Botania] (Botania r1.9-337.jar) 
	UCHIJAAAA	chancecubes{1.10.2-2.3.2.131} [Chance Cubes] (ChanceCubes-1.10.2-2.3.2.131.jar) 
	UCHIJAAAA	cyberware{beta-0.2.3} [Cyberware] (cyberware-1.9.4-1.10.2-beta-0.2.3.jar) 
	UCHIJAAAA	cyclopscore{0.8.0} [Cyclops Core] (CyclopsCore-1.9.4-0.8.0.jar) 
	UCHIJAAAA	lootablebodies{2.2.0} [DrCyano's Lootable Bodies] (DrCyanosLootableBodies_1.10.2-2.2.0.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.58-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.58-beta.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAA	EnderIO{1.10.2-3.0.1.127_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.127_beta.jar) 
	UCHIJAAAA	evilcraft{0.10.14} [EvilCraft] (EvilCraft-1.10.2-0.10.14.jar) 
	UCHIJAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-alpha-1.2.2.jar) 
	UCHIJAAAA	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCHIJAAAA	forestry{5.2.16.315} [Forestry] (forestry_1.10.2-5.2.16.315.jar) 
	UCHIJAAAA	gendustry{1.6.4.24} [GenDustry] (gendustry-1.6.4.24-mc1.10.2.jar) 
	UCHIJAAAA	JEFB{1.0.4} [Just Enough Forestry Bees] (jefb_1.10.2-1.0.4.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.3.0b2} [JourneyMap] (journeymap-1.10.2-5.3.0b2-unlimited.jar) 
	UCHIJAAAA	morebees{1.10.2-1.1.4} [More Bees] (morebees-1.10.2-1.1.4.jar) 
	UCHIJAAAA	natura{1.10.2-4.0.0.87} [Natura] (natura-1.10.2-4.0.0.87.jar) 
	UCHIJAAAA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHIJAAAA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.1.213.jar) 
	UCHIJAAAA	wawla{2.3.1.213} [What Are We Looking At] (Wawla-1.10.2-2.3.1.213.jar) 
	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.10.2-0.4.1.58-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
AppEngCore (appliedenergistics2-rv4-alpha-4.jar)
  appeng.transformer.asm.ASMIntegration
LoadingPlugin (Quark-r1.0-57.jar)
  vazkii.quark.base.asm.ClassTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- WailaIntegration (Enabled/Not Forced)

	AE2 Version: alpha rv4-alpha-4 for Forge 12.18.2.2104
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* AbyssalCraftAPI (1.8.5) from AbyssalCraft-1.10.2-1.9.3.4.jar
		* appliedenergistics2|API (rv4) from appliedenergistics2-rv4-alpha-4.jar
		* Baubles|API (1.3.1.0) from Baubles-1.10.2-1.3.2.jar
		* BloodMagic|API (@VERSION@) from BloodMagic-1.9.4-2.1.0-66.jar
		* BotaniaAPI (85) from Botania r1.9-337.jar
		* CoFHAPI (1.8.9R1.2.0B1) from extrautils2-1.10.2-alpha-1.2.2.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from extrautils2-1.10.2-alpha-1.2.2.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.10.2-3.0.1.127_beta.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.10.2-3.0.1.127_beta.jar
		* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.10.2-3.0.1.127_beta.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.10.2-3.0.1.127_beta.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.10.2-5.2.16.315.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.10.2-5.2.16.315.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.10.2-5.2.16.315.jar
		* ForestryAPI|climate (2.1.0) from forestry_1.10.2-5.2.16.315.jar
		* ForestryAPI|core (5.1.0) from forestry_1.10.2-5.2.16.315.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.10.2-5.2.16.315.jar
		* ForestryAPI|food (1.1.0) from forestry_1.10.2-5.2.16.315.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.10.2-5.2.16.315.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.10.2-5.2.16.315.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.10.2-5.2.16.315.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.10.2-5.2.16.315.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.10.2-5.2.16.315.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.10.2-5.2.16.315.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.10.2-5.2.16.315.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.10.2-5.2.16.315.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.10.2-5.2.16.315.jar
		* ForestryAPI|world (2.1.0) from forestry_1.10.2-5.2.16.315.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.4.24-mc1.10.2.jar
		* Guide-API|API (1.10.2-2.0.2-45) from Guide-API-1.10.2-2.0.2-45.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.10-48.jar
		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.10-48.jar
		* jeresources|API (0.5.4.68) from JustEnoughResources-1.10.2-0.5.4.68.jar
		* journeymap|client-api (1.3-SNAPSHOT) from journeymap-1.10.2-5.3.0b2-unlimited.jar
		* journeymap|client-api-display (1.3-SNAPSHOT) from journeymap-1.10.2-5.3.0b2-unlimited.jar
		* journeymap|client-api-event (1.3-SNAPSHOT) from journeymap-1.10.2-5.3.0b2-unlimited.jar
		* journeymap|client-api-model (1.3-SNAPSHOT) from journeymap-1.10.2-5.3.0b2-unlimited.jar
		* journeymap|client-api-util (1.3-SNAPSHOT) from journeymap-1.10.2-5.3.0b2-unlimited.jar
		* JustEnoughItemsAPI (4.10.1) from jei_1.10.2-3.13.2.359.jar
		* WailaAPI (1.3) from Waila-1.7.0-B3_1.9.4.jar
	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * An unknown AE2 API is installed (rv4 from appliedenergistics2-rv4-alpha-4.jar).
                    Ender IO was build against API version rv2 and may or may not work with a newer version.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/home/minecraft/mc-instances/mc-57f13a182df17/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/home/minecraft/mc-instances/mc-57f13a182df17/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/home/minecraft/mc-instances/mc-57f13a182df17/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/home/minecraft/mc-instances/mc-57f13a182df17/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/home/minecraft/mc-instances/mc-57f13a182df17/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/home/minecraft/mc-instances/mc-57f13a182df17/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/home/minecraft/mc-instances/mc-57f13a182df17/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/home/minecraft/mc-instances/mc-57f13a182df17/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/home/minecraft/mc-instances/mc-57f13a182df17/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BuildCraftCore:OFF, BuildCraftTransport:OFF, BuildCraftBuilder:OFF, RF:OFF, RFItem:OFF, MFR:OFF, DSU:OFF, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['TheSkuggi'/175, l='world', x=-735.93, y=66.00, z=982.89]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by yueh** [comment]
#2569
