### ISSUE TITLE
Crash on Startup rv3 beta 6

### ISSUE THREAD

**Issue by staircrusher** [AppliedEnergistics/Applied-Energistics-2#2814]
Server Crash almost instant after Start

#### Description
Server crash almost instant after start. Server was running without problems, but after normal sheduled restart it didn't start anymore.
Same crash already occured in the past. After purging all AE2 content (removed ae2 mod and addons from mod folder) everything went well... until now.

On the server some guys build a big storage system with about 1024 Storage Bus on 1024 Deep Storage units wit p2p tunnelt etc. It seems that the crash (after restarting) occured directly after this setup.

Crash even occurs in Single Player with downloaded world save.

#### Environment
FTB Infinity Evolved MP Server 2.6.0

Original Crash log is about 100mb, so i cut it cause its repeating.

Crash log pastebin: http://pastebin.com/ESHGHDtm

- Minecraft Version: 1.7.10
- AE2 Version: rv3 beta 6
- Forge Version: 10.13.4.1614

```
Description: Exception in server tick loop

java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
	at appeng.me.NetworkEventBus$EventMethod.invoke(NetworkEventBus.java:191)
	at appeng.me.NetworkEventBus$EventMethod.access$400(NetworkEventBus.java:165)
	at appeng.me.NetworkEventBus$MENetworkEventInfo.invoke(NetworkEventBus.java:215)
	at appeng.me.NetworkEventBus$MENetworkEventInfo.access$200(NetworkEventBus.java:201)
	at appeng.me.NetworkEventBus.postEventTo(NetworkEventBus.java:146)
	at appeng.me.Grid.postEventTo(Grid.java:228)
	at appeng.me.GridConnection.finalizeChannels(GridConnection.java:275)
	at appeng.me.pathfinding.ControllerChannelUpdater.visitConnection(ControllerChannelUpdater.java:44)
	at appeng.me.GridNode.beginVisit(GridNode.java:176)
	at appeng.me.cache.PathGridCache.onUpdateTick(PathGridCache.java:188)
	at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:43)
	at appeng.me.Grid.update(Grid.java:280)
	at appeng.hooks.TickHandler.onTick(TickHandler.java:239)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_549_TickHandler_onTick_TickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at appeng.me.NetworkEventBus$EventMethod.invoke(NetworkEventBus.java:183)
	... 19 more

```

**Comment by mindforger** [comment]
1.7.10 is not supported anymore, this looks like an infinite loop somehow, is this an official version or one of the foreign compiled versions with the anti-dupe bugfix?

if it is the official version, your world may be corrupted

**Comment by staircrusher** [comment]
thanks for the reply. It is the official version or rather the version that comes with infinity modpack

**Comment by mindforger** [comment]
if you got an idea where you may have created an infinite loop in your ME setup ..(honestly whould not be possible).. you could probably use mcedit to kill the bus

**Comment by xsun2001** [comment]
That sounds interesting.
@staircrusher Can I have your world?I will try to find the cause of this problem.

**Comment by staircrusher** [comment]
After editing the affected region with mcedit (i cut the me dense cables) everything is fina again.
I replaced every storage bus with an export bus and built a big "me drive wall" full with storage cells.
No crash yet and restarting the server works without crashing at startup.

@xsun2001  I don't have a copy from the damaged region anymore, but the edited version from mcedit. There I only cut the dense cables at the me controller multiblock and removed the power source (dense cell and energy acceptor) in the basement. So you only need to power it and connect those 4 dense wires. Then you replicated my issue. It would work until you restart or reload.

Region File: http://schwarzspiele.de/r.0.-1.zip  (affected chunk: X:27 Y:1 Z:-7)
seed (if needed): 9114700169440305538

**Comment by xsun2001** [comment]
Thank you.Let's play with bugs.

**Comment by xsun2001** [comment]
![2017-02-25_20 48 09](https://cloud.githubusercontent.com/assets/14010993/23331196/4c897570-fb9c-11e6-8146-66e0305e53f3.png)
@staircrusher I cannot find it.I must miss something...

**Comment by staircrusher** [comment]
Ok here is the setup (now with import bus instead storage bus):

One of 3 levels:
![2017-02-25_19 05 14](https://cloud.githubusercontent.com/assets/3681763/23333595/2b1865f8-fb8e-11e6-8428-4c04d4bf4b17.png)

![2017-02-25_19 05 26](https://cloud.githubusercontent.com/assets/3681763/23333603/56da3fc2-fb8e-11e6-8f1f-e1ea58b366d2.png)


ME Controller setup:
![2017-02-25_19 06 15](https://cloud.githubusercontent.com/assets/3681763/23333613/693cd864-fb8e-11e6-975c-beb821160893.png)


And the new drive wall:
![2017-02-25_19 06 31](https://cloud.githubusercontent.com/assets/3681763/23333620/81d2caf0-fb8e-11e6-8a15-89511ced0f16.png)


Its still running smooth without any crashes :-) So 1024 Import Buses working well.
After everything is importet in the drives, i will destroy all DSU`s... Maybe it will take a little bit, cause I had no nerves to insert Acceleration and Capacity Cards in about 1024 buses.

**Comment by xsun2001** [comment]
That is amazing. Please give me more time to think about it....
