### ISSUE TITLE
CRASH - Failed to save chunk (spatial cell)

### ISSUE THREAD

**Issue by Stervil98** [AppliedEnergistics/Applied-Energistics-2#3286]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 12/20/17 6:21 PM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_76670_c(ExtendedBlockStorage.java:88)
	at net.minecraft.world.chunk.Chunk.func_177413_a(Chunk.java:652)
	at net.minecraft.world.World.func_175642_b(World.java:858)
	at net.minecraft.world.World.func_180500_c(World.java:2839)
	at net.minecraft.world.World.func_175664_x(World.java:2757)
	at net.minecraft.world.chunk.Chunk.func_76594_o(Chunk.java:1279)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:398)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_76670_c(ExtendedBlockStorage.java:88)
	at net.minecraft.world.chunk.Chunk.func_177413_a(Chunk.java:652)
	at net.minecraft.world.World.func_175642_b(World.java:858)
	at net.minecraft.world.World.func_180500_c(World.java:2839)
	at net.minecraft.world.World.func_175664_x(World.java:2757)
	at net.minecraft.world.chunk.Chunk.func_76594_o(Chunk.java:1279)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:398)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['Stervil'/762, l='New World', x=107.59, y=101.05, z=234.67]]
	Chunk stats: ServerChunkCache: 661 Drop: 0
	Level seed: 5967517864726561566
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (208,64,256), Chunk: (at 0,4,0 in 13,16; contains blocks 208,0,256 to 223,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2798 game time, 2798 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 166615 (now: false), thunder time: 151998 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 260989928 bytes (248 MB) / 754974720 bytes (720 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.0.2512 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                  | Version      | Source                             | Signature                                |
	|:--------- |:------------------- |:------------ |:---------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft           | 1.12.2       | minecraft.jar                      | None                                     |
	| UCHIJAAAA | mcp                 | 9.42         | minecraft.jar                      | None                                     |
	| UCHIJAAAA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.0.2512.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge               | 14.23.0.2512 | forge-1.12.2-14.23.0.2512.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | mercurius_updater   | 1.0          | MercuriusUpdater-1.12.2.jar        | None                                     |
	| UCHIJAAAA | appliedenergistics2 | rv5-beta-1   | appliedenergistics2-rv5-beta-1.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: beta rv5-beta-1 for Forge 14.23.0.2491
	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:OFF, JEI:OFF, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Stervil'/762, l='New World', x=107.59, y=101.05, z=234.67]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

#### Description
When I try to save an area too big (bigger than 24 blocks in all directions) I get an instant crash of the client if SP or the server if MP, when it should save the area.

#### Environment
Crash reproduced in both, SinglePlayer and Server, instances.
tried in my modpack with another 158 mods, and also with the AE2 instaled alone.

- Minecraft Version: 1.12.2
- AE2 Version:  rv5 - stable 3
- Forge Version: 14.23.1.2566
                          14.23.1.2560
                          14.23.1.2555
                          14.23.0.2512
                          14.23.0.2485

**Comment by fscan** [comment]
_appliedenergistics2-rv5-beta-1.jar_

Just to be sure, can you please reproduce this with the newest AE2 and forge?

**Comment by fscan** [comment]
Also, a log with debug enabled (in appliedenergistic2.cfg) would be helpful.
