### ISSUE TITLE
Crash/ AE2 / 1.10.2

### ISSUE THREAD

**Issue by janjao12** [AppliedEnergistics/Applied-Energistics-2#3353]
I'm having issues with applied energistics 2, I'm having a server crash (i'm in single player, not even in a server) I have a AE2 system. Most part in overworld in my base and the ME Controllers and CPU's for crafitng inside a Compact Machine

appliedenergistics2-rv4-stable-1
Forge 12.18.3.2254
Minecraft 1.10.2

Description: Exception in server tick loop
 
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
    at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
    at appeng.me.NetworkEventBus.postEvent(NetworkEventBus.java:116)
    at appeng.me.Grid.postEvent(Grid.java:222)
    at appeng.me.cache.EnergyGridCache.publicPowerState(EnergyGridCache.java:238)
    at appeng.me.cache.EnergyGridCache.onUpdateTick(EnergyGridCache.java:206)
    at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:43)
    at appeng.me.Grid.update(Grid.java:280)
    at appeng.hooks.TickHandler.onTick(TickHandler.java:236)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_600_TickHandler_onTick_TickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:261)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)

Full Crash here: https://pastebin.com/4Jd6AnEq

**Comment by ktole1999** [comment]
does it crash if its not in a compact machine?

**Comment by janjao12** [comment]
I already resolved the issue.
Aparently, when my energy is empty and the AE2 discharge is causing the crash. 
I entered in the map and fastenly put 6 dense energy cells (I cheated), put my energy system back and the problem was not occurring anymore

**Comment by janjao12** [comment]
Probably the problem is with the ae2 inside the compact machine. IDK.
Maybe if the problem continuous, I return to the issue. Bye

**Comment by yueh** [comment]
At this point 1.10 can be considered EOL, so there won't be any further fixes.

**Comment by TheFlash787** [comment]
Hello, I am also having this issue on a public server. As it is happening randomly with many people on, There is no definite solution as to who has the dodgy power system. Has this been referenced anywhere for 1.12?

Thanks.

**Comment by fscan** [comment]
If this is happening for you on 1.12.2, please open a new issue with a crash log attached.
