### ISSUE TITLE
Crash on server stop

### ISSUE THREAD

**Issue by LemADEC** [AppliedEnergistics/Applied-Energistics-2#3602]
#### Description
When server stops during boot, before loading the world, AE2 will crash on stopping the server.
```
[18:15:40] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Energistics 2 (appliedenergistics2)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: Caused by: java.lang.NullPointerException
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at appeng.core.AppEng.serverStopped(AppEng.java:274)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at java.lang.reflect.Method.invoke(Method.java:498)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at java.lang.reflect.Method.invoke(Method.java:498)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at java.lang.reflect.Method.invoke(Method.java:498)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at net.minecraftforge.fml.common.Loader.serverStopped(Loader.java:855)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStopped(FMLCommonHandler.java:507)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:587)
[18:15:40] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at java.lang.Thread.run(Thread.java:748)
[18:16:05] [Server Shutdown Thread/INFO] [minecraft/MinecraftServer]: Stopping server
```
#### Environment
Dedicated server, while debugging a modpack

- Minecraft Version: 1.12.2
- AE2 Version: rv6-alpha-1
- Forge Version: 14.23.4.2729

**Comment by yueh** [comment]
It is already crashing or being killed, so there is no need to safeguard against an unpredictable state caused by it.
