### ISSUE TITLE
ERror with Thermal expansion

### ISSUE THREAD

**Issue by ClearRelic24** [AppliedEnergistics/Applied-Energistics-2#3722]
#### Description
a Error was generate sytemating 
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 9/11/18 12:11 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Energistics 2 (appliedenergistics2)
Caused by: java.lang.IllegalArgumentException: Failed to register dimension for id 2, One is already registered
	at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:119)
	at appeng.core.Registration.registerSpatialDimension(Registration.java:222)
	at appeng.core.Registration.postInit(Registration.java:397)
	at appeng.core.AppEng.postInit(AppEng.java:252)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:280)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:258)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:149)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:760)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 718229400 bytes (684 MB) / 2113929216 bytes (2016 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.3.2681 Optifine OptiFine_1.12.2_HD_U_D3 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version           | Source                                          | Signature                                |
	|:----- |:------------------- |:----------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJ | minecraft           | 1.12.2            | minecraft.jar                                   | None                                     |
	| UCHIJ | mcp                 | 9.42              | minecraft.jar                                   | None                                     |
	| UCHIJ | FML                 | 8.0.99.99         | forge-1.12.2-14.23.3.2681.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ | forge               | 14.23.3.2681      | forge-1.12.2-14.23.3.2681.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ | securitycraft       | v1.8.4.1          | [1.12.x]+SecurityCraft+v1.8.4.1.jar             | None                                     |
	| UCHIE | appliedenergistics2 | rv5-stable-10     | appliedenergistics2-rv5-stable-10.jar           | None                                     |
	| UCHIJ | codechickenlib      | 3.2.0.345         | CodeChickenLib-1.12.2-3.2.0.345-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJ | redstoneflux        | 2.0.2             | RedstoneFlux-1.12-2.0.2.3-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJ | cofhcore            | 4.5.2             | CoFHCore-1.12.2-4.5.2.19-universal.jar          | None                                     |
	| UCHIJ | cofhworld           | 1.2.0             | CoFHWorld-1.12.2-1.2.0.5-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJ | flansmod            | 5.5.2             | Flan's Mod-1.12.2-5.5.2.jar                     | None                                     |
	| UCHIJ | flansmodapocalypse  | 1.0               | Flan's Mod-1.12.2-5.5.2.jar                     | None                                     |
	| UCHIJ | mekanism            | 1.12.2-9.4.13.349 | Mekanism-1.12.2-9.4.13.349.jar                  | None                                     |
	| UCHIJ | thermalfoundation   | 2.5.0             | ThermalFoundation-1.12.2-2.5.0.19-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJ | thermalexpansion    | 5.5.0             | ThermalExpansion-1.12.2-5.5.0.29-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJ | thermaldynamics     | 2.5.1             | ThermalDynamics-1.12.2-2.5.1.14-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 22.20.16.4749' Renderer: 'Intel(R) HD Graphics 620'
	AE2 Version: stable rv5-stable-10 for Forge 14.23.1.2554
	OptiFine Version: OptiFine_1.12.2_HD_U_D3
	OptiFine Build: 20180515-125031
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 - Build 22.20.16.4749
	OpenGlRenderer: Intel(R) HD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 4
#### Environment
A error was gerenate whit termal expansipn
1.12.2
Thermal expandsion and applied
- Minecraft Version: 
- AE2 Version: rv11
- Forge Version: 1.12

**Comment by Tahakk** [comment]
I'm not sure why you think this is TE related as it is nowhere in log. There is problem with dimension, which TE doesn't use as far as I know. Take a look at DIM 2 since AE2 have problem with it.

**Comment by covers1624** [comment]
Yeah, TE doesn't have any dimensions.

**Comment by mindforger** [comment]
security craft speaks about secret rooms, how high are possibilitys they use anotehr dimension ? :dagger: 

for your issue, go into the config and assign another dimension ID for spatial dimensions other than 0, 1 or 2 (0 and 1 being nether and overworld and 2 used by somebody else) keept that in mid if yiou want to shug in other mods with additional dimensions
