### ISSUE TITLE
ConcurrentModificationException when loading into world

### ISSUE THREAD

**Issue by Direcub** [AppliedEnergistics/Applied-Energistics-2#3800]
Whenever i load my world my fps stutters heavily and eventually the game freezes 
When the game locks it never starts back up again,

Using custom modpack i made in twitch client, in Singleplayer

log: https://pastebin.com/X0kNfjdK

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-3
- Forge Version: 14.23.5.2770

**Comment by yueh** [comment]
Does this happen always? If so can you try and reduce the amount of mods to a mininum amount possible, or alternative remove just one or 2 until it no longer appears?

On the first glance it looks like something tries to use multithreaded worldloading, which is just wrong and we are just the first mod affected by it and crash therefore.

**Comment by Direcub** [comment]
Will do this evening

**Comment by gtokarz** [comment]
@Direcub what was your findings, having same problem in my quite random private SP pack

**Comment by Direcub** [comment]
i couldnt find the mod causing it. No matter the combonation it seemed to happen at random and only in that world

**Comment by Shybella** [comment]
Encountering this too. 

```Time: 1/7/19 3:23 AM
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.remove(Unknown Source)
	at appeng.me.cache.EnergyGridCache.extractProviderPower(EnergyGridCache.java:316)
	at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:248)
	at appeng.me.cache.EnergyGridCache.onUpdateTick(EnergyGridCache.java:199)
	at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:43)
	at appeng.me.Grid.update(Grid.java:280)
	at appeng.hooks.TickHandler.onTick(TickHandler.java:228)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1573_TickHandler_onTick_TickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:677)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:634)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.LinkedHashMap$LinkedHashIterator.remove(Unknown Source)
	at appeng.me.cache.EnergyGridCache.extractProviderPower(EnergyGridCache.java:316)
	at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:248)
	at appeng.me.cache.EnergyGridCache.onUpdateTick(EnergyGridCache.java:199)
	at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:43)
	at appeng.me.Grid.update(Grid.java:280)
	at appeng.hooks.TickHandler.onTick(TickHandler.java:228)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1573_TickHandler_onTick_TickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:677)

-- Sponge PhaseTracker --
Details:
	Phase Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjk000(MinecraftServer.java:3980)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:889)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:371)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:558)
	at java.lang.Thread.run(Unknown Source)

**Comment by mindforger** [comment]
>Sponge PhaseTracker

can you possibly test without sponge?

other than that, this MAY be an power issue, try to add some dense enrgy cells to your network, it is possible that your system has too low capacity and stall during startup in an infinite loop ... and maybe sponge with some tick shenanigangs grinds it to a halt

**Comment by Shybella** [comment]
OP wasn't using Sponge.

Sponge has nothing to do with this error.

**Comment by mindforger** [comment]
Was i referring to op?  I quoted your log and the advice was meant in general, how about being constructive and check for what i wrote?

**Comment by Shybella** [comment]
Original poster.

If you check his crash report, he's not using Sponge. It's just a bias towards Sponge and if someone is gonna to push bias in-front of me I'm going to slap you down.

Stop it.

**Comment by Mordenkainen** [comment]
So in that case perhaps help us out a little. You did not post your whole log so we can not see what mods you have so we cannot look for mods you may have in common.

**Comment by Shybella** [comment]
#3812, #3831

Plenty of crash reports to build enough correlation. I don't understand the Sponge hate and it's completely unnecessary. 

Suddenly people care about this because "Sponge". Really interesting.

**Comment by yueh** [comment]
Asking to try it without sponge is perfectly fine. It could easily be caused by some changes to chunkloading or similar system, which sponge likes to do and some other mod might simply include similar changes because they claimed it should be 5% faster but crashes in return.

It would simply remove some variables and could make it easier. Or at least rule it out as possible cause.

But it appears you are not actually interested in identifying a potential cause as well as reject a simple and quick request. So I do not see any chance to get something useful out of it from discussing it any further.
