### ISSUE TITLE
Network tool executing task error

### ISSUE THREAD

**Issue by Orygeunik** [AppliedEnergistics/Applied-Energistics-2#3826]
**Describe the bug**
In the server console, if the client uses a network tool on the door, an error appears

**To Reproduce**
1. Take in hand network tool
2. Right-click on the installed wooden door
3. To obtain the error in the console

**Additional context**

> [20:23:44] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=half, clazz=class net.minecraft.block.BlockDoor$EnumDoorHalf, values=[upper, lower]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_181]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=half, clazz=class net.minecraft.block.BlockDoor$EnumDoorHalf, values=[upper, lower]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201) ~[awu$a.class:?]
	at net.minecraft.block.BlockDoor.func_189540_a(BlockDoor.java:180) ~[aqa.class:?]
	at appeng.items.tools.ToolNetworkTool.serverSideToolLogic(ToolNetworkTool.java:153) ~[ToolNetworkTool.class:?]
	at appeng.core.sync.packets.PacketClick.serverPacketData(PacketClick.java:135) ~[PacketClick.class:?]
	at appeng.core.sync.network.AppEngServerPacketHandler$1.call(AppEngServerPacketHandler.java:57) ~[AppEngServerPacketHandler$1.class:?]
	at appeng.core.sync.AppEngPacket.func_148833_a(AppEngPacket.java:126) ~[AppEngPacket.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_181]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

**Environment**
MP
jre1.8.0_181 (Upgrade to 191 in queue)
Mods (excluding dependencies):

- buildcraft-7.99.19
- buildcraft-compat-7.99.15
- forestry_1.12.2-5.8.2.374
- industrialcraft-2-2.8.103-ex112
- jei_1.12.2-4.13.1.220
- ProjectRed-1.12.2-4.9.1.92
- UniDict-1.12.2-2.9.1
- TConstruct-1.12.2-2.11.0.106
- Thaumcraft-1.12.2-6.1.BETA26
- practicallogistics2-1.12.2-3.0.4
- ironchest-1.12.2-7.0.52.838
---
- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-4
- Forge Version: 1.12.2 - 14.23.5.2775

**Comment by yueh** [comment]
Cannot reproduce it in either SP or MP.

**Comment by Orygeunik** [comment]
Ok, pls try to use [this server](https://drive.google.com/open?id=1illrAYguTjP5IvL0CXFGKem-5C5i6oWr)
Only run, everything configured
