### ISSUE TITLE
game crash when launched

### ISSUE THREAD

**Issue by armbine64** [AppliedEnergistics/Applied-Energistics-2#3912]
put in the flans mod and just crash when I started the game

---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.12.2-0.5.43.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2 (1).jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63 (1).jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.20.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 1/21/19 5:11 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Energistics 2 (appliedenergistics2)
Caused by: java.lang.IllegalArgumentException: Failed to register dimension for id 2, One is already registered
	at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:134)
	at appeng.core.Registration.registerSpatialDimension(Registration.java:201)
	at appeng.core.Registration.postInit(Registration.java:352)
	at appeng.core.AppEng.postInit(AppEng.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 703704640 bytes (671 MB) / 2818572288 bytes (2688 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E3 74 mods loaded, 74 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                | Version                  | Source                                                | Signature                                |
	|:------ |:--------------------------------- |:------------------------ |:----------------------------------------------------- |:---------------------------------------- |
	| UCHIJ  | minecraft                         | 1.12.2                   | minecraft.jar                                         | None                                     |
	| UCHIJ  | mcp                               | 9.42                     | minecraft.jar                                         | None                                     |
	| UCHIJ  | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2768.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ  | forge                             | 14.23.5.2768             | forge-1.12.2-14.23.5.2768.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ  | micdoodlecore                     |                          | minecraft.jar                                         | None                                     |
	| UCHIJ  | ctm                               | MC1.12.2-0.3.2.20        | CTM-MC1.12.2-0.3.2.20.jar                             | None                                     |
	| UCHIEE | appliedenergistics2               | rv6-stable-6             | appliedenergistics2-rv6-stable-6.jar                  | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| UCHI   | bibliocraft                       | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2] (1).jar                 | None                                     |
	| UCHI   | biomesoplenty                     | 7.0.1.2419               | BiomesOPlenty-1.12.2-7.0.1.2419-universal.jar         | None                                     |
	| UCHI   | buildcraftlib                     | 7.99.19                  | buildcraft-7.99.19.jar                                | None                                     |
	| UCHI   | buildcraftcore                    | 7.99.19                  | buildcraft-7.99.19.jar                                | None                                     |
	| UCHI   | buildcraftbuilders                | 7.99.19                  | buildcraft-7.99.19.jar                                | None                                     |
	| UCHI   | buildcraftenergy                  | 7.99.19                  | buildcraft-7.99.19.jar                                | None                                     |
	| UCHI   | buildcraftfactory                 | 7.99.19                  | buildcraft-7.99.19.jar                                | None                                     |
	| UCHI   | buildcraftrobotics                | 7.99.19                  | buildcraft-7.99.19.jar                                | None                                     |
	| UCHI   | buildcrafttransport               | 7.99.19                  | buildcraft-7.99.19.jar                                | None                                     |
	| UCHI   | buildcraftsilicon                 | 7.99.19                  | buildcraft-7.99.19.jar                                | None                                     |
	| UCHI   | chesttransporter                  | 2.8.8                    | ChestTransporter-1.12.2-2.8.8 (1).jar                 | None                                     |
	| UCHI   | chisel                            | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                          | None                                     |
	| UCHI   | configmod                         | v1.0                     | coroutil-1.12.1-1.2.15.jar                            | None                                     |
	| UCHI   | extendedrenderer                  | v1.0                     | coroutil-1.12.1-1.2.15.jar                            | None                                     |
	| UCHI   | coroutil                          | 1.12.1-1.2.15            | coroutil-1.12.1-1.2.15.jar                            | None                                     |
	| UCHI   | cucumber                          | 1.1.3                    | Cucumber-1.12.2-1.1.3.jar                             | None                                     |
	| UCHI   | endercore                         | 1.12.2-0.5.43            | EnderCore-1.12.2-0.5.43.jar                           | None                                     |
	| UCHI   | jei                               | 4.13.1.225               | jei_1.12.2-4.13.1.225.jar                             | None                                     |
	| UCHI   | enderio                           | 5.0.39                   | EnderIO-base-1.12.2-5.0.39.jar                        | None                                     |
	| UCHI   | enderiointegrationtic             | 5.0.39                   | EnderIO-integration-tic-1.12.2-5.0.39.jar             | None                                     |
	| UCHI   | enderiobase                       | 5.0.39                   | EnderIO-base-1.12.2-5.0.39.jar                        | None                                     |
	| UCHI   | enderioconduits                   | 5.0.39                   | EnderIO-conduits-1.12.2-5.0.39.jar                    | None                                     |
	| UCHI   | enderiopowertools                 | 5.0.39                   | EnderIO-conduits-1.12.2-5.0.39.jar                    | None                                     |
	| UCHI   | enderioconduitsappliedenergistics | 5.0.39                   | EnderIO-conduits-appliedenergistics-1.12.2-5.0.39.jar | None                                     |
	| UCHI   | enderioconduitsopencomputers      | 5.0.39                   | EnderIO-conduits-opencomputers-1.12.2-5.0.39.jar      | None                                     |
	| UCHI   | enderiointegrationforestry        | 5.0.39                   | EnderIO-integration-forestry-1.12.2-5.0.39.jar        | None                                     |
	| UCHI   | mantle                            | 1.12-1.3.3.39            | Mantle-1.12-1.3.3.39.jar                              | None                                     |
	| UCHI   | twilightforest                    | 3.8.689                  | twilightforest-1.12.2-3.8.689-universal.jar           | None                                     |
	| UCHI   | tconstruct                        | 1.12.2-2.11.0.106        | TConstruct-1.12.2-2.11.0.106.jar                      | None                                     |
	| UCHI   | enderiointegrationticlate         | 5.0.39                   | EnderIO-integration-tic-1.12.2-5.0.39.jar             | None                                     |
	| UCHI   | enderiomachines                   | 5.0.39                   | EnderIO-machines-1.12.2-5.0.39.jar                    | None                                     |
	| UCHI   | extrautils2                       | 1.0                      | extrautils2-1.12-1.9.8.jar                            | None                                     |
	| UCHI   | flansmod                          | 5.5.2                    | Flan's Mod-1.12.2-5.5.2.jar                           | None                                     |
	| UCHI   | flansmodapocalypse                | 1.0                      | Flan's Mod-1.12.2-5.5.2.jar                           | None                                     |
	| UCHI   | forgelin                          | 1.8.2                    | Forgelin-1.8.2.jar                                    | None                                     |
	| UCHI   | galacticraftcore                  | 4.0.1.181                | Galacticraft-Mod-1.12.2 (1).jar                       | None                                     |
	| UCHI   | teslacorelib                      | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15 (1).jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHI   | industrialforegoing               | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.12.4-228.jar             | None                                     |
	| UCHI   | inventorytweaks                   | 1.63+release.109.220f184 | InventoryTweaks-1.63 (1).jar                          | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHI   | ironbackpacks                     | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12 (4).jar                 | None                                     |
	| UCHI   | ironchest                         | 1.12.2-7.0.54.838        | ironchest-1.12.2-7.0.54.838.jar                       | None                                     |
	| UCHI   | ironfurnaces                      | 1.3.1                    | ironfurnaces-1.3.1.jar                                | None                                     |
	| UCHI   | irontanks                         | 2.1.0-beta.5             | irontanks-2.1.0-beta.5 (2).jar                        | None                                     |
	| UCHI   | journeymap                        | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2 (4).jar                       | None                                     |
	| UCHI   | lycanitesmobs                     | 1.20.5.1 - MC 1.12.2     | LycanitesMobsComplete+1.20.5.1+[1.12.2].jar           | None                                     |
	| UCHI   | arcticmobs                        | 1.20.5.1 - MC 1.12.2     | LycanitesMobsComplete+1.20.5.1+[1.12.2].jar           | None                                     |
	| UCHI   | demonmobs                         | 1.20.5.1 - MC 1.12.2     | LycanitesMobsComplete+1.20.5.1+[1.12.2].jar           | None                                     |
	| UCHI   | desertmobs                        | 1.20.5.1 - MC 1.12.2     | LycanitesMobsComplete+1.20.5.1+[1.12.2].jar           | None                                     |
	| UCHI   | elementalmobs                     | 1.20.5.1 - MC 1.12.2     | LycanitesMobsComplete+1.20.5.1+[1.12.2].jar           | None                                     |
	| UCHI   | forestmobs                        | 1.20.5.1 - MC 1.12.2     | LycanitesMobsComplete+1.20.5.1+[1.12.2].jar           | None                                     |
	| UCHI   | freshwatermobs                    | 1.20.5.1 - MC 1.12.2     | LycanitesMobsComplete+1.20.5.1+[1.12.2].jar           | None                                     |
	| UCHI   | infernomobs                       | 1.20.5.1 - MC 1.12.2     | LycanitesMobsComplete+1.20.5.1+[1.12.2].jar           | None                                     |
	| UCHI   | junglemobs                        | 1.20.5.1 - MC 1.12.2     | LycanitesMobsComplete+1.20.5.1+[1.12.2].jar           | None                                     |
	| UCHI   | mountainmobs                      | 1.20.5.1 - MC 1.12.2     | LycanitesMobsComplete+1.20.5.1+[1.12.2].jar           | None                                     |
	| UCHI   | plainsmobs                        | 1.20.5.1 - MC 1.12.2     | LycanitesMobsComplete+1.20.5.1+[1.12.2].jar           | None                                     |
	| UCHI   | saltwatermobs                     | 1.20.5.1 - MC 1.12.2     | LycanitesMobsComplete+1.20.5.1+[1.12.2].jar           | None                                     |
	| UCHI   | shadowmobs                        | 1.20.5.1 - MC 1.12.2     | LycanitesMobsComplete+1.20.5.1+[1.12.2].jar           | None                                     |
	| UCHI   | swampmobs                         | 1.20.5.1 - MC 1.12.2     | LycanitesMobsComplete+1.20.5.1+[1.12.2].jar           | None                                     |
	| UCHI   | millenaire                        | Millénaire 7.1.1         | millenaire-1.12.2-7.1.1.jar                           | None                                     |
	| UCHI   | mysticalagriculture               | 1.7.0                    | MysticalAgriculture-1.12.2-1.7.0.jar                  | None                                     |
	| UCHI   | mysticalagradditions              | 1.2.10                   | MysticalAgradditions-1.12.2-1.2.10.jar                | None                                     |
	| UCHI   | tinkertoolleveling                | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                   | None                                     |
	| UCHI   | torohealthmod                     | 1.12.2-11                | torohealth-1.12.2-11 (1).jar                          | None                                     |
	| UCHI   | veinminer                         | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar                 | None                                     |
	| UCHI   | veinminermodsupport               | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar                 | None                                     |
	| UCHI   | weather2                          | 1.12.1-2.6.12            | weather2-1.12.1-2.6.12 (1).jar                        | None                                     |
	| UCHI   | teslacorelib_registries           | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15 (1).jar                  | None                                     |

	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.12.2-0.5.43.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
MicdoodlePlugin (MicdoodleCore-1.12.2 (1).jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63 (1).jar)
  invtweaks.forge.asm.ContainerTransformer
ForgelinPlugin (Forgelin-1.8.2.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.2.20.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4549' Renderer: 'Intel(R) HD Graphics 4600'
	AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)

	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.3.0 - Build 20.19.15.4549
	OpenGlRenderer: Intel(R) HD Graphics 4600
	OpenGlVendor: Intel
	CpuCount: 8

**Comment by mindforger** [comment]
>java.lang.IllegalArgumentException: Failed to register dimension for id 2, One is already registered

check your configs, you got an duplicate dimension id

**Comment by armbine64** [comment]
yeah um got a lot of configs you know which one?

**Comment by armbine64** [comment]
wait I found it what do I do with it?

**Comment by armbine64** [comment]
> > java.lang.IllegalArgumentException: Failed to register dimension for id 2, One is already registered
> 
> check your configs, you got an duplicate dimension id
yeah um got a lot of configs you know which one?

**Comment by mindforger** [comment]
Change the used dimension either in teh ae config or change it in the other mod so they are not using the same id

**Comment by mindforger** [comment]
Beware, changing the id may corrupt existing savegames.

**Comment by armbine64** [comment]
> Change the used dimension either in teh ae config or change it in the other mod so they are not using the same id

thanks, for your help it work
