### ISSUE TITLE
Server crash caused by AE2 network cache error

### ISSUE THREAD

**Issue by Laotouy** [AppliedEnergistics/Applied-Energistics-2#3950]
Umm... Hi, I am running a public MInecraft server with AE2 and some other mods
 There were about 20 player online on average each day. There was an error takes place everyday
and leads to the server crash. could u please help me to fix this problem? As far as I can see the Network cache error may cause this problem  . I have posted the logs and the information
of my server as well as the version of forge and AE2. The most possible
way to fix it has been added to the bottom of the post. I wish you can use it as an reference or gain inspiration from it. :D And ,Have a Good day.~
P.s. I'm a operator from China  and my English was not  very well.If you cant
understand what i am saying you can contact me

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-6
- Forge Version: 2808

[20:09:57] [Server thread/WARN] []: java.lang.NullPointerException
[20:09:57] [Server thread/WARN] []: 	at appeng.me.cache.helpers.TickTracker.compareTo(TickTracker.java:81)
[20:09:57] [Server thread/WARN] []: 	at appeng.me.cache.helpers.TickTracker.compareTo(TickTracker.java:34)
[20:09:57] [Server thread/WARN] []: 	at java.util.PriorityQueue.siftDownComparable(Unknown Source)
[20:09:57] [Server thread/WARN] []: 	at java.util.PriorityQueue.siftDown(Unknown Source)
[20:09:57] [Server thread/WARN] []: 	at java.util.PriorityQueue.poll(Unknown Source)
[20:09:57] [Server thread/WARN] []: 	at appeng.me.cache.TickManagerCache.onUpdateTick(TickManagerCache.java:93)
[20:09:57] [Server thread/WARN] []: 	at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:43)
[20:09:57] [Server thread/WARN] []: 	at appeng.me.Grid.update(Grid.java:280)
[20:09:57] [Server thread/WARN] []: 	at appeng.hooks.TickHandler.onTick(TickHandler.java:228)
[20:09:57] [Server thread/WARN] []: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_428_TickHandler_onTick_TickEvent.invoke(.dynamic)
[20:09:57] [Server thread/WARN] []: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[20:09:57] [Server thread/WARN] []: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:187)
[20:09:57] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:832)
[20:09:57] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:640)
[20:09:57] [Server thread/WARN] []: 	at java.lang.Thread.run(Unknown Source)
[20:09:57] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent@19d7155a:
net.minecraft.util.ReportedException: Ticking GridNode
	at appeng.me.cache.TickManagerCache.onUpdateTick(TickManagerCache.java:135) ~[TickManagerCache.class:?]
	at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:43) ~[GridCacheWrapper.class:?]
	at appeng.me.Grid.update(Grid.java:280) ~[Grid.class:?]
	at appeng.hooks.TickHandler.onTick(TickHandler.java:228) ~[TickHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_428_TickHandler_onTick_TickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:git-1.12.2-eb43344]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:187) [EventBus.class:git-1.12.2-eb43344]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:263) [FMLCommonHandler.class:git-1.12.2-eb43344]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:832) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:640) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
	at appeng.me.cache.helpers.TickTracker.compareTo(TickTracker.java:81) ~[TickTracker.class:?]
	at appeng.me.cache.helpers.TickTracker.compareTo(TickTracker.java:34) ~[TickTracker.class:?]
	at java.util.PriorityQueue.siftDownComparable(Unknown Source) ~[?:1.8.0_181]
	at java.util.PriorityQueue.siftDown(Unknown Source) ~[?:1.8.0_181]
	at java.util.PriorityQueue.poll(Unknown Source) ~[?:1.8.0_181]
	at appeng.me.cache.TickManagerCache.onUpdateTick(TickManagerCache.java:93) ~[TickManagerCache.class:?]
	... 10 more
[20:09:57] [Server thread/ERROR] [FML]: Index: 7 Listeners:
[20:09:57] [Server thread/ERROR] [FML]: 0: NORMAL
[20:09:57] [Server thread/ERROR] [FML]: 1: ASM: class blusunrize.immersiveengineering.common.blocks.BlockIETileProvider onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[20:09:57] [Server thread/ERROR] [FML]: 2: ASM: net.minecraftforge.common.ForgeInternalHandler@5420f0ae onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[20:09:57] [Server thread/ERROR] [FML]: 3: ASM: class buildcraft.lib.BCLibEventDist serverTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[20:09:57] [Server thread/ERROR] [FML]: 4: ASM: ic2.core.TickHandler@7502d1c6 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[20:09:57] [Server thread/ERROR] [FML]: 5: ASM: cofh.thermaldynamics.util.TickHandler@54ca7073 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[20:09:57] [Server thread/ERROR] [FML]: 6: ASM: Block{minecraft:air} tickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[20:09:57] [Server thread/ERROR] [FML]: 7: ASM: appeng.hooks.TickHandler@258b323b onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[20:09:57] [Server thread/ERROR] [FML]: 8: LOWEST
[20:09:57] [Server thread/ERROR] [FML]: 9: ASM: class codechicken.lib.internal.CCLLog onTickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[20:09:57] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking GridNode
	at appeng.me.cache.TickManagerCache.onUpdateTick(TickManagerCache.java:135) ~[TickManagerCache.class:?]
	at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:43) ~[GridCacheWrapper.class:?]
	at appeng.me.Grid.update(Grid.java:280) ~[Grid.class:?]
	at appeng.hooks.TickHandler.onTick(TickHandler.java:228) ~[TickHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_428_TickHandler_onTick_TickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:git-1.12.2-eb43344]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:187) ~[EventBus.class:git-1.12.2-eb43344]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:263) ~[FMLCommonHandler.class:git-1.12.2-eb43344]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:832) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:640) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
	at appeng.me.cache.helpers.TickTracker.compareTo(TickTracker.java:81) ~[TickTracker.class:?]
	at appeng.me.cache.helpers.TickTracker.compareTo(TickTracker.java:34) ~[TickTracker.class:?]
	at java.util.PriorityQueue.siftDownComparable(Unknown Source) ~[?:1.8.0_181]
	at java.util.PriorityQueue.siftDown(Unknown Source) ~[?:1.8.0_181]
	at java.util.PriorityQueue.poll(Unknown Source) ~[?:1.8.0_181]
	at appeng.me.cache.TickManagerCache.onUpdateTick(TickManagerCache.java:93) ~[TickManagerCache.class:?]
	... 10 more
[20:09:57] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: E:\MIAOCHAT\.\crash-reports\crash-2019-03-04_20.09.57-server.txt
[20:09:57] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server

**Comment by yueh** [comment]
We need complete log.

**Comment by Laotouy** [comment]
https://paste.ubuntu.com/p/q9FTx2TQCq/

**Comment by Laotouy** [comment]
- https://paste.ubuntu.com/p/KVS5CJBbrd/

**Comment by yueh** [comment]
We do not support anything like Sponge or Bukkit officially. Only a standard forge environment.

Should you be able to reproduce it without it, please update the issue accordingly and we will reopen it.
