### ISSUE TITLE
Hwyla error registering wrapped plugin form appliedenergistics2

### ISSUE THREAD

**Issue by XakepSDK** [AppliedEnergistics/Applied-Energistics-2#3954]
- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-6
- Forge Version: forge-1.12.2-14.23.5.2815-universal
- Hwyla version: Hwyla-1.8.26-B41_1.12.2
I'm getting this error while starting forge server. Is this ok?
```
[Waila]: Error registering wrapped plugin from appliedenergistics2 at appeng.integration.modules.waila.WailaModule.register
```

**Comment by yueh** [comment]
No idea. If they suppress the actual error, there is no way to guess it. So at least it needs the complete log.

**Comment by XakepSDK** [comment]
I recompiled hwyla. That's all i got.
```
[14:28:19] [Server thread/ERROR] [Waila]: Error registering wrapped plugin from appliedenergistics2 at appeng.integration.modules.waila.WailaModule.register                                                                                                                   
java.lang.reflect.InvocationTargetException: null                                                                                                                                                                                                                              
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]                                                                                                                                                                                          
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]                                                                                                                                                                        
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]                                                                                                                                                                
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]                                                                                                                                                                                                     
        at mcp.mobius.waila.utils.PluginUtil.lambda$gatherIMCPlugins$0(PluginUtil.java:49) ~[PluginUtil.class:?]                                                                                                                                                               
        at mcp.mobius.waila.proxy.ProxyCommon.loadComplete(ProxyCommon.java:72) [ProxyCommon.class:?]                                                                                                                                                                          
        at mcp.mobius.waila.Waila.loadComplete(Waila.java:68) [Waila.class:?]                                                                                                                                                                                                  
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]                                                                                                                                                                                          
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]                                                                                                                                                                        
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]                                                                                                                                                                
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]                                                                                                                                                                                                     
        at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624) [FMLModContainer.class:?]                                                                                                                                               
        at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]                                                                                                                                                                                                 
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]                                                                                                                                                                
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]                                                                                                                                                                                                     
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]                                                                                                                                                    
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]                                                                                                                            
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]                                                                                                                                                                     
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]                                                                                                                                      
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]                                                                                                                                                             
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]                                                                                                                                       
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]                                                                                                                                                                         
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) [LoadController.class:?]                                                                                                                                              
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) [LoadController.class:?]                                                                                                                                                
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]                                                                                                                                                                                          
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]                                                                                                                                                                        
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]                                                                                                                                                                
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]                                                                                                                                                                                                     
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]                                                                                                                                                    
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]                                                                                                                            
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]                                                                                                                                                                     
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]                                                                                                                                      
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]                                                                                                                                                             
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]                                                                                                                                       
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]                                                                                                                                                                         
        at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:553) [LoadController.class:?]                                                                                                                                               
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) [LoadController.class:?]                                                                                                                                               
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:752) [Loader.class:?]                                                                                                                                                                               
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) [FMLServerHandler.class:?]                                                                                                                                            
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338) [FMLCommonHandler.class:?]                                                                                                                                                
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:219) [nz.class:?]                                                                                                                                                                          
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]                                                                                                                                                                        
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]                                                                                                                                                                                                                 
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag                                                                                                                                                                                              
        at appeng.integration.modules.waila.TileWailaDataProvider.<init>(TileWailaDataProvider.java:62) ~[TileWailaDataProvider.class:?]                                                                                                                                       
        at appeng.integration.modules.waila.WailaModule.register(WailaModule.java:52) ~[WailaModule.class:?]                                                                                                                                                                   
        ... 43 more                                                                                                                                                                                                                                                            
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.util.ITooltipFlag                                                                                                                                                                                            
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]                                                                                                                                                     
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]                                                                                                                                                                                                
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]                                                                                                                                                                                                
        at appeng.integration.modules.waila.TileWailaDataProvider.<init>(TileWailaDataProvider.java:62) ~[TileWailaDataProvider.class:?]                                                                                                                                       
        at appeng.integration.modules.waila.WailaModule.register(WailaModule.java:52) ~[WailaModule.class:?]                                                                                                                                                                   
        ... 43 more
Caused by: java.lang.NullPointerException

```

**Comment by XakepSDK** [comment]
Is this fixed?
