### ISSUE TITLE
Server crashes when loading chunks with crafting cpu

### ISSUE THREAD

**Issue by scrouthtv** [AppliedEnergistics/Applied-Energistics-2#4019]
_Obligatory stuff first although I can't provide much information for now as it's not my server._

I'm not sure yet on how to reproduce this bug, but it would help if anyone could tell me on how to find out what recipe the crafting cpu was working on (_how to enable verbose logging?_).

- Minecraft Version: 1.12.2
- AE2 Version: 	appliedenergistics2-rv6-stable-6.jar
- Forge Version: forge-14.23.5.2815

_Some more stuff_

I think we are having the same bug. Running ATM v 1.2.0 (appliedenergistics2-rv6-stable-6.jar) with I guess all AE addons. As soon as someone comes into one of our chunks, the server crashes:

```
java.lang.Error: ServerHangWatchdog detected that a single server tick took 90.00 seconds (should be max 0.05)
at net.minecraft.item.crafting.ShapelessRecipes.func_77569_a(ShapelessRecipes.java:67)
at net.minecraft.item.crafting.CraftingManager.func_82787_a(CraftingManager.java:199)
at appeng.helpers.PatternHelper.isValidItemForSlot(PatternHelper.java:273)
at appeng.me.cluster.implementations.CraftingCPUCluster.executeCrafting(CraftingCPUCluster.java:713)
at appeng.me.cluster.implementations.CraftingCPUCluster.updateCraftingLogic(CraftingCPUCluster.java:617)
at appeng.me.cache.CraftingGridCache.onUpdateTick(CraftingGridCache.java:152)
at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:43)
at appeng.me.Grid.update(Grid.java:280)
at appeng.hooks.TickHandler.onTick(TickHandler.java:228)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2356_TickHandler_onTick_TickEvent.invoke(.dynamic)
```
etc. (see https://pastebin.com/EZPibxyT)
I can't really remember what we last requested in autocrafting, might have been an energy cell from Mekanism / Mekanica but don't quote me on this one..

Has anyone a fix yet? My next attempt would be to erase / replace all Crafting Storages via the command line but I don't want to do that yet..

I will append a full server log later as I asked them to send me one, please bear with me :)

**Comment by yueh** [comment]
That is simply due to how poorly forge handles recipes especially combined with some mods having particularly slow handlers.

The best (possible) option would be to profile the server itself while loading and identify which handler takes so much time and then deal with it somehow. Otherwise the only other solution is to hope forge will at some point improve their recipe system.
