### ISSUE TITLE
All terminals empty - network still up

### ISSUE THREAD

**Issue by robertperbes** [AppliedEnergistics/Applied-Energistics-2#4380]
### Description
All AE2 terminals - crafting, pattern, wireless, etc - go blank after some time.  First time was after overloading channels, now it seems import/exporting items can cause it.  A server reboot fixes the issue for a time.

Terminals can still craft, but show no inventory.  You can even shift-click JEI recipes in and crafting grid gets populated with items in AE storage.  If you pull a disk from a drive bay and re-insert, the inventory comes up for a moment, and items can be extracted until crafting terminal is re-opened.  Auto-crafting recipes will also show up for a moment as well, but the craft button is always greyed out.

### Environment
PO3 Server
4 ME controllers
250+ channels
Quantum rings
All AE2 chunks loaded with ChickenChunks ChunkLoaders or SpotLoaders

### What I've tried so far:
Removed all storage buses
Removed all Extra Cells disks
Added Dense Cells to all legs of network (22MRF Stored, 3.5kRF/t usage from Network Tool)
Removed all Tinker's Construct weapons and parts from storage
Ensured no loops/redundant connections (using anchors)
Tested using OpenComputers to component.me_interface.getItemsInNetwork() returns n=0
Tested storage bus/ME Interface loop 
Read through #1189 as it seemed like a similar issue - no help there

- Minecraft Version: 
- AE2 Version: 1.12.2
- Forge Version: 14.23.5.2847
- Modpack - Project Ozone 3: 3.3.57

**Comment by Wassaaa** [comment]
exactly the same issue here.

It started happening for us while we were pumping millions of items from our Yabba item barrel system to the main AE system with 32 drives full of the biggest storage cells. we are hoping maybe it gets better after all the items are transfered, but it will take some time.

**Comment by Pingger** [comment]
OK, my guess, not enough power.
Please try one of the following:
- Add a Creative EnergyCell to the ME System.
- Add a Dense EnergyCell
- Add a few 'normal' EnergyCells to the ME System

Reason:
The ME System can only take so much energy as it has internal Storage. So a ME System without any energy cells is limit to a few hundred RF/tick (if I recall correctly). Adding EnergyCells increases this limitation by capacity of the added energycells.  
When a ME System is barely out of energy the System starts and stops every other tick causing the Terminals to visually be online, but not have access to the Drives, because the interaction with the Drives (adding and removing items) costs probably the most energy. (A Spatial Storage, a Quantum Bridge or Wireless Transmitter can exceed that though).

**Comment by Wassaaa** [comment]
As soon as we placed the creative cell to the system, the terminals went all invisible. everything is as if its working, toggling a storage cell out of the drive and back in, makes the items visible for a moment. Also if I keep the terminal open, I can take items out, but ANY item that I take out, disappears from the terminal. (for example we have 40mil iron, I took out 1 stack and the system shows no more iron.) And as soon as I close the terminal, opening it again results in no items shown.

AFTER that creative cell addition, we restarted the server and it has been staying fine for a few hours now. But we will see in the future if it stays fine.

Also network tool shows huge numbers of energy in the system, 1.84 PRF to be exact. So if it goes down, it cant be an energy problem any more I suspect.

**Comment by Pingger** [comment]
It CAN still be an energy issue, if the chunk containing the energy cell is unloaded. So DO chunkload the controller and energy cells.

**Comment by XerockXMG** [comment]
I was having this exact same issue on my server. I saw the following in the console just me and other people on the server started seeing issues with their ME systems as well

`[16:28:12] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ClassCastException: appeng.util.item.AEItemStack cannot be cast to appeng.api.storage.data.IAEFluidStack
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_181]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.ClassCastException: appeng.util.item.AEItemStack cannot be cast to appeng.api.storage.data.IAEFluidStack
	at appeng.fluids.util.FluidList.findPrecise(FluidList.java:33) ~[FluidList.class:?]
	at appeng.me.storage.BasicCellInventory.extractItems(BasicCellInventory.java:221) ~[BasicCellInventory.class:?]
	at appeng.me.storage.MEPassThrough.extractItems(MEPassThrough.java:63) ~[MEPassThrough.class:?]
	at appeng.me.storage.MEInventoryHandler.extractItems(MEInventoryHandler.java:117) ~[MEInventoryHandler.class:?]
	at appeng.me.storage.MEInventoryHandler.extractItems(MEInventoryHandler.java:117) ~[MEInventoryHandler.class:?]
	at appeng.me.storage.DriveWatcher.extractItems(DriveWatcher.java:77) ~[DriveWatcher.class:?]
	at appeng.me.storage.NetworkInventoryHandler.injectItems(NetworkInventoryHandler.java:99) ~[NetworkInventoryHandler.class:?]
	at appeng.me.cache.NetworkMonitor.injectItems(NetworkMonitor.java:157) ~[NetworkMonitor.class:?]
	at p455w0rd.ae2wtlib.helpers.WTGuiObjectImpl.injectItems(WTGuiObjectImpl.java:203) ~[WTGuiObjectImpl.class:?]
	at appeng.util.Platform.poweredInsert(Platform.java:1229) ~[Platform.class:?]
	at appeng.util.Platform.poweredInsert(Platform.java:1218) ~[Platform.class:?]
	at p455w0rd.wct.container.ContainerWCT.shiftStoreItem(ContainerWCT.java:1143) ~[ContainerWCT.class:?]
	at p455w0rd.wct.container.ContainerWCT.func_82846_b(ContainerWCT.java:989) ~[ContainerWCT.class:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:246) ~[afr.class:?]
	at p455w0rd.wct.container.ContainerWCT.func_184996_a(ContainerWCT.java:1154) ~[ContainerWCT.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1162) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]`

We are playing Project Ozone 3 currently

**Comment by Wassaaa** [comment]
it seems something about fluid stacks? for us it also started happening after we tried to put fluids into the system, but we have removed the fluids since then and the issue is still happening

did trying fluids fuck something up for good in our map or something?

**Comment by TheInfamousAlk** [comment]
Hi, person from XerockXMG's server. The only fluid stuff anyone has going on is Xerock exporting gelid cryotheum. After a server restart, it works until Xerock's chunks are loaded. Then *everyone's* ME systems stop working across the whole server in the same fashion. Same errors as posted in the log above. This is after Xerock removed his fluid storage drives, so those are not in play when the errors start up again after a restart.

**Comment by yueh** [comment]
@XerockXMG that is the wireless crafting terminal mod trying to insert an item into some fluid storage.
That probably causes a bunch of different sideeffects. Like terminals being broken. But nothing we can fix on our side.

As the original post doesn't contain much useful information, yet is the same modpack and mostly identical description, I simply assume it is the same issue for now.

**Comment by forzakenus** [comment]
Hi, 
I'm playing with Wassaa in our private server the Project Ozone 3 Kappa mode. And actually managed to replicate the problem.
First we crafted the AE2 Wireless Terminals with the extra modules installed (Pattern Terminal, Fluid Terminal, Crafting Terminal and Interface terminal). So when I open the fluid tab in the terminal and close it in fluid terminal, reopen the terminal(with keybind) then it opens the regular crafting grid and then when I craft the whole system gets bugged and needs a server restart.

Did it 2 times in a row. Regular fluid terminal didn't trigger it. So is it Wireless terminal related?
For me it seemed when i closed the terminal in fluid mode  and then open the terminal again the terminal thought it was still in fluid mode even though the UI was crafting terminals.

Hopefully it was useful for someone.

**Comment by XerockXMG** [comment]
> Hi,
> I'm playing with Wassaa in our private server the Project Ozone 3 Kappa mode. And actually managed to replicate the problem.
> First we crafted the AE2 Wireless Terminals with the extra modules installed (Pattern Terminal, Fluid Terminal, Crafting Terminal and Interface terminal). So when I open the fluid tab in the terminal and close it in fluid terminal, reopen the terminal(with keybind) then it opens the regular crafting grid and then when I craft the whole system gets bugged and needs a server restart.
> 
> Did it 2 times in a row. Regular fluid terminal didn't trigger it. So is it Wireless terminal related?
> For me it seemed when i closed the terminal in fluid mode and then open the terminal again the terminal thought it was still in fluid mode even though the UI was crafting terminals.
> 
> Hopefully it was useful for someone.

That actually makes perfect sense.

I can only assume that opening the terminal with the keybind isn't setting the terminal state properly.

I know of you use the item in your hand, it will remember what terminal you were in last when you use it.

100% a bug in the wireless terminal code.

Thanks for catching this!

**Comment by Pingger** [comment]
Then you should probably report this issue to the developer of the wireless crafting terminal: https://github.com/p455w0rd/WirelessCraftingTerminal/issues

**Comment by mindforger** [comment]
i wouldn't use such words @Pingger it is a bit harsh 
we all only cooks with water and extending/modifying an UI in AE2 is actually not THAT simple

could also be an API issue :P let's see what happens on p455word's side

please link the issue on the other issue on their tracker so it gets linked :)

**Comment by Pingger** [comment]
> 
> 
> i wouldn't use such words @Pingger it is a bit harsh
> we all only cooks with water and extending/modifying an UI in AE2 is actually not THAT simple

why is it harsh? A mod (A) causing another mod (B) to fail to do its job properly because mod A accesses mod B in an unintended/wrong way. And not properly handling the resulting error, possibly causing save corruption, but at least causing runtime corruption?! I don't see why it should not be called "fails catastrophically".
But also the "wireless fluid terminal" is also marked as **beta**, so one should expect such a thing.
