### ISSUE TITLE
Applied Energistics 2 uses a dimension id that is used by Any Dimensions mod, causing Minecraft and my server to crash.

### ISSUE THREAD

**Issue by RealEthanPlayzDev** [AppliedEnergistics/Applied-Energistics-2#4397]
When I installed Any Dimensions mod, starting Minecraft after step 5 will crash Minecraft due to dimension ID conflict, I have also changed the dimension ID in the config to 255 and 256 in both client and server but Minecraft with the server crashed because that is outside the limits (I thought the limits are at 256???)

Crash log: https://pastebin.com/tnd4G0Di
Full server crash log (Warning: it's very long): https://pastebin.com/CNQeKzyW

Using version rv6-stable7
Any dimensions: https://www.curseforge.com/minecraft/mc-mods/any-dimension-mod

**Comment by mindforger** [comment]
IDs are counted from 0 , so 0 to 255 = 265 IDs or 0x00 to 0xff in hex

what is the point of your question?
Did you try already ALL IDs from 0 to 255?
Can't you except/blacklist one single ID in the AnyDimensions Mod?

**Comment by Ommina** [comment]
Allegedly AnyDimensions uses 4 through 231 and offers no config.

mcreator too, so don't hold your breath.

**Comment by RealEthanPlayzDev** [comment]
Oh, I'll try now then.

**Comment by RealEthanPlayzDev** [comment]
Umm?
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  Techguns Core (techguns-1.12.2-2.0.2.0_pre3.2.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 6/1/20 2:20 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Energistics 2 (appliedenergistics2)
Caused by: java.lang.IllegalArgumentException: Invalid dimension id 233
	at net.minecraft.world.DimensionType.func_186069_a(DimensionType.java:77)
	at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:131)
	at appeng.core.Registration.registerSpatialDimension(Registration.java:201)
	at appeng.core.Registration.postInit(Registration.java:352)
	at appeng.core.AppEng.postInit(AppEng.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 222877920 bytes (212 MB) / 1476395008 bytes (1408 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 28 mods loaded, 28 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version           | Source                                             | Signature                                |
	|:----- |:------------------- |:----------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJ | minecraft           | 1.12.2            | minecraft.jar                                      | None                                     |
	| LCHIJ | mcp                 | 9.42              | minecraft.jar                                      | None                                     |
	| LCHIJ | FML                 | 8.0.99.99         | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | forge               | 14.23.5.2854      | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | opencomputers|core  | 1.7.5.192         | minecraft.jar                                      | None                                     |
	| LCHIJ | techguns_core       | 1.12.2-1.0        | minecraft.jar                                      | None                                     |
	| LCHIJ | any_dimension_mod   | 1.3.4             | any_dimension_mod_v1.3.4.jar                       | None                                     |
	| LCHIE | appliedenergistics2 | rv6-stable-7      | appliedenergistics2-rv6-stable-7.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHI  | betterbuilderswands | 0.13.2            | BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar  | None                                     |
	| LCHI  | codechickenlib      | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHI  | redstoneflux        | 2.1.1             | RedstoneFlux-1.12-2.1.1.1-universal.jar            | None                                     |
	| LCHI  | brandonscore        | 2.4.18            | BrandonsCore-1.12.2-2.4.18.210-universal.jar       | None                                     |
	| LCHI  | cctweaked           | 1.88.0            | cc-tweaked-1.12.2-1.88.0.jar                       | None                                     |
	| LCHI  | computercraft       | 1.88.0            | cc-tweaked-1.12.2-1.88.0.jar                       | None                                     |
	| LCHI  | discordrp           | 1.2.19            | DiscordRP-1.12.2-1.2.19.jar                        | 5b6b19557df723bd85d474a32d64e4e191a2b42a |
	| LCHI  | draconicevolution   | 2.3.25            | Draconic-Evolution-1.12.2-2.3.25.351-universal.jar | None                                     |
	| LCHI  | ichunutil           | 7.2.2             | iChunUtil-1.12.2-7.2.2.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHI  | jei                 | 4.15.0.293        | jei_1.12.2-4.15.0.293.jar                          | None                                     |
	| LCHI  | mantle              | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                           | None                                     |
	| LCHI  | opencomputers       | 1.7.5.192         | OpenComputers-MC1.12.2-1.7.5.192.jar               | None                                     |
	| LCHI  | portalgun           | 7.1.0             | PortalGun-1.12.2-7.1.0.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHI  | projecte            | 1.12.2-PE1.4.1    | ProjectE-1.12.2-PE1.4.1.jar                        | None                                     |
	| LCHI  | subcommonlib        | 1.2.0.1           | subcommonlib-sublib-1.12.2-1.2.0.4.jar             | None                                     |
	| LCHI  | tconstruct          | 1.12.2-2.13.0.183 | TConstruct-1.12.2-2.13.0.183.jar                   | None                                     |
	| LCHI  | techguns            | 2.0.2.0           | techguns-1.12.2-2.0.2.0_pre3.2.jar                 | None                                     |
	| LCHI  | telepads            | $version          | telepads-1.12.2-1.1.0.7.jar                        | None                                     |
	| LCHI  | veinminer           | 0.38.2            | VeinMiner-1.12-0.38.2.647+b31535a.jar              | None                                     |
	| LCHI  | veinminermodsupport | 0.38.2            | VeinMiner-1.12-0.38.2.647+b31535a.jar              | None                                     |

	Loaded coremods (and transformers): 
TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  li.cil.oc.common.asm.ClassTransformer
Techguns Core (techguns-1.12.2-2.0.2.0_pre3.2.jar)
  techguns.core.TechgunsASMTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13559 Compatibility Profile Context 26.20.12028.2' Renderer: 'AMD Radeon(TM) R7 Graphics'
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 26
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.13559 Compatibility Profile Context 26.20.12028.2
	OpenGlRenderer: AMD Radeon(TM) R7 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by RealEthanPlayzDev** [comment]
spatialio {
    D:spatialPowerExponent=1.35
    D:spatialPowerMultiplier=1250.0
    I:storageDimensionID=232
    I:storageProviderID=233
}

**Comment by Tahakk** [comment]
I mean can you blame AE if other mods are blocking dimensions IDs? Start removing mods to see which one causes it and report it to their repo. If there is a mod that needs that much ID's they should provide available ID list

**Comment by RealEthanPlayzDev** [comment]
I don't think any other mods have dimension (Draconic has a dimension but it's at the end)
Except AE2 and that mod

**Comment by RealEthanPlayzDev** [comment]
Why is it saying "Invalid dimension id: <dimension id>" just like that?
Is the dimension configuration on AE a number or a string?

**Comment by RealEthanPlayzDev** [comment]
It's not talking about I:storageDimensionID=232 as well.

**Comment by RealEthanPlayzDev** [comment]
Removing Any Dimensions just fixes it.
I guess I have to contact the other mod owner, closing this issue.
