### ISSUE TITLE
Crashing while loading 1.15.2 server

### ISSUE THREAD

**Issue by Moodss0151** [AppliedEnergistics/Applied-Energistics-2#4455]
Loading up a server with forge 1.15.2 always causes this:

[08Jul2020 01:35:59.710] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Applied Energistics 2 (appliedenergistics2) encountered an error during the common_setup event phase
§7net.minecraft.item.Item.func_200296_o()Lnet/minecraft/util/text/ITextComponent;
]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:218) ~[?:?]
	at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:156) ~[?:?]
	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:46) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

**Comment by Ommina** [comment]
#4453 and #4454
