### ISSUE TITLE
Error at startup phase,Prompt in the common_setup stage

### ISSUE THREAD

**Issue by imorefun** [AppliedEnergistics/Applied-Energistics-2#4456]
**Describe the bug**

Error at startup phase

Prompt in the common_setup stage
```
net.minecraftforge.fml.DistExecutor.unsafeRunForDist(Ljava/util/function/Supplier;Ljava/util/function/Supplier;)Ljava/lang/Object;
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$2127/1772262616@3742b1f7
java.lang.NoSuchMethodError: net.minecraftforge.fml.DistExecutor.unsafeRunForDist(Ljava/util/function/Supplier;Ljava/util/function/Supplier;)Ljava/lang/Object;
	at appeng.core.sync.network.NetworkHandler.<init>(NetworkHandler.java:55)
	at appeng.core.sync.network.NetworkHandler.init(NetworkHandler.java:60)
	at appeng.core.AppEng.registerNetworkHandler(AppEng.java:281)
	at appeng.core.AppEng.commonSetup(AppEng.java:158)
	at appeng.core.AppEng$$Lambda$2832/1559301142.accept(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2127/1772262616.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2237/1161255903.accept(Unknown Source)
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65)
	at java.util.function.Consumer$$Lambda$2226/1731593711.accept(Unknown Source)
	at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65)
	at java.util.function.Consumer$$Lambda$2226/1731593711.accept(Unknown Source)
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112)
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:134)
	at net.minecraftforge.fml.ModList$$Lambda$2284/644432670.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
**To Reproduce**

You can restart the error in the same environment

**Environment**

- Environment: 
mc version ：1.15.2
forge version：1.15.2-31.0.0

**Comment by Ommina** [comment]
Update Forge.  By a lot.  At least 31.2.5.
