### ISSUE TITLE
Server Crashed with ae2 rv6 1.12

### ISSUE THREAD

**Issue by OnkelStinson** [AppliedEnergistics/Applied-Energistics-2#4518]
Server Crashed with ae2 rv6 1.12

**Describe the issue**

i added mods to my server, like ae2 rv6 1.12, and when i start the server, it crashes.
i removed ae2 and started my server with no problem.
i removed every mod and only add ae2 and it chrashed again.

**Environment**

---- Minecraft Crash Report ----

// You're mean.

Time: 29.07.20 13:23
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Energistics 2 (appliedenergistics2)
Caused by: java.lang.RuntimeException: Failed to check session lock, aborting
	at net.minecraft.world.storage.SaveHandler.func_75766_h(SaveHandler.java:76)
	at net.minecraft.world.storage.SaveHandler.<init>(SaveHandler.java:54)
	at net.minecraft.world.chunk.storage.AnvilSaveHandler.<init>(AnvilSaveHandler.java:18)
	at net.minecraft.world.chunk.storage.AnvilSaveConverter.func_75804_a(SourceFile:84)
	at appeng.core.worlddata.WorldData.onServerAboutToStart(WorldData.java:130)
	at appeng.core.AppEng.serverAboutToStart(AppEng.java:259)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.serverAboutToStart(Loader.java:859)
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:292)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:268)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_261, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6967922568 bytes (6645 MB) / 8537636864 bytes (8142 MB) up to 12832604160 bytes (12238 MB)
	JVM Flags: 7 total; -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:ParallelGCThreads=6 -XX:+CMSIncrementalPacing -XX:+AggressiveOpts -Xms8G -Xmx12G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID                                | Version           | Source                                         | Signature                                |
	|:------- |:--------------------------------- |:----------------- |:---------------------------------------------- |:---------------------------------------- |
	| LCHIJA  | minecraft                         | 1.12.2            | minecraft.jar                                  | None                                     |
	| LCHIJA  | mcp                               | 9.42              | minecraft.jar                                  | None                                     |
	| LCHIJA  | FML                               | 8.0.99.99         | forge-1.12.2-14.23.5.2854-universal.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA  | forge                             | 14.23.5.2854      | forge-1.12.2-14.23.5.2854-universal.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJAE | appliedenergistics2               | rv6-stable-7      | Applied-Energistics-2-Mod-1.12.2.jar           | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |

	List of loaded APIs: 
		* appliedenergistics2|API (rv6) from Applied-Energistics-2-Mod-1.12.2.jar

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:OFF, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Profiler Position: N/A (disabled)
	Player Count: 0 / 4; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

- Environment:

**Comment by mindforger** [comment]
Not sure if related, but https://bugs.mojang.com/browse/MC-10167

**Comment by OnkelStinson** [comment]
lol, nice.
it was simple, to long world name.
Thx ^^
