### ISSUE TITLE
Applied Energetics 2 1.16.1 8.0.0 Crash

### ISSUE THREAD

**Issue by weaponm249entity** [AppliedEnergistics/Applied-Energistics-2#4571]
Well i wanted to create a personal modpack so that i can make videos of it. Well it suddenly started to crash. I started to troubleshoot the crashlog with help of the Minecraft Forum and out of all mods it seems that AE 2 is creating the crash. So i wanted to share this crash in order to improve this mod.

Minecraft Suddenly crashes while loading and gives a crashlog.

Add These mods to your mod folder install the lastest forge and you can reproduce it. (BTW all of the mods are latest version and 1.16.1)
Mods:
AutoRegLib
curios-FORGE-1.16.1-3.0.0.2
jei
Mekanism-1.16.1-10.0.8.431 + All other Mekanism addons
(mekanism addons)
Mekanism Additions
Mekanism Generators
MekanismTools
-------------------------
More Mods
Natures Compass
Patchouli
Quark
Storage Drawers
Titanium
Industrial Foregoing
Iron shulker boxes
AppleSkin
Botania
CookingForBlockheads
CTM-MC1.16.1-1.1.0.1
FastLeafDecay
McCrayfish's Furniture Mod
Iron Chest
Iron Jetpacks
Cucumber

Aaand Finally

Applied Energetics 2 8.0.0

I wanted minecraft to start and start tinkering with the configs but instead it gave a crash

here's the crashlog

---- Minecraft Crash Report ----
// Don't do that.
 
Time: 08.08.2020 10:49
Description: Rendering overlay
 
net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: appliedenergistics2:part/cable/core/glass/whıte
        at net.minecraft.util.ResourceLocation.<init>(SourceFile:41) ~[?:?] {re:classloading}
        at net.minecraft.util.ResourceLocation.<init>(SourceFile:50) ~[?:?] {re:classloading}
        at appeng.client.render.cablebus.CableCoreType.getTexture(CableCoreType.java:77) ~[?:8.0.0-alpha.2] {re:classloading}
        at appeng.client.render.cablebus.CableBuilder.getTextures(CableBuilder.java:709) ~[?:8.0.0-alpha.2] {re:classloading}
        at appeng.client.render.cablebus.CableBusModel.getAdditionalTextures(CableBusModel.java:61) ~[?:8.0.0-alpha.2] {re:classloading}
        at appeng.client.render.BasicUnbakedModel.getTextures(BasicUnbakedModel.java:39) ~[?:8.0.0-alpha.2] {re:classloading}
        at net.minecraftforge.client.model.BlockModelConfiguration.getTextureDependencies(BlockModelConfiguration.java:151) ~[?:?] {re:classloading}
        at net.minecraft.client.renderer.model.BlockModel.func_225614_a_(BlockModel.java:157) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.client.renderer.model.ModelBakery.lambda$processLoading$9(ModelBakery.java:197) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[?:1.8.0_261] {}
        at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_261] {}
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_261] {}
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_261] {}
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_261] {}
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_261] {}
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_261] {}
        at net.minecraft.client.renderer.model.ModelBakery.processLoading(ModelBakery.java:198) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraftforge.client.model.ModelLoader.<init>(ModelLoader.java:72) ~[?:?] {re:classloading}
        at net.minecraft.client.renderer.model.ModelManager.func_212854_a_(ModelManager.java:57) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.client.renderer.model.ModelManager.func_212854_a_(ModelManager.java:20) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.client.resources.ReloadListener.func_215270_b(SourceFile:11) ~[?:?] {re:classloading,re:mixin}
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:1.8.0_261] {}
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[?:1.8.0_261] {}
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_261] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_261] {}
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_261] {}
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_261] {}
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- Head --
Thread: Render thread
Stacktrace:
        at net.minecraft.util.ResourceLocation.<init>(SourceFile:41)
        at net.minecraft.util.ResourceLocation.<init>(SourceFile:50)
        at appeng.client.render.cablebus.CableCoreType.getTexture(CableCoreType.java:77)
        at appeng.client.render.cablebus.CableBuilder.getTextures(CableBuilder.java:709)
        at appeng.client.render.cablebus.CableBusModel.getAdditionalTextures(CableBusModel.java:61)
        at appeng.client.render.BasicUnbakedModel.getTextures(BasicUnbakedModel.java:39)
        at net.minecraftforge.client.model.BlockModelConfiguration.getTextureDependencies(BlockModelConfiguration.java:151)
        at net.minecraft.client.renderer.model.BlockModel.func_225614_a_(BlockModel.java:157)
        at net.minecraft.client.renderer.model.ModelBakery.lambda$processLoading$9(ModelBakery.java:197)
        at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
        at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
 
-- Overlay render details --
Details:
        Overlay name: net.minecraft.client.gui.ResourceLoadProgressGui
Stacktrace:
        at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:473)
        at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:951)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:582)
        at net.minecraft.client.main.Main.main(Main.java:184)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
 
-- System Details --
Details:
        Minecraft Version: 1.16.1
        Minecraft Version ID: 1.16.1
        Operating System: Windows 10 (amd64) version 10.0
        Java Version: 1.8.0_261, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 3254193008 bytes (3103 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
        CPUs: 4
        JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:ConcGCThreads=1 -XX:ParallelGCThreads=4 -Xmx4096M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
        ModLauncher: 6.1.1+74+master.966c698
        ModLauncher launch target: fmlclient
        ModLauncher naming: srg
        ModLauncher services:
                /mixin-0.8.jar mixin PLUGINSERVICE
                /eventbus-3.0.3-service.jar eventbus PLUGINSERVICE
                /forge-1.16.1-32.0.106.jar object_holder_definalize PLUGINSERVICE
                /forge-1.16.1-32.0.106.jar runtime_enum_extender PLUGINSERVICE
                /accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE
                /forge-1.16.1-32.0.106.jar capability_inject_definalize PLUGINSERVICE
                /forge-1.16.1-32.0.106.jar runtimedistcleaner PLUGINSERVICE
                /mixin-0.8.jar mixin TRANSFORMATIONSERVICE
                /forge-1.16.1-32.0.106.jar fml TRANSFORMATIONSERVICE
        FML: 32.0
        Forge: net.minecraftforge:32.0.106
        FML Language Providers:
                javafml@32.0
                minecraft@1
        Mod List:
                forge-1.16.1-32.0.106-client.jar Minecraft {minecraft@1.16.1 ENQUEUE_IMC}
                industrial-foregoing-1.16.1-3.0.4-eeeb31e.jar Industrial Foregoing {industrialforegoing@3.0.4 ENQUEUE_IMC}
                useful_backpacks-1.16.1-1.11.1.71.jar Useful Backpacks {usefulbackpacks@1.11.1.71 ENQUEUE_IMC}
                titanium-1.16.1-3.0.4.jar Titanium {titanium@3.0.4 ENQUEUE_IMC}
                Cucumber-1.16.1-4.0.0.jar Cucumber Library {cucumber@4.0.0 ENQUEUE_IMC}
                mining-helmet-1.16.1-1.0.8.jar Mining Helmet {mining_helmet@1.0.8 ENQUEUE_IMC}
                MekanismAdditions-1.16.1-10.0.8.431.jar Mekanism: Additions {mekanismadditions@10.0.8 ENQUEUE_IMC}
                jei-1.16.1-7.0.1.9.jar Just Enough Items {jei@7.0.1.9 ENQUEUE_IMC}
                simplefarming-1.16.1-1.3.2.jar Simple Farming {simplefarming@1.16.1-1.3.2 ENQUEUE_IMC}
                Mekanism-1.16.1-10.0.8.431.jar Mekanism {mekanism@10.0.8 ENQUEUE_IMC}
                mcws-win-1.16.1-v1.0.2.jar Macaw's Windows {mcwwindows@1.0.2 ENQUEUE_IMC}
                curios-FORGE-1.16.1-3.0.0.2.jar Curios API {curios@FORGE-1.16.1-3.0.0.2 ENQUEUE_IMC}
                Botania-1.16-399.jar Botania {botania@1.16-399 ENQUEUE_IMC}
                Patchouli-1.16-39.jar Patchouli {patchouli@1.16-39 ENQUEUE_IMC}
                ForgeEndertech-1.16.1-7.0.0.0-build.0006.jar Forge Endertech {forgeendertech@7.0.0.0 ENQUEUE_IMC}
                AdFinders-1.16.1-5.0.0.0-build.0006.jar Advanced Finders {adfinders@5.0.0.0 ENQUEUE_IMC}
                AdLods-1.16.1-4.0.0.0-build.0007.jar Large Ore Deposits {adlods@4.0.0.0 ENQUEUE_IMC}
                gravestone-1.16.1-1.0.6.jar Gravestone Mod {gravestone@1.16.1-1.0.6 ENQUEUE_IMC}
                XaerosWorldMap_1.9.0_Forge_1.16.1.jar Xaero's World Map {xaeroworldmap@1.9.0 ENQUEUE_IMC}
                CTM-MC1.16.1-1.1.0.1.jar ConnectedTexturesMod {ctm@MC1.16.1-1.1.0.1 ENQUEUE_IMC}
                CookingForBlockheads_1.16.1-9.0.0.jar Cooking for Blockheads {cookingforblockheads@9.0.0 ENQUEUE_IMC}
                comforts-FORGE-1.16.1-3.0.jar Comforts {comforts@FORGE-1.16.1-3.0 ENQUEUE_IMC}
                AutoRegLib-1.6-43.jar AutoRegLib {autoreglib@1.6-43 ENQUEUE_IMC}
                appliedenergistics2-8.0.0-alpha.2.jar Applied Energistics 2 {appliedenergistics2@8.0.0-alpha.2 ENQUEUE_IMC}
                StorageDrawers-1.16.1-8.0.0.jar Storage Drawers {storagedrawers@1.16.1-8.0.0 ENQUEUE_IMC}
                NaturesCompass-1.16.1-1.8.5.jar Nature's Compass {naturescompass@1.16.1-1.8.5 ENQUEUE_IMC}
                decorative_blocks-7c.jar Decorative Blocks {decorative_blocks@7c ENQUEUE_IMC}
                obfuscate-0.4.3-1.16.1.jar Obfuscate {obfuscate@0.4.3 ENQUEUE_IMC}
                FarmingForBlockheads_1.16.1-7.0.1.jar Farming for Blockheads {farmingforblockheads@7.0.1 ENQUEUE_IMC}
                worldedit-forge-mc1.16.1-7.2.0-beta-02.jar WorldEdit {worldedit@7.2.0-beta-02+d10d7d6 ENQUEUE_IMC}
                u_team_core-1.16.1-3.1.2.167.jar U Team Core {uteamcore@3.1.2.167 ENQUEUE_IMC}
                PickleTweaks-1.16.1-5.0.0.jar Pickle Tweaks {pickletweaks@5.0.0 ENQUEUE_IMC}
                MekanismTools-1.16.1-10.0.8.431.jar Mekanism: Tools {mekanismtools@10.0.8 ENQUEUE_IMC}
                ironshulkerboxes-1.16.1-5.0.1.jar Iron Shulker Boxes {ironshulkerbox@1.16.1-5.0.1 ENQUEUE_IMC}
                furniture-7.0.0-pre18-1.16.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre18 ENQUEUE_IMC}
                MekanismGenerators-1.16.1-10.0.8.431.jar Mekanism: Generators {mekanismgenerators@10.0.8 ENQUEUE_IMC}
                forge-1.16.1-32.0.106-universal.jar Forge {forge@32.0.106 ENQUEUE_IMC}
                Quark-r2.2-260.jar Quark {quark@r2.2-260 ENQUEUE_IMC}
                AppleSkin-mc1.16.1-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 ENQUEUE_IMC}
                FastLeafDecay-v23.jar FastLeafDecay {fastleafdecay@v23 ENQUEUE_IMC}
                ironchest-1.16.1-11.0.1.jar Iron Chests {ironchest@1.16.1-11.0.1 ENQUEUE_IMC}
        Patchouli open book context: n/a
        Launched Version: 1.16.1-forge-32.0.106
        Backend library: LWJGL version 3.2.2 build 10
        Backend API: AMD Radeon(TM) R7 250 GL version 4.6.13587 Compatibility Profile Context 20.4.2 26.20.15029.27017, ATI Technologies Inc.
        GL Caps: Using framebuffer using OpenGL 3.0
        Using VBOs: Yes
        Is Modded: Definitely; Client brand changed to 'forge'
        Type: Client (map_client.txt)
        Resource Packs:
        Current Language: English (US)
        CPU: 4x Intel(R) Core(TM) i3-6098P CPU @ 3.60GHz

here's the paste bin for the crashlog

https://pastebin.pl/view/a647f8a0

**Comment by shartte** [comment]
@weaponm249entity: Do you by chance have a turkish locale? Or some other language that has two lowercase i?
