### ISSUE TITLE
Cables not displaying right!

### ISSUE THREAD

**Issue by mcbigboy** [AppliedEnergistics/Applied-Energistics-2#4592]
Just updated the mod and now the cables are not displaying right and controller is not show lit up.  I can open up the inventory.  All blocks where showing right but the molecular assembler before the updated to alpha 3 about two hours ago. 
![2020-08-13_16 34 20](https://user-images.githubusercontent.com/1017430/90194106-b546ed00-dd83-11ea-8a74-f08a9ae90abe.png)

**Comment by shartte** [comment]
Please provide the information requested in the issue template.

**Comment by mcbigboy** [comment]
there was not a crash report

**Comment by shartte** [comment]
Please press on "New Issue"/"Bug" again and read the text that it shows. That describes how to get a crash report without a crash.

**Comment by DoremySwee** [comment]
(Actually the situation occurs whenever mods changes, at least since rv3)

**Comment by Skishe** [comment]
I seem to also get this... probably shouldn't have updated to beta then proceeded to delete the alpha version.

The blocks affected for me are the crafting terminal, cables and the ME drive. They seem to be functional however, just that they don't have textures

**Comment by shartte** [comment]
Can you post a crashlog (using the approach that is outlined in the new issue placeholder text)?
I kinda need to see your environment + modlist to say anything because we're testing on 1.16.1 beta and don't have this problem.

**Comment by mcbigboy** [comment]
I deleted the mod sorry

**Comment by shartte** [comment]
@Skishe Can you provide a modlist using the "forced crash" approach listed in the issue template?
I'd like to know what may cause this.

**Comment by Occhioverde** [comment]
> Can you provide a modlist using the "forced crash"

Since I'm having the same issue after the update from 1.15.2 to 1.16.1, I'll paste below my forced crash report in the hope it'll be useful:
```
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 19/08/20, 18:07
Description: Manually triggered debug crash

java.lang.Throwable: null
	at net.minecraft.client.KeyboardListener.func_204870_b(KeyboardListener.java:669) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1504) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:928) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:582) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.1-forge-32.0.108.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.1-32.0.108.jar:32.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.KeyboardListener.func_204870_b(KeyboardListener.java:669)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Occhioverde'/190, l='ClientLevel', x=258.24, y=88.00, z=179.89]]
	Chunk stats: Client Chunk Cache: 441, 271
	Level dimension: minecraft:overworld
	Level spawn location: World: (192,87,176), Chunk: (at 0,5,0 in 12,11; contains blocks 192,0,176 to 207,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 6823667 game time, 12089 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:616)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:598)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Linux (amd64) version 5.7.9-1-MANJARO
	Java Version: 11.0.7, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 385917288 bytes (368 MB) / 1476395008 bytes (1408 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 6.1.1+74+master.966c698
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.1_HD_U_G2.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.1-32.0.108.jar fml TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.108
	FML Language Providers: 
		javafml@32.0
		minecraft@1
	Mod List: 
		forge-1.16.1-32.0.108-client.jar Minecraft {minecraft@1.16.1 DONE}
		elevatorid-1.16.1-1.7.3.jar Elevator Mod {elevatorid@1.16.1-1.7.3 DONE}
		Mekanism-1.16.1-10.0.9.432.jar Mekanism {mekanism@10.0.9 DONE}
		forge-1.16.1-32.0.108-universal.jar Forge {forge@32.0.108 DONE}
		MekanismTools-1.16.1-10.0.9.432.jar Mekanism: Tools {mekanismtools@10.0.9 DONE}
		cc-tweaked-1.16.1-1.90.3.jar CC: Tweaked {computercraft@1.90.3 DONE}
		MekanismGenerators-1.16.1-10.0.9.432.jar Mekanism: Generators {mekanismgenerators@10.0.9 DONE}
		appliedenergistics2-8.0.0-beta.1.jar Applied Energistics 2 {appliedenergistics2@8.0.0-beta.1 DONE}
		[1.16.1]+SecurityCraft+v1.8.19.1-beta2.jar SecurityCraft {securitycraft@v1.8.19.1-beta2 DONE}
		jei-1.16.1-7.0.1.10.jar Just Enough Items {jei@7.0.1.10 DONE}
	Launched Version: 1.16.1-forge-32.0.108
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD KABINI (DRM 2.50.0, 5.7.9-1-MANJARO, LLVM 10.0.0) GL version 4.5 (Compatibility Profile) Mesa 20.1.3, X.Org
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x AMD A8-7410 APU with AMD Radeon R5 Graphics
```
Let me know if you need further details.

**Comment by yueh** [comment]
That's most certainly caused by optifine.

**Comment by Occhioverde** [comment]
Yes, you're right. I've tried removing it and the textures rendered just fine.
I've even tried opening the world using OptiForge since I've read [here](https://github.com/sp614x/optifine/issues/4639#issuecomment-676944956) that it may help with this issue (that, by the way, happens also with other technical mods that include any sort of cables) but the game crashed while trying to tessellate a CableBusBlock (which I'm not sure if is part of AE2).

Here it is the crash report, even if I'm in doubt that this bug is caused by an incompatibility generated by AE2 rather than the Optifine itself:
```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 20/08/20, 21:17
Description: Tesselating block model

java.util.ConcurrentModificationException: null
	at java.util.HashMap.computeIfAbsent(HashMap.java:1134) ~[?:?] {}
	at appeng.client.render.cablebus.CableBusBakedModel.getQuads(CableBusBakedModel.java:95) ~[?:8.0.0-beta.1] {re:classloading}
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelFlat(BlockModelRenderer.java:203) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.renderModelFlat(ForgeBlockModelRenderer.java:69) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:101) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderModel(BlockRendererDispatcher.java:83) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_228940_a_(ChunkRenderDispatcher.java:894) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_225618_a_(ChunkRenderDispatcher.java:721) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$1(ChunkRenderDispatcher.java:180) ~[?:?] {re:classloading,xf:OptiFine:default}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1742) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
	at appeng.client.render.cablebus.CableBusBakedModel.getQuads(CableBusBakedModel.java:95)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelFlat(BlockModelRenderer.java:203)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.renderModelFlat(ForgeBlockModelRenderer.java:69)

-- Block model being tesselated --
Details:
	Block: CableBusBlock[cable_bus]
	Block location: World: (283,73,175), Chunk: (at 11,4,15 in 17,10; contains blocks 272,0,160 to 287,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Using AO: false
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:101)

-- Block being tesselated --
Details:
	Block: CableBusBlock[cable_bus]
	Block location: World: (283,73,175), Chunk: (at 11,4,15 in 17,10; contains blocks 272,0,160 to 287,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Occhioverde'/264, l='ClientLevel', x=277.30, y=70.00, z=174.34]]
	Chunk stats: Client Chunk Cache: 441, 268
	Level dimension: minecraft:overworld
	Level spawn location: World: (192,87,176), Chunk: (at 0,5,0 in 12,11; contains blocks 192,0,176 to 207,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 6830849 game time, 19271 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:616)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1973)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$3(ChunkRenderDispatcher.java:186)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1742)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Linux (amd64) version 5.7.9-1-MANJARO
	Java Version: 11.0.7, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 461416880 bytes (440 MB) / 1409286144 bytes (1344 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 6.1.1+74+master.966c698
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.1_HD_U_G2.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.1-32.0.108.jar fml TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.1-0.1.9.jar FakeOptiFine TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.1-0.1.9.jar optiforge TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.108
	FML Language Providers: 
		javafml@32.0
		minecraft@1
	Mod List: 
		forge-1.16.1-32.0.108-client.jar Minecraft {minecraft@1.16.1 DONE}
		OptiForge-MC1.16.1-0.1.9.jar OptiForge {optiforge@0.1.9 DONE}
		elevatorid-1.16.1-1.7.3.jar Elevator Mod {elevatorid@1.16.1-1.7.3 DONE}
		Mekanism-1.16.1-10.0.9.432.jar Mekanism {mekanism@10.0.9 DONE}
		forge-1.16.1-32.0.108-universal.jar Forge {forge@32.0.108 DONE}
		MekanismTools-1.16.1-10.0.9.432.jar Mekanism: Tools {mekanismtools@10.0.9 DONE}
		cc-tweaked-1.16.1-1.90.3.jar CC: Tweaked {computercraft@1.90.3 DONE}
		MekanismGenerators-1.16.1-10.0.9.432.jar Mekanism: Generators {mekanismgenerators@10.0.9 DONE}
		appliedenergistics2-8.0.0-beta.1.jar Applied Energistics 2 {appliedenergistics2@8.0.0-beta.1 DONE}
		[1.16.1]+SecurityCraft+v1.8.19.1-beta2.jar SecurityCraft {securitycraft@v1.8.19.1-beta2 DONE}
		jei-1.16.1-7.0.1.10.jar Just Enough Items {jei@7.0.1.10 DONE}
	Launched Version: 1.16.1-forge-32.0.108
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: ~~ERROR~~ IllegalStateException: Rendersystem called from wrong thread
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x AMD A8-7410 APU with AMD Radeon R5 Graphics
	OptiFine Version: OptiFine_1.16.1_HD_U_G2
	OptiFine Build: 20200802-005745
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5 (Compatibility Profile) Mesa 20.1.3
	OpenGlRenderer: AMD KABINI (DRM 2.50.0, 5.7.9-1-MANJARO, LLVM 10.0.0)
	OpenGlVendor: X.Org
	CpuCount: 4
```

**Comment by shartte** [comment]
Yeah sorry, Optifine will super-clash with our rendering hacks to get the cables to glow on Vanilla. Sorry :-|
