### ISSUE TITLE
"Automatically Crafting" crashes game

### ISSUE THREAD

**Issue by yuuuanquuu90** [AppliedEnergistics/Applied-Energistics-2#4639]
**Describe the bug**
Game crashes, if I use ME Crafting Terminal+ Molecular Assembler + Encoded Pattern
to automatically craft item.

**Hier ist the log:**
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 24.08.20 17:23
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at appeng.client.gui.implementations.CraftAmountScreen.drawBG(CraftAmountScreen.java:75)
	at appeng.client.gui.AEBaseScreen.method_2389(AEBaseScreen.java:253)
	at net.minecraft.class_465.method_25394(class_465.java:101)
	at appeng.client.gui.AEBaseScreen.method_25394(AEBaseScreen.java:144)
	at net.minecraft.class_757.method_3192(class_757.java:616)
	at net.minecraft.class_310.method_1523(class_310.java:1023)
	at net.minecraft.class_310.method_1514(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

**Environment**
appliedenergistics2-fabric-8.1.0-alpha.4.jar

**Comment by yuuuanquuu90** [comment]
It still works in appliedenergistics2-fabric-8.1.0-alpha.3.jar.

**Comment by yuuuanquuu90** [comment]
The error should be caused by an unknown conflict with another mod. After the mod is removed, it works again. 
I don't know if I can mention the name of the mod here. If you want to know, I can do that with pleasure. :)

**Comment by shartte** [comment]
Uh, why should not be able to? UNLESS ITS A CRACK

**Comment by yuuuanquuu90** [comment]
**InventorySorter-1.7.2-1.16.jar **

This mod should be the reason. After removing it, game works again.

**Comment by shartte** [comment]
I honestly don't know how they could make that happen.
Do you want to report it on their Github?

**Comment by Monster-Zer0** [comment]
same issue. no inventory sorter. different log.

this is on a server as well.

https://paste.gg/p/anonymous/541243a8a80247a095985f1c2afd6ad1

**Comment by shartte** [comment]
@Monster-Zer0 That is a VERY different problem.
According to the libblockattributes author, incompatibility with universalcomponents.
Will be fixed once they provide a fix.
