### ISSUE TITLE
Inserting Items into a pre-partitioned ME Chest crashes the server

### ISSUE THREAD

**Issue by shartte** [AppliedEnergistics/Applied-Energistics-2#4748]
```
Sep 18 01:06:19 fibercraft run.sh[11445]: [01:06:19] [Server thread/FATAL]: Error executing task on Server
Sep 18 01:06:19 fibercraft run.sh[11445]: java.lang.IllegalStateException: Unable to force-set the slot 0 to Empty!
Sep 18 01:06:19 fibercraft run.sh[11445]:         at alexiil.mc.lib.attributes.item.FixedItemInv.forceSetInvStack(FixedItemInv.java:72) ~[f859bddd-9a48-4ca3-abcf-11b288ed1953.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at appeng.tile.storage.ChestBlockEntity.tryToStoreContents(ChestBlockEntity.java:494) ~[appliedenergistics2-fabric-0.0.0-SNAPSHOT.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at appeng.tile.storage.ChestBlockEntity.onChangeInventory(ChestBlockEntity.java:471) ~[appliedenergistics2-fabric-0.0.0-SNAPSHOT.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at appeng.tile.inventory.AppEngInternalInventory.onContentsChanged(AppEngInternalInventory.java:131) ~[appliedenergistics2-fabric-0.0.0-SNAPSHOT.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at appeng.tile.inventory.AppEngInternalInventory.setInvStack(AppEngInternalInventory.java:106) ~[appliedenergistics2-fabric-0.0.0-SNAPSHOT.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at alexiil.mc.lib.attributes.item.FixedItemInv.insertStack(FixedItemInv.java:117) ~[f859bddd-9a48-4ca3-abcf-11b288ed1953.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at alexiil.mc.lib.attributes.item.SingleItemSlot.attemptInsertion(SingleItemSlot.java:58) ~[f859bddd-9a48-4ca3-abcf-11b288ed1953.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at appeng.parts.misc.ItemHandlerAdapter.injectItems(ItemHandlerAdapter.java:78) ~[appliedenergistics2-fabric-0.0.0-SNAPSHOT.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at appeng.parts.misc.ItemHandlerAdapter.injectItems(ItemHandlerAdapter.java:54) ~[appliedenergistics2-fabric-0.0.0-SNAPSHOT.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at appeng.me.storage.MEPassThrough.injectItems(MEPassThrough.java:50) ~[appliedenergistics2-fabric-0.0.0-SNAPSHOT.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at appeng.me.storage.MEInventoryHandler.injectItems(MEInventoryHandler.java:91) ~[appliedenergistics2-fabric-0.0.0-SNAPSHOT.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at appeng.me.storage.NetworkInventoryHandler.injectItems(NetworkInventoryHandler.java:104) ~[appliedenergistics2-fabric-0.0.0-SNAPSHOT.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at appeng.me.cache.NetworkMonitor.injectItems(NetworkMonitor.java:143) ~[appliedenergistics2-fabric-0.0.0-SNAPSHOT.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at appeng.util.Platform.poweredInsert(Platform.java:843) ~[appliedenergistics2-fabric-0.0.0-SNAPSHOT.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at appeng.util.Platform.poweredInsert(Platform.java:797) ~[appliedenergistics2-fabric-0.0.0-SNAPSHOT.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at appeng.container.AEBaseContainer.doAction(AEBaseContainer.java:760) ~[appliedenergistics2-fabric-0.0.0-SNAPSHOT.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at appeng.core.sync.packets.InventoryActionPacket.serverPacketData(InventoryActionPacket.java:128) ~[appliedenergistics2-fabric-0.0.0-SNAPSHOT.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at appeng.core.sync.network.ServerNetworkHandler.lambda$handlePacketFromClient$3(ServerNetworkHandler.java:74) ~[appliedenergistics2-fabric-0.0.0-SNAPSHOT.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:758) ~[intermediary-server.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:152) ~[intermediary-server.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:740) ~[intermediary-server.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:734) ~[intermediary-server.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:719) ~[intermediary-server.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[intermediary-server.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254) ~[intermediary-server.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at java.lang.Thread.run(Thread.java:834) [?:?]
Sep 18 01:06:19 fibercraft run.sh[11445]: [01:06:19] [Server thread/ERROR]: Encountered an unexpected exception
Sep 18 01:06:19 fibercraft run.sh[11445]: net.minecraft.class_148: Ticking block entity
Sep 18 01:06:19 fibercraft run.sh[11445]:         at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:872) ~[intermediary-server.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at net.minecraft.class_3176.method_3813(class_3176.java:303) ~[intermediary-server.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:808) ~[intermediary-server.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:667) ~[intermediary-server.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254) ~[intermediary-server.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at java.lang.Thread.run(Thread.java:834) [?:?]
Sep 18 01:06:19 fibercraft run.sh[11445]: Caused by: java.lang.IllegalStateException: Unable to force-set the slot 0 to Empty!
Sep 18 01:06:19 fibercraft run.sh[11445]:         at alexiil.mc.lib.attributes.item.FixedItemInv.forceSetInvStack(FixedItemInv.java:72) ~[f859bddd-9a48-4ca3-abcf-11b288ed1953.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at appeng.tile.storage.ChestBlockEntity.tryToStoreContents(ChestBlockEntity.java:494) ~[appliedenergistics2-fabric-0.0.0-SNAPSHOT.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at appeng.tile.storage.ChestBlockEntity.method_16896(ChestBlockEntity.java:358) ~[appliedenergistics2-fabric-0.0.0-SNAPSHOT.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at net.minecraft.class_1937.method_18471(class_1937.java:510) ~[intermediary-server.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at net.minecraft.class_3218.method_18765(class_3218.java:424) ~[intermediary-server.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:868) ~[intermediary-server.jar:?]
Sep 18 01:06:19 fibercraft run.sh[11445]:         ... 5 more




Sep 18 01:08:59 fibercraft run.sh[18852]: [01:08:59] [Server thread/ERROR]: Failed to load data for block entity appliedenergistics2:chest
Sep 18 01:08:59 fibercraft run.sh[18852]: java.lang.IllegalStateException: Unable to force-set the slot 0 to 64xblock.astromine.copper_ore tag = null!
Sep 18 01:08:59 fibercraft run.sh[18852]:         at alexiil.mc.lib.attributes.item.FixedItemInv.forceSetInvStack(FixedItemInv.java:72) ~[cdfbf4e2-3c3d-4b0d-9340-c5a479adb631.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at appeng.util.helpers.ItemHandlerUtil.setStackInSlot(ItemHandlerUtil.java:31) ~[appliedenergistics2-fabric-0.0.0-SNAPSHOT.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at appeng.tile.AEBaseInvBlockEntity.method_11014(AEBaseInvBlockEntity.java:55) ~[appliedenergistics2-fabric-0.0.0-SNAPSHOT.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at appeng.tile.powersink.AEBasePoweredBlockEntity.method_11014(AEBasePoweredBlockEntity.java:85) ~[appliedenergistics2-fabric-0.0.0-SNAPSHOT.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at appeng.tile.grid.AENetworkPowerBlockEntity.method_11014(AENetworkPowerBlockEntity.java:45) ~[appliedenergistics2-fabric-0.0.0-SNAPSHOT.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at appeng.tile.storage.ChestBlockEntity.method_11014(ChestBlockEntity.java:406) ~[appliedenergistics2-fabric-0.0.0-SNAPSHOT.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at net.minecraft.class_2586.method_17897(class_2586.java:86) ~[intermediary-server.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at java.util.Optional.map(Optional.java:265) ~[?:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at net.minecraft.class_2586.method_11005(class_2586.java:84) ~[intermediary-server.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at net.minecraft.class_2852.method_12386(class_2852.java:394) ~[intermediary-server.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at net.minecraft.class_2852.method_12388(class_2852.java:138) ~[intermediary-server.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at net.minecraft.class_2818.method_12206(class_2818.java:479) ~[intermediary-server.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at net.minecraft.class_3898.method_17227(class_3898.java:622) ~[intermediary-server.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[intermediary-server.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[intermediary-server.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[intermediary-server.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at net.minecraft.class_3898.method_20460(class_3898.java:611) ~[intermediary-server.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642) ~[?:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at net.minecraft.class_3900.method_17634(class_3900.java:58) ~[intermediary-server.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:545) ~[intermediary-server.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:554) ~[intermediary-server.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at net.minecraft.class_3215.getChunkBlocking(class_3215.java:1271) ~[intermediary-server.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at net.minecraft.class_3215.method_12121(class_3215.java:1165) ~[intermediary-server.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at net.minecraft.class_1937.getChunkLithium(class_1937.java:3240) ~[intermediary-server.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at net.minecraft.class_1937.method_22350(class_1937.java:3216) ~[intermediary-server.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at net.minecraft.class_1937.method_8500(class_1937.java:3211) ~[intermediary-server.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at net.minecraft.class_1937.method_8321(class_1937.java:610) ~[intermediary-server.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at com.github.chainmailstudios.astromine.common.utilities.data.position.WorldPos.getBlockEntity(WorldPos.java:101) ~[b6ae5d1a-f20b-49d5-9e7f-6033a7aa2a1e.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at com.github.chainmailstudios.astromine.common.network.type.EnergyNetworkType.tick(EnergyNetworkType.java:57) ~[b6ae5d1a-f20b-49d5-9e7f-6033a7aa2a1e.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at com.github.chainmailstudios.astromine.common.network.NetworkInstance.method_16896(NetworkInstance.java:119) ~[b6ae5d1a-f20b-49d5-9e7f-6033a7aa2a1e.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4698) ~[?:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at java.util.Collections$SetFromMap.forEach(Collections.java:5581) ~[?:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at com.github.chainmailstudios.astromine.common.component.world.WorldNetworkComponent.method_16896(WorldNetworkComponent.java:140) ~[b6ae5d1a-f20b-49d5-9e7f-6033a7aa2a1e.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at com.github.chainmailstudios.astromine.registry.AstromineCommonCallbacks.lambda$initialize$2(AstromineCommonCallbacks.java:86) ~[b6ae5d1a-f20b-49d5-9e7f-6033a7aa2a1e.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$null$4(ServerTickEvents.java:84) ~[7e6e504b-738b-455c-af24-353c42ec981b.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at net.minecraft.class_3218.handler$bag000$startWorldTick(class_3218.java:7050) ~[intermediary-server.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at net.minecraft.class_3218.method_18765(class_3218.java:230) ~[intermediary-server.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:868) ~[intermediary-server.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at net.minecraft.class_3176.method_3813(class_3176.java:303) ~[intermediary-server.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:808) ~[intermediary-server.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:667) ~[intermediary-server.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254) ~[intermediary-server.jar:?]
Sep 18 01:08:59 fibercraft run.sh[18852]:         at java.lang.Thread.run(Thread.java:834) [?:?]
Sep 18 01:08:59 fibercraft run.sh[18852]: [01:08:59] [Server thread/WARN]: Skipping BlockEntity with id appliedenergistics2:chest
```

**Comment by shartte** [comment]
Fixed
