### ISSUE TITLE
Moving a ME Drive with a sticky piston crashes my server

### ISSUE THREAD

**Issue by recytec** [AppliedEnergistics/Applied-Energistics-2#5079]
**Describe the bug**
Moving a ME Drive with a sticky piston crashes my server

**To Reproduce**
Place sticky piston, enable it with redstone, disable and -> crash

**Expected behavior**
should move the ME drive correctly

Description: Exception ticking world

```
java.lang.IllegalStateException: Loading data after part of a grid, this is invalid.
	at appeng.me.GridNode.loadFromNBT(GridNode.java:344)
	at appeng.me.helpers.AENetworkProxy.readFromNBT(AENetworkProxy.java:163)
	at appeng.tile.grid.AENetworkInvTile.func_145839_a(AENetworkInvTile.java:41)
	at appeng.tile.storage.TileDrive.func_145839_a(TileDrive.java:177)
	at sandro.RedstonePlusPlus.API.Movable.IMovable.preMove(IMovable.java:220)
	at sandro.RedstonePlusPlus.Modules.ImprovedPistons.Pistons.BlockPistonBaseFix.doMove(BlockPistonBaseFix.java:358)
	at sandro.RedstonePlusPlus.Modules.ImprovedPistons.Pistons.BlockPistonBaseFix.func_189539_a(BlockPistonBaseFix.java:270)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189547_a(BlockStateContainer.java:476)
	at net.minecraft.world.WorldServer.func_147485_a(WorldServer.java:1552)
	at net.minecraft.world.WorldServer.func_147488_Z(WorldServer.java:1538)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:449)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:975)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737)
	at java.lang.Thread.run(Unknown Source)
```

-- Head --
Thread: Server thread
```
Stacktrace:
	at appeng.me.GridNode.loadFromNBT(GridNode.java:344)
	at appeng.me.helpers.AENetworkProxy.readFromNBT(AENetworkProxy.java:163)
	at appeng.tile.grid.AENetworkInvTile.func_145839_a(AENetworkInvTile.java:41)
	at appeng.tile.storage.TileDrive.func_145839_a(TileDrive.java:177)
	at sandro.RedstonePlusPlus.API.Movable.IMovable.preMove(IMovable.java:220)
	at sandro.RedstonePlusPlus.Modules.ImprovedPistons.Pistons.BlockPistonBaseFix.doMove(BlockPistonBaseFix.java:358)
	at sandro.RedstonePlusPlus.Modules.ImprovedPistons.Pistons.BlockPistonBaseFix.func_189539_a(BlockPistonBaseFix.java:270)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189547_a(BlockStateContainer.java:476)
	at net.minecraft.world.WorldServer.func_147485_a(WorldServer.java:1552)
	at net.minecraft.world.WorldServer.func_147488_Z(WorldServer.java:1538)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:449)

```

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.16 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
