### ISSUE TITLE
AE2: terminals not showing items

### ISSUE THREAD

**Issue by MJOwen10** [AppliedEnergistics/Applied-Energistics-2#5199]
AE2 terminals not showing anything
**Describe the bug**

This in on a forge custom modpack and game version 1.16.5. Nothing show in any of the terminals, wired or wireless ones.
![2021-05-06_10 02 00](https://user-images.githubusercontent.com/83771257/117311862-99740180-ae52-11eb-8453-804bf3c2ff63.png)
![2021-05-06_10 02 14](https://user-images.githubusercontent.com/83771257/117311863-99740180-ae52-11eb-9e78-6aa523b14c2c.png)
![2021-05-06_10 02 19](https://user-images.githubusercontent.com/83771257/117311864-99740180-ae52-11eb-8598-590858b6cc96.png)

**To Reproduce**

ME controller, ME drive, storage cell, fluix cable, any but the interface terminal, supply power
**Expected behavior**

Items that I put in to the network should've poped up
**Additional context**

![2021-05-06_10 02 00](https://user-images.githubusercontent.com/83771257/117311862-99740180-ae52-11eb-8453-804bf3c2ff63.png)
![2021-05-06_10 02 14](https://user-images.githubusercontent.com/83771257/117311863-99740180-ae52-11eb-9e78-6aa523b14c2c.png)
![2021-05-06_10 02 19](https://user-images.githubusercontent.com/83771257/117311864-99740180-ae52-11eb-8598-590858b6cc96.png)

**Environment**

- Environment: 
- Custom modpack, latest AE2 installed
A list of the mods included:

Just Enough Items (JEI) (by mezz)
Toast Control (by Shadows_of_Fire)
Mekanism Additions (by bradyaidanc)
RFTools Base (by McJty)
MrCrayfish's Gun Mod (by MrCrayfish)
Just Enough Characters (by towdium)
Ender Storage 1.8.+ (by covers1624)
Storage Drawers (by Texelsaur)
MrCrayfish's Furniture Mod (by MrCrayfish)
AppleSkin (by squeek502)
SlashBlade (by flammpfeil)
Dungeon Crawl (by XIROC1337)
Better Ender Dragon (by Ricy41)
GraveStone Mod (by henkelmax)
Thermal Innovation (by TeamCoFH)
QuickSpawns (by itsmeowdev)
AE2 Extras (by tfarecnim)
QuickHomes (by itsmeowdev)
Chisels & Bits (by AlgorithmX2)
BetterEnd (Forge) (by Beethoven92)
QuickTeleports (by itsmeowdev)
Mowzie's Mobs (by bobmowzie)
Citadel (by alex1the1666)
XNet Gases (by Terrails)
SwingThroughGrass (by exidex)
Thermal Cultivation (by TeamCoFH)
Biomes O' Plenty (by Forstride)
Dynamic Surroundings (by OreCruncher)
Create (by simibubi)
Compact Machines (by davenonymous)
Mob Origins (by UltrusBot)
WorldEdit (by sk89q)
The Aether Reborn (by ImmortalDevs)
Mekanism (by bradyaidanc)
McJtyLib (by McJty)
YUNG's Better Caves (Forge) (by YUNGNICKYOUNG)
Sophisticated Backpacks (by P3pp3rF1y)
Mekanism Generators (by bradyaidanc)
Mekanism Tools (by bradyaidanc)
Milk All The Mobs (by Serilum)
Tool Belt (by gigaherz)
Ender Chested (by ModdingLegacy)
CodeChicken Lib 1.8.+ (by covers1624)
Better Weather - Seasons, Blizzards, and more! (by Corgi_Taco)
Thermal Foundation (by TeamCoFH)
inzhefop's Core (by inzhefop)
Effortless Building (by Requioss)
CoFH Core (by TeamCoFH)
Thermal Expansion (by TeamCoFH)
Obfuscate (by MrCrayfish)
Just Enough Resources (JER) (by way2muchnoise)
Cosmetic Armor Reworked (by LainMI)
Aquaculture 2 (by Shadowclaimer)
YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)
Collective (by Serilum)
Clumps (by Jaredlll08)
YUNG's Better Strongholds (Forge) (by YUNGNICKYOUNG)
Unity (by theCyanideX)
Off Hand Combat (by aya_shamelessmaru)
Mekanism Matter (by inzhefop)
Golden Hopper (by MrCrayfish)
MrCrayfish's Vehicle Mod (by MrCrayfish)
Fabric API (by modmuss50)
Alex's Mobs (by alex1the1666)
Unity: Dark Edition (by theCyanideX)
Applied Energistics 2 (by AlgorithmX2)
XNet (by McJty)
YUNG's API (Forge) (by YUNGNICKYOUNG)
Mouse Tweaks (by YaLTeR)
Origins (by Apace100)
Controlling (by Jaredlll08)
Ender Mail (by Chaosyr)
Placebo (by Shadows_of_Fire)

**Comment by shartte** [comment]
Can you please enable AE2 debug logging in the config file, retry and post your debug.log?

Otherwise this is not really fixable

**Comment by MJOwen10** [comment]
Okay, how do I enable AE2 debug logging in the config file?

**Comment by MJOwen10** [comment]
> Can you please enable AE2 debug logging in the config file, retry and post your debug.log?
> 
> Otherwise this is not really fixable
    Okay, how do I enable AE2 debug logging in the config file?

**Comment by shartte** [comment]
Find appliedenergistics2-common.toml (on both server + client btw), and set

```
DebugLogging = true
```

**Comment by MJOwen10** [comment]
13:50:40.517
net.minecraft.util.concurrent.ThreadTaskExecutor
Render thread
Error executing task on Client
io.netty.handler.codec.EncoderException: java.io.EOFException: fieldSize is too long! Length is 3585, but maximum is 64
	at net.minecraft.network.PacketBuffer.func_244272_a(PacketBuffer.java:289)
	at net.minecraft.network.PacketBuffer.func_150793_b(PacketBuffer.java:269)
	at appeng.util.item.AEItemStack.fromPacket(AEItemStack.java:119)
	at appeng.core.sync.packets.MEInventoryUpdatePacket.<init>(MEInventoryUpdatePacket.java:70)
	at appeng.core.sync.BasePacketHandler$PacketTypes$$Lambda$17708/365843740.apply(Unknown Source)
	at appeng.core.sync.BasePacketHandler$PacketTypes.parsePacket(BasePacketHandler.java:127)
	at appeng.core.sync.network.ClientPacketHandler.onPacketData(ClientPacketHandler.java:37)
	at appeng.core.sync.network.NetworkHandler.lambda$clientPacket$7(NetworkHandler.java:100)
	at appeng.core.sync.network.NetworkHandler$$Lambda$17769/342734976.run(Unknown Source)
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215)
	at appeng.core.sync.network.NetworkHandler.clientPacket(NetworkHandler.java:100)
	at net.minecraftforge.eventbus.ASMEventHandler_746_NetworkHandler_clientPacket_ServerCustomPayloadEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2571/2046140266.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86)
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:90)
	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$16579/1304036170.apply(Unknown Source)
	at java.util.Optional.map(Optional.java:215)
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:90)
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1904)
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:59)
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11)
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21)
	at net.minecraft.network.PacketThreadUtil$$Lambda$16682/402612325.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$474/1905758512.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
Caused by: java.io.EOFException: fieldSize is too long! Length is 3585, but maximum is 64
	at io.netty.buffer.ByteBufInputStream.checkAvailable(ByteBufInputStream.java:313)
	at io.netty.buffer.ByteBufInputStream.readFully(ByteBufInputStream.java:233)
	at java.io.DataInputStream.readUTF(DataInputStream.java:609)
	at io.netty.buffer.ByteBufInputStream.readUTF(ByteBufInputStream.java:287)
	at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:113)
	at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:87)
	at net.minecraft.network.PacketBuffer.func_244272_a(PacketBuffer.java:287)
	... 43 more
13:50:41.844
net.minecraft.util.concurrent.ThreadTaskExecutor
Render thread
Error executing task on Client
io.netty.handler.codec.EncoderException: java.io.EOFException: fieldSize is too long! Length is 3585, but maximum is 64
	at net.minecraft.network.PacketBuffer.func_244272_a(PacketBuffer.java:289)
	at net.minecraft.network.PacketBuffer.func_150793_b(PacketBuffer.java:269)
	at appeng.util.item.AEItemStack.fromPacket(AEItemStack.java:119)
	at appeng.core.sync.packets.MEInventoryUpdatePacket.<init>(MEInventoryUpdatePacket.java:70)
	at appeng.core.sync.BasePacketHandler$PacketTypes$$Lambda$17708/365843740.apply(Unknown Source)
	at appeng.core.sync.BasePacketHandler$PacketTypes.parsePacket(BasePacketHandler.java:127)
	at appeng.core.sync.network.ClientPacketHandler.onPacketData(ClientPacketHandler.java:37)
	at appeng.core.sync.network.NetworkHandler.lambda$clientPacket$7(NetworkHandler.java:100)
	at appeng.core.sync.network.NetworkHandler$$Lambda$17769/342734976.run(Unknown Source)
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215)
	at appeng.core.sync.network.NetworkHandler.clientPacket(NetworkHandler.java:100)
	at net.minecraftforge.eventbus.ASMEventHandler_746_NetworkHandler_clientPacket_ServerCustomPayloadEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2571/2046140266.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86)
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:90)
	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$16579/1304036170.apply(Unknown Source)
	at java.util.Optional.map(Optional.java:215)
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:90)
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1904)
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:59)
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11)
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21)
	at net.minecraft.network.PacketThreadUtil$$Lambda$16682/402612325.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$474/1905758512.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
Caused by: java.io.EOFException: fieldSize is too long! Length is 3585, but maximum is 64
	at io.netty.buffer.ByteBufInputStream.checkAvailable(ByteBufInputStream.java:313)
	at io.netty.buffer.ByteBufInputStream.readFully(ByteBufInputStream.java:233)
	at java.io.DataInputStream.readUTF(DataInputStream.java:609)
	at io.netty.buffer.ByteBufInputStream.readUTF(ByteBufInputStream.java:287)
	at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:113)
	at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:87)
	at net.minecraft.network.PacketBuffer.func_244272_a(PacketBuffer.java:287)
	... 43 more

**Comment by MJOwen10** [comment]
The debug log posted above appears everytime I try to access the network via any terminal, wired or wireless ones.

**Comment by shartte** [comment]
Thanks, this helps a ton!

**Comment by MJOwen10** [comment]
> Thanks, this helps a ton!

Thank you! As I will be expecting a ton of help from you guys lol!

**Comment by shartte** [comment]
We're already working on rewriting the Terminal UI and this issue will most likely be fixed by that (now that I see the error).
But I'll double-check.

**Comment by MJOwen10** [comment]
Ok, thanks for the awesome work!

**Comment by MJOwen10** [comment]
Hi! I notice the new release but didn't see the change log addressing this issue, and it still remains to be fixed as i logged in after updating. Will this be addressed in the next update perhaps?

**Comment by shartte** [comment]
This is going to be in the next alpha version since it's a full rework of the UI system that just happens to fix this problem too (along a lot of other stuff).

**Comment by MJOwen10** [comment]
I see, no worries, take your time and I believe it will be a fantastic alpha and release coming up

**Comment by MJOwen10** [comment]
> This is going to be in the next alpha version since it's a full rework of the UI system that just happens to fix this problem too (along a lot of other stuff).

Hi! Any update on this issue?
I log on yesterday and the issue remained to be unresolved

**Comment by Technici4n** [comment]
And did you update to the latest alpha? (Make a backup before!) Issues won't randomly fix themselves if you don't update... ^^
