### ISSUE TITLE
place a 'dense_energy_cell' with power but item counts is 1 on any block, the power will be lost

### ISSUE THREAD

**Issue by ChihoiTse** [AppliedEnergistics/Applied-Energistics-2#5226]
**Describe the bug**

- There is a newly discovered issue, in 1.16, if you place a 'dense_energy_cell' with power but item counts is 1 on any block, the power of 'dense_energy_cell' will be lost.As long as the counts of items is not 1, this problem will not occur

**To Reproduce**

- Use 'vibration_chamber' to charge the 'dense_energy_cell', then use 'network_tool' to fold it up and Make sure the item counts is 1 .Put it on any block, the energy will be lost

**Expected behavior**

- 'Dense_Energy_Cell' does not lose energy when placed on any square with a counts is 1

**Additional context**

- Fig. 1 `'dense_energy_cell` with less energy and counts is 1
![image](https://user-images.githubusercontent.com/49972747/118519580-d5b93300-b76b-11eb-8353-5c7a5b42f02d.png)

Fig. 2 Place it on any square,lose energy
![image](https://user-images.githubusercontent.com/49972747/118519621-deaa0480-b76b-11eb-9d69-167c9837e6c9.png)

Fig. 3 counts is not 1
![image](https://user-images.githubusercontent.com/49972747/118519754-faada600-b76b-11eb-821e-d8be26f6fd5f.png)

Fig.4 Place it on any square,all going well 
![image](https://user-images.githubusercontent.com/49972747/118519847-1153fd00-b76c-11eb-80b2-ec598e0b3e2c.png)

**Environment**

- Environment: 1.16.5
- crash-report:
```java
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 21-5-17 下午11:11
Description: Manually triggered debug crash

java.lang.Throwable: null
	at net.minecraft.client.KeyboardListener.func_204870_b(KeyboardListener.java:663) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:randompatches.mixins.json:client.keybindings.KeyboardListenerMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1539) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5.jar:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.4.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.KeyboardListener.func_204870_b(KeyboardListener.java:663) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:randompatches.mixins.json:client.keybindings.KeyboardListenerMixin,pl:mixin:A}
-- Affected level --
Details:
	All players: 2 total; [ClientPlayerEntity['sakura'/66345, l='ClientLevel', x=-3376.41, y=64.00, z=-388.39], RemoteClientPlayerEntity['Faith'/60718, l='ClientLevel', x=-3374.50, y=64.00, z=-381.50]]
	Chunk stats: Client Chunk Cache: 729, 649
	Level dimension: minecraft:overworld
	Level spawn location: World: (-18,66,128), Chunk: (at 14,4,0 in -2,8; contains blocks -32,0,128 to -17,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 108035711 game time, 35616 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:APP:endergetic.mixins.json:ClientWorldMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5.jar:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.4.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6449377984 bytes (6150 MB) / 10737418240 bytes (10240 MB) up to 10737418240 bytes (10240 MB)
	CPUs: 16
	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx10240m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.4.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.4.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.4.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.4.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/%5B高清修复%5DOptiFine_1.16.5_HD_U_G7.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.4.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.4
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		[附魔书颜色]enchantedbookredesign-3.3-1.16.4.jar       |Enchanted Book Redesign       |enchantedbookredesign         |3.3-1.16.4          |DONE      |NOSIGNATURE
		[机械动力：物品附加]create-stuff-additions1.16.5_v1.0.3.jar|Create Stuff Additions        |create_stuff_additions        |1.0.2               |DONE      |NOSIGNATURE
		[夸克：奇思妙想]QuarkOddities-1.16.3.jar                 |Quark Oddities                |quarkoddities                 |1.16.3              |DONE      |NOSIGNATURE
		[自动钓鱼]forgeautofish-2.0.3-1.16.x.jar              |AutoFish for Forge            |forgeautofish                 |2.0.3               |DONE      |NOSIGNATURE
		[一件整理]inventoryprofiles-forge-1.16.2-0.4.2.jar    |Inventory Profiles            |inventoryprofiles             |0.4.2               |DONE      |NOSIGNATURE
		[更大的堆叠]upsizer-mc1.16.4-6.1.1.jar                 |Upsizer                       |upsizer                       |6.1.1               |DONE      |NOSIGNATURE
		[物品管理]jei-1.16.4-7.6.1.71.jar                     |Just Enough Items             |jei                           |7.6.1.71            |DONE      |NOSIGNATURE
		[万物皆可获得经验]GetExpForEverything-v1.2.2-1.14-1.16.jar|Get experience for everything!|getexpforeverything           |1.2.2               |DONE      |NOSIGNATURE
		[更多船，秋园，薰衣草花园，河口蓝色群系前置]abnormals_core-1.16.5-3.1.0|Abnormals Core                |abnormals_core                |3.1.0               |DONE      |NOSIGNATURE
		[通用机械]Mekanism-1.16.5-10.0.21.448.jar             |Mekanism                      |mekanism                      |10.0.21             |DONE      |NOSIGNATURE
		[伤害显示]torohealth-1.16.4-forge-4.jar               |ToroHealth                    |torohealth                    |NONE                |DONE      |NOSIGNATURE
		[更多船]extraboats-1.16.5-2.1.0.jar                  |Extra Boats                   |extraboats                    |2.1.0               |DONE      |NOSIGNATURE
		[找我]findme-1.16.3-2.1.0.0.jar                     |Find Me                       |findme                        |NONE                |DONE      |NOSIGNATURE
		[机械动力]create-mc1.16.5_v0.3.1c.jar                 |Create                        |create                        |mc1.16.5_v0.3.1c+151|DONE      |NOSIGNATURE
		[yung的洞穴优化]BetterCaves-Forge-1.16.4-1.1.1.jar     |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.1        |DONE      |NOSIGNATURE
		[传送石碑]Waystones_1.16.5-7.4.0.jar                  |Waystones                     |waystones                     |7.4.0               |DONE      |NOSIGNATURE
		[键位冲突显示]Controlling-7.0.0.14.jar                  |Controlling                   |controlling                   |7.0.0.14            |DONE      |NOSIGNATURE
		[自动汉化更新]i18nupdatemod-1.16.5-2.0.1.jar            |I18n update Mod               |i18nupdatemod                 |2.0.1               |DONE      |NOSIGNATURE
		[应用能源2]appliedenergistics2-8.3.1.jar              |Applied Energistics 2         |appliedenergistics2           |8.3.1               |DONE      |95:58:cc:83:9d:a8:fa:4f:e9:f3:54:90:66:61:c8:ae:9c:08:88:11:52:52:df:2d:28:5f:05:d8:28:57:0f:98
		[旅行背包]TravelersBackpack-1.16.4-5.4.1.jar          |Traveler's Backpack           |travelersbackpack             |5.4.1               |DONE      |NOSIGNATURE
		[yung的洞穴优化前置]YungsApi-1.16.4-Forge-6.jar          |YUNG's API                    |yungsapi                      |1.16.4-Forge-6      |DONE      |NOSIGNATURE
		[地下村庄]stoneholm-1.2.1.jar                         |Stoneholm                     |stoneholm                     |1.2                 |DONE      |NOSIGNATURE
		[不死图腾槽位]curioofundying-forge-1.16.4-5.1.0.0.jar   |Curio of Undying              |curioofundying                |1.16.4-5.1.0.0      |DONE      |NOSIGNATURE
		[突变生物]MutantBeasts-1.16.4-1.1.3.jar               |Mutant Beasts                 |mutantbeasts                  |1.16.4-1.1.3        |DONE      |d9:be:bd:b6:9a:e4:14:aa:05:67:fb:84:06:77:a0:c5:10:ec:27:15:1b:d6:c0:88:49:9a:ef:26:77:61:0b:5e
		[随缘修复]randompatches-2.4.4-forge.jar               |RandomPatches                 |randompatches                 |2.4.4-forge         |DONE      |92:f6:29:d4:09:89:f5:f5:98:5e:20:34:31:d0:7b:58:22:06:bd:a5:d1:6a:92:6e:ac:3d:8d:18:c5:b2:5b:d7
		[飞檐走壁]walljump-forge-1.16.4-1.3.7.jar             |Wall-Jump!                    |walljump                      |1.16.4-1.3.7        |DONE      |NOSIGNATURE
		[服务器命令]Ma-Essentials-1.16.3-3.4.0.jar             |Ma Essentials                 |maessentials                  |1.16.3-3.4.0        |DONE      |NOSIGNATURE
		[可搬动的箱子]carryon-1.16.5-1.15.3.13.jar              |Carry On                      |carryon                       |1.15.3.13           |DONE      |8c:03:ac:7d:21:62:65:e2:83:91:f3:22:57:99:ed:75:78:1e:db:de:03:99:ef:53:3b:59:95:18:01:bc:84:a9
		forge-1.16.5-36.1.4-universal.jar                 |Forge                         |forge                         |36.1.4              |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		[经验装瓶]exp_bottling-1.16.3-5.jar                   |EXP Bottling                  |exp_bottling                  |1.16.3-5            |DONE      |NOSIGNATURE
		[简单矿石]SimpleOres2-1.16.5-2.4.4.0.jar              |Simple Ores                   |simpleores                    |1.16.5-2.4.4.0      |DONE      |NOSIGNATURE
		[更多箱子]ironchest-1.16.4-11.2.10.jar                |Iron Chests                   |ironchest                     |1.16.4-11.2.10      |DONE      |NOSIGNATURE
		[补种农作物]replantingcrops_1.16.5-2.2.jar             |Replanting Crops              |replantingcrops               |2.2                 |DONE      |NOSIGNATURE
		[合成辅助]CraftingTweaks_1.16.3-12.2.0.jar            |Crafting Tweaks               |craftingtweaks                |12.2.0              |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.4-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		[碧海新生]upgrade_aquatic-1.16.5-3.1.0.jar            |Upgrade Aquatic               |upgrade_aquatic               |3.1.0               |DONE      |NOSIGNATURE
		[热力前置]cofh_core-1.16.4-1.2.1.jar                  |CoFH Core                     |cofh_core                     |1.2.1               |DONE      |NOSIGNATURE
		[热力基本]thermal_foundation-1.16.4-1.2.0.jar         |Thermal Series                |thermal                       |1.2.0               |DONE      |NOSIGNATURE
		[末地拓展]endergetic-1.16.4-3.0.0.jar                 |The Endergetic Expansion      |endergetic                    |3.0.0               |DONE      |NOSIGNATURE
		[改进结构]crepurposed_structures-1.16.5-2.6.6-forge.ja|Repurposed Structures         |repurposed_structures         |1.16.5-2.6.6-forge  |DONE      |NOSIGNATURE
		[鼠标手势]MouseTweaks-2.14-mc1.16.2.jar               |Mouse Tweaks                  |mousetweaks                   |2.14                |DONE      |NOSIGNATURE
		[薰衣草花园]Abundance-1.16.5-1.0.5.jar                 |Abundance                     |abundance                     |1.16.5-1.0.5        |DONE      |NOSIGNATURE
		[超多生物群系]BiomesOPlenty-1.16.4-13.0.0.431-universal.|Biomes O' Plenty              |biomesoplenty                 |1.16.4-13.0.0.431   |DONE      |NOSIGNATURE
		[玉，Hwyla附属]Jade-1.16.4-2.6.2.jar                  |Jade                          |jade                          |2.6.2               |DONE      |NOSIGNATURE
		[末地重置]EndRemastered-R36.jar                       |End Remastered 3.6            |endrem                        |1.16.3              |DONE      |NOSIGNATURE
		[简单矿石前置]SimpleCoreLib-1.16.5-2.0.5.0.jar          |SimpleCoreLib                 |simplecorelib                 |1.16.5-2.0.5.0      |DONE      |NOSIGNATURE
		[流畅加载]smoothboot-forge-1.16.4-1.2.2.jar           |Smooth Boot                   |smoothboot                    |1.16.4-1.2.2        |DONE      |NOSIGNATURE
		[区块载入器]ChickenChunks-1.16.4-2.7.0.85-universal.jar|ChickenChunks                 |chickenchunks                 |2.7.0.85            |DONE      |31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		[回收箱，已下架mcbbs]Corail-Recycler-NE-1.16.4-385.jar   |Corail Recycler NE            |corail_recycler_ne            |1.16.4-385          |DONE      |NOSIGNATURE
		[不死图腾槽位前置API]curios-forge-1.16.5-4.0.5.1.jar      |Curios API                    |curios                        |1.16.5-4.0.5.1      |DONE      |NOSIGNATURE
		[补种农作物前置]collective-1.16.5-2.11.jar               |Collective                    |collective                    |2.11                |DONE      |NOSIGNATURE
		[墓碑]gravestone-1.16.5-1.0.1.jar                   |Gravestone Mod                |gravestone                    |1.16.5-1.0.1        |DONE      |NOSIGNATURE
		[秋园]autumnity-1.16.5-2.1.0.jar                    |Autumnity                     |autumnity                     |2.1.0               |DONE      |NOSIGNATURE
		[夸克前置]AutoRegLib-1.6-47.jar                       |AutoRegLib                    |autoreglib                    |1.6-47              |DONE      |NOSIGNATURE
		[夸克]Quark-r2.4-311.jar                            |Quark                         |quark                         |r2.4-311            |DONE      |NOSIGNATURE
		[热力膨胀]thermal_expansion-1.16.4-1.2.0.jar          |Thermal Expansion             |thermal_expansion             |1.2.0               |DONE      |NOSIGNATURE
		[苹果皮]AppleSkin-mc1.16.2-forge-1.0.14.jar          |AppleSkin                     |appleskin                     |1.0.14              |DONE      |NOSIGNATURE
		[地下村庄前置]cloth-config-4.11.19-forge.jar            |Cloth Config v4 API           |cloth-config                  |4.11.19             |DONE      |NOSIGNATURE
		[准确放置]ProPlacer-v1.0-1.16.2.jar                   |Pro Placer                    |proplacer                     |1.0                 |DONE      |d3:cc:6f:1b:30:87:fa:d9:8f:91:15:20:27:63:95:aa:d5:cb:1b:5b:e6:36:cc:57:20:a9:b3:d4:d5:1a:5d:b8
		[体素地图]forgemod_VoxelMap-1.10.12_for_1.16.5.jar    |VoxelMap                      |voxelmap                      |1.10.15             |DONE      |NOSIGNATURE
		[进入水桶]getinthebucketmod-1.16.5-3.0.6.jar          |Get In The Bucket Mod         |getinthebucketmod             |3.0.6               |DONE      |NOSIGNATURE
		[鸡块核心，区块载入器前置]CodeChickenLib-1.16.4-3.5.1.408-univ|CodeChicken Lib               |codechickenlib                |3.5.1.408           |DONE      |31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		[驱魔台]Disenchanting-forge-1.16.5-1.7.1.jar         |Disenchanting                 |disenchanting                 |1.6.0               |DONE      |NOSIGNATURE
		[yung的矿井优化]BetterMineshafts-Forge-1.16.4-2.0.3.jar|YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.3        |DONE      |NOSIGNATURE
		[原版工具+]supertools-1.16.5-4.4.jar                  |Vanilla+ Tools                |supertools                    |version             |DONE      |NOSIGNATURE
	Crash Report UUID: 226d347e-d7a8-4362-bb8d-8def06324fec
	Launched Version: HMCL 3.3.173
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Radeon RX Vega GL version 4.6.14757 Compatibility Profile Context 20.11.2 27.20.14501.18003, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources, quark:emote_resources (incompatible), file/Quark Programmer Art.zip
	Current Language: 简体中文 (中国)
	CPU: 16x AMD Ryzen 7 2700 Eight-Core Processor 
```

**Comment by ChihoiTse** [comment]
This problem had a huge impact on my experience with the game

**Comment by ChihoiTse** [comment]
This problem had a huge impact on my experience with the game.Please fix.

**Comment by yueh** [comment]
Cannot reproduce this. The modlist also contains some mods which claim to break block placement, so be sure you can reproduce this with only AE2.

**Comment by ChihoiTse** [comment]
> Cannot reproduce this. The modlist also contains some mods which claim to break block placement, so be sure you can reproduce this with only AE2.
Just tested, only AE2 remains in the mod list, and there are still problems.
I've just run a test and found a more accurate description of the BUG, so I change the first post now.
I'll describe it here：if you place a 'dense_energy_cell' with power but item counts is 1 on any block, the power of 'dense_energy_cell' will be lost.As long as the counts of items is not 1, this problem will not occur

**Comment by ChihoiTse** [comment]
> > Cannot reproduce this. The modlist also contains some mods which claim to break block placement, so be sure you can reproduce this with only AE2.
- Just tested, only AE2 remains in the mod list, and there are still problems. 
- I've just run a test and found a more accurate description of the BUG, so I change the first post now.
- I'll describe it here：if you place a 'dense_energy_cell' with power but item counts is 1 on any block, the power of 'dense_energy_cell' will be lost.As long as the counts of items is not 1, this problem will not occur

**Comment by masakitenchi** [comment]
Reproduced while in survival.
Mods:
appliedenergistics2-8.3.1.jar
architectury-1.12.145-forge.jar
InventoryEssentials_1.16.3-2.3.1.jar
InventoryHud_[1.16.2-1.16.5].forge-3.2.2.jar
invtweaks-1.16.4-1.0.1.jar
item-filters-1605.2.4-build.30-forge.jar
itemzoom-1.16.4-2.3.0.jar
jei-1.16.5-7.7.0.91.jar
justenoughbeacons-3.1-1.16.3.jar
JustEnoughCharacters-1.16.4-4.1.6.jar
JustEnoughProfessions-1.16.5-1.2.1.jar
JustEnoughResources-1.16.4-0.12.0.109.jar
Mekanism-1.16.5-10.0.21.448.jar
MekanismGenerators-1.16.5-10.0.21.448.jar
MekanismTools-1.16.5-10.0.21.448.jar
theoneprobe-1.16-3.0.8.jar

Java version:
Openjdk 11.0.11.9
Forge version:
36.1.18

https://user-images.githubusercontent.com/11086210/118557122-b936ee00-b79f-11eb-9f0c-3627b77b1fbf.mp4

**Comment by ChihoiTse** [comment]
Change the title to a more accurate description
