### ISSUE TITLE
ME Interface Terminal breakes with too many crafting patterns 

### ISSUE THREAD

**Issue by d0x7** [AppliedEnergistics/Applied-Energistics-2#5298]
**Describe the bug**
Once there are too many recipes put in ME Interfaces, the ME Interface Terminal stays empty with a error in the log. I didn't notice the error at first and thought it might be a channel issue. Once I noticed it, I removed some patterns and I could use the terminal again.

I'm almost 100% certain the issue is the same as #5082, which got closed due to lacking details.

Just after I rebuild everything in SP I thought about that it won't not work in SP, because it's a network related issue.. lol. 
On our SMP I have four of those "star shaped" assembler interface, well, stars. Each has 12 interfaces with assemblers connected to as many sides as possible - I don't think this matters but just in case.

**To Reproduce**
Build something like 36-48 ME Interfaces on a SMP, fill each of them with recipes (just fill one and CTRL copy the others) until the ME Interface Terminal stops working and the error appears in the log. 

Eventually it's also (as the issue is that the NBT data is too big) related to the fact that there are some more or less complex recipes. I don't know how AE2 handles the data for the ME Interface Terminal (network-wise), therefore I'm not sure whether this issue exists with 48 interfaces filled with recipes of a stone button (e.g. very simple), or if the issue would already appear at, lets say, some basic stuff plus 24 times a complex recipe that recipes nine different components with eight sub crafted components - I hope you understand what I mean.

**Expected behavior**
Still show all patterns, regardless of how many patterns there are.

**Additional context**
The following stacktrace prints every time I'm opening/right clicking the ME Interface Terminal:
```JAVA
[16Jun2021 00:15:35.357] [Render thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Client
java.lang.RuntimeException: Tried to read NBT tag that was too big; tried to allocate: 2097192bytes where max allowed: 2097152
	at net.minecraft.nbt.NBTSizeTracker.func_152450_a(NBTSizeTracker.java:18) ~[?:?]
	at net.minecraft.nbt.CompoundNBT$1.func_225649_b_(CompoundNBT.java:51) ~[?:?]
	at net.minecraft.nbt.CompoundNBT$1.func_225649_b_(CompoundNBT.java:40) ~[?:?]
	at net.minecraft.nbt.CompoundNBT.func_229680_b_(CompoundNBT.java:423) ~[?:?]
	at net.minecraft.nbt.CompoundNBT.func_229678_a_(CompoundNBT.java:31) ~[?:?]
	at net.minecraft.nbt.CompoundNBT$1.func_225649_b_(CompoundNBT.java:53) ~[?:?]
	at net.minecraft.nbt.CompoundNBT$1.func_225649_b_(CompoundNBT.java:40) ~[?:?]
	at net.minecraft.nbt.ListNBT$1.func_225649_b_(SourceFile:49) ~[?:?]
	at net.minecraft.nbt.ListNBT$1.func_225649_b_(SourceFile:32) ~[?:?]
	at net.minecraft.nbt.CompoundNBT.func_229680_b_(CompoundNBT.java:423) ~[?:?]
	at net.minecraft.nbt.CompoundNBT.func_229678_a_(CompoundNBT.java:31) ~[?:?]
	at net.minecraft.nbt.CompoundNBT$1.func_225649_b_(CompoundNBT.java:53) ~[?:?]
	at net.minecraft.nbt.CompoundNBT$1.func_225649_b_(CompoundNBT.java:40) ~[?:?]
	at net.minecraft.nbt.CompoundNBT.func_229680_b_(CompoundNBT.java:423) ~[?:?]
	at net.minecraft.nbt.CompoundNBT.func_229678_a_(CompoundNBT.java:31) ~[?:?]
	at net.minecraft.nbt.CompoundNBT$1.func_225649_b_(CompoundNBT.java:53) ~[?:?]
	at net.minecraft.nbt.CompoundNBT$1.func_225649_b_(CompoundNBT.java:40) ~[?:?]
	at net.minecraft.nbt.CompoundNBT.func_229680_b_(CompoundNBT.java:423) ~[?:?]
	at net.minecraft.nbt.CompoundNBT.func_229678_a_(CompoundNBT.java:31) ~[?:?]
	at net.minecraft.nbt.CompoundNBT$1.func_225649_b_(CompoundNBT.java:53) ~[?:?]
	at net.minecraft.nbt.CompoundNBT$1.func_225649_b_(CompoundNBT.java:40) ~[?:?]
	at net.minecraft.nbt.CompoundNBT.func_229680_b_(CompoundNBT.java:423) ~[?:?]
	at net.minecraft.nbt.CompoundNBT.func_229678_a_(CompoundNBT.java:31) ~[?:?]
	at net.minecraft.nbt.CompoundNBT$1.func_225649_b_(CompoundNBT.java:53) ~[?:?]
	at net.minecraft.nbt.CompoundNBT$1.func_225649_b_(CompoundNBT.java:40) ~[?:?]
	at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:117) ~[?:?]
	at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:87) ~[?:?]
	at net.minecraft.network.PacketBuffer.func_244272_a(PacketBuffer.java:406) ~[?:?]
	at net.minecraft.network.PacketBuffer.func_150793_b(PacketBuffer.java:381) ~[?:?]
	at appeng.core.sync.packets.MEInterfaceUpdatePacket.<init>(MEInterfaceUpdatePacket.java:46) ~[?:8.3.1]
	at appeng.core.sync.BasePacketHandler$PacketTypes$$Lambda$26028/237572437.apply(Unknown Source) ~[?:?]
	at appeng.core.sync.BasePacketHandler$PacketTypes.parsePacket(BasePacketHandler.java:127) ~[?:8.3.1]
	at appeng.core.sync.network.ClientPacketHandler.onPacketData(ClientPacketHandler.java:37) ~[?:8.3.1]
	at appeng.core.sync.network.NetworkHandler.lambda$clientPacket$7(NetworkHandler.java:100) ~[?:8.3.1]
	at appeng.core.sync.network.NetworkHandler$$Lambda$26053/670657276.run(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[?:?]
	at appeng.core.sync.network.NetworkHandler.clientPacket(NetworkHandler.java:100) ~[?:8.3.1]
	at net.minecraftforge.eventbus.ASMEventHandler_1468_NetworkHandler_clientPacket_ServerCustomPayloadEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2595/1021903388.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:90) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$22924/1080945000.apply(Unknown Source) ~[?:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:90) ~[?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1904) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:59) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:36) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$23311/1261062696.run(Unknown Source) ~[?:?]
	at net.optifine.util.PacketRunnable.run(PacketRunnable.java:28) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:189) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:151) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:128) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.0.jar:36.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$486/1567857145.call(Unknown Source) [forge-1.16.5-36.1.0.jar:36.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?
```

Same issue without OptiFine installed:
```JAVA
[16Jun2021 00:15:35.357] [Render thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Client
java.lang.RuntimeException: Tried to read NBT tag that was too big; tried to allocate: 2097192bytes where max allowed: 2097152
	at net.minecraft.nbt.NBTSizeTracker.func_152450_a(NBTSizeTracker.java:18) ~[?:?]
	at net.minecraft.nbt.CompoundNBT$1.func_225649_b_(CompoundNBT.java:51) ~[?:?]
	at net.minecraft.nbt.CompoundNBT$1.func_225649_b_(CompoundNBT.java:40) ~[?:?]
	at net.minecraft.nbt.CompoundNBT.func_229680_b_(CompoundNBT.java:423) ~[?:?]
	at net.minecraft.nbt.CompoundNBT.func_229678_a_(CompoundNBT.java:31) ~[?:?]
	at net.minecraft.nbt.CompoundNBT$1.func_225649_b_(CompoundNBT.java:53) ~[?:?]
	at net.minecraft.nbt.CompoundNBT$1.func_225649_b_(CompoundNBT.java:40) ~[?:?]
	at net.minecraft.nbt.ListNBT$1.func_225649_b_(SourceFile:49) ~[?:?]
	at net.minecraft.nbt.ListNBT$1.func_225649_b_(SourceFile:32) ~[?:?]
	at net.minecraft.nbt.CompoundNBT.func_229680_b_(CompoundNBT.java:423) ~[?:?]
	at net.minecraft.nbt.CompoundNBT.func_229678_a_(CompoundNBT.java:31) ~[?:?]
	at net.minecraft.nbt.CompoundNBT$1.func_225649_b_(CompoundNBT.java:53) ~[?:?]
	at net.minecraft.nbt.CompoundNBT$1.func_225649_b_(CompoundNBT.java:40) ~[?:?]
	at net.minecraft.nbt.CompoundNBT.func_229680_b_(CompoundNBT.java:423) ~[?:?]
	at net.minecraft.nbt.CompoundNBT.func_229678_a_(CompoundNBT.java:31) ~[?:?]
	at net.minecraft.nbt.CompoundNBT$1.func_225649_b_(CompoundNBT.java:53) ~[?:?]
	at net.minecraft.nbt.CompoundNBT$1.func_225649_b_(CompoundNBT.java:40) ~[?:?]
	at net.minecraft.nbt.CompoundNBT.func_229680_b_(CompoundNBT.java:423) ~[?:?]
	at net.minecraft.nbt.CompoundNBT.func_229678_a_(CompoundNBT.java:31) ~[?:?]
	at net.minecraft.nbt.CompoundNBT$1.func_225649_b_(CompoundNBT.java:53) ~[?:?]
	at net.minecraft.nbt.CompoundNBT$1.func_225649_b_(CompoundNBT.java:40) ~[?:?]
	at net.minecraft.nbt.CompoundNBT.func_229680_b_(CompoundNBT.java:423) ~[?:?]
	at net.minecraft.nbt.CompoundNBT.func_229678_a_(CompoundNBT.java:31) ~[?:?]
	at net.minecraft.nbt.CompoundNBT$1.func_225649_b_(CompoundNBT.java:53) ~[?:?]
	at net.minecraft.nbt.CompoundNBT$1.func_225649_b_(CompoundNBT.java:40) ~[?:?]
	at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:117) ~[?:?]
	at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:87) ~[?:?]
	at net.minecraft.network.PacketBuffer.func_244272_a(PacketBuffer.java:406) ~[?:?]
	at net.minecraft.network.PacketBuffer.func_150793_b(PacketBuffer.java:381) ~[?:?]
	at appeng.core.sync.packets.MEInterfaceUpdatePacket.<init>(MEInterfaceUpdatePacket.java:46) ~[?:8.3.1]
	at appeng.core.sync.BasePacketHandler$PacketTypes$$Lambda$26028/237572437.apply(Unknown Source) ~[?:?]
	at appeng.core.sync.BasePacketHandler$PacketTypes.parsePacket(BasePacketHandler.java:127) ~[?:8.3.1]
	at appeng.core.sync.network.ClientPacketHandler.onPacketData(ClientPacketHandler.java:37) ~[?:8.3.1]
	at appeng.core.sync.network.NetworkHandler.lambda$clientPacket$7(NetworkHandler.java:100) ~[?:8.3.1]
	at appeng.core.sync.network.NetworkHandler$$Lambda$26053/670657276.run(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[?:?]
	at appeng.core.sync.network.NetworkHandler.clientPacket(NetworkHandler.java:100) ~[?:8.3.1]
	at net.minecraftforge.eventbus.ASMEventHandler_1468_NetworkHandler_clientPacket_ServerCustomPayloadEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2595/1021903388.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:90) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$22924/1080945000.apply(Unknown Source) ~[?:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:90) ~[?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1904) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:59) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:36) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$23311/1261062696.run(Unknown Source) ~[?:?]
	at net.optifine.util.PacketRunnable.run(PacketRunnable.java:28) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:189) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:151) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:128) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.0.jar:36.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$486/1567857145.call(Unknown Source) [forge-1.16.5-36.1.0.jar:36.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
```

**Environment**

In total I have around 90 mods, but I'm very certain none of them are involved in this issue. 
I do have OptiFine installed, and as your ruleset says, I disabled OptiFine to find out whether the issue persists - it does, even with a mere 2 FPS, lol.

- Minecraft: 1.16.5
- Forge: v36.1.0
- AE2: v8.3.1

**Comment by Technici4n** [comment]
Can you try on the latest version? (8.4.0-beta.1, backup your world!)
I'm pretty sure this exact issue was fixed with the 8.4 gui rework.

**Comment by yueh** [comment]
This definitively changed in 8.4. As it was a pretty massive change, it is very likely to not happen at all.

Closing for now as there won't be a 8.3 fix. Will be reopened, if it could happen in 8.4.

**Comment by frank89722** [comment]
Still happening in 8.4.0
```
[22:36:16] [Render thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Client
java.lang.RuntimeException: Tried to read NBT tag that was too big; tried to allocate: 2097174bytes where max allowed: 2097152
	at net.minecraft.nbt.NBTSizeTracker.func_152450_a(NBTSizeTracker.java:18) ~[?:?] {re:classloading}
	at net.minecraft.nbt.StringNBT$1.func_225649_b_(StringNBT.java:13) ~[?:?] {re:classloading}
	at net.minecraft.nbt.StringNBT$1.func_225649_b_(StringNBT.java:11) ~[?:?] {re:classloading}
	at net.minecraft.nbt.CompoundNBT.func_229680_b_(CompoundNBT.java:423) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:CompoundNBTMixin,pl:mixin:A}
	at net.minecraft.nbt.CompoundNBT.func_229678_a_(CompoundNBT.java:31) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:CompoundNBTMixin,pl:mixin:A}
	at net.minecraft.nbt.CompoundNBT$1.func_225649_b_(CompoundNBT.java:53) ~[?:?] {re:classloading}
	at net.minecraft.nbt.CompoundNBT$1.func_225649_b_(CompoundNBT.java:40) ~[?:?] {re:classloading}
	at net.minecraft.nbt.CompoundNBT.func_229680_b_(CompoundNBT.java:423) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:CompoundNBTMixin,pl:mixin:A}
	at net.minecraft.nbt.CompoundNBT.func_229678_a_(CompoundNBT.java:31) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:CompoundNBTMixin,pl:mixin:A}
	at net.minecraft.nbt.CompoundNBT$1.func_225649_b_(CompoundNBT.java:53) ~[?:?] {re:classloading}
	at net.minecraft.nbt.CompoundNBT$1.func_225649_b_(CompoundNBT.java:40) ~[?:?] {re:classloading}
	at net.minecraft.nbt.CompoundNBT.func_229680_b_(CompoundNBT.java:423) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:CompoundNBTMixin,pl:mixin:A}
	at net.minecraft.nbt.CompoundNBT.func_229678_a_(CompoundNBT.java:31) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:CompoundNBTMixin,pl:mixin:A}
	at net.minecraft.nbt.CompoundNBT$1.func_225649_b_(CompoundNBT.java:53) ~[?:?] {re:classloading}
	at net.minecraft.nbt.CompoundNBT$1.func_225649_b_(CompoundNBT.java:40) ~[?:?] {re:classloading}
	at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:117) ~[?:?] {re:classloading}
	at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:87) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketBuffer.func_244272_a(PacketBuffer.java:282) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.network.PacketBuffer.func_150793_b(PacketBuffer.java:264) ~[?:?] {re:mixin,re:classloading}
	at appeng.core.sync.packets.InterfaceTerminalPacket.<init>(InterfaceTerminalPacket.java:46) ~[appliedenergistics2:8.4.0] {re:classloading}
	at appeng.core.sync.BasePacketHandler$PacketTypes.parsePacket(BasePacketHandler.java:134) ~[appliedenergistics2:8.4.0] {re:classloading}
	at appeng.core.sync.network.ClientPacketHandler.onPacketData(ClientPacketHandler.java:37) ~[appliedenergistics2:8.4.0] {re:classloading}
	at appeng.core.sync.network.NetworkHandler.lambda$clientPacket$7(NetworkHandler.java:100) ~[appliedenergistics2:8.4.0] {re:classloading}
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[forge:?] {re:classloading}
	at appeng.core.sync.network.NetworkHandler.clientPacket(NetworkHandler.java:100) ~[appliedenergistics2:8.4.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_2160_NetworkHandler_clientPacket_ServerCustomPayloadEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:91) ~[forge:?] {re:classloading}
	at java.util.Optional.map(Optional.java:260) ~[?:?] {}
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:91) ~[forge:?] {re:classloading}
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1904) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:creativecore:clientnetwork,pl:mixin:APP:randompatches.mixins.json:client.keybindings.ClientPlayNetHandlerMixin,pl:mixin:APP:flywheel.mixins.json:light.NetworkLightUpdateMixin,pl:mixin:APP:endergetic.mixins.json:ClientPlayNetHandlerMixin,pl:mixin:APP:farsight.mixins.json:ClientPlayNetHandlerMixin,pl:mixin:APP:ftbchunks-common.mixins.json:ClientPacketListenerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:59) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:connectivity.mixins.json:SCustomPayloadPlayPacketMixin,pl:mixin:APP:connectivity.mixins.json:networkstats.SCustomPayloadPlayPacketNameMixin,pl:mixin:A}
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:connectivity.mixins.json:SCustomPayloadPlayPacketMixin,pl:mixin:APP:connectivity.mixins.json:networkstats.SCustomPayloadPlayPacketNameMixin,pl:mixin:A}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?] {re:classloading,xf:fml:screenshotclipboard:coremodone,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.2-launcher.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:52) [ForgeWrapper-1.5.1.jar:1.5.1] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}
```

**Comment by shartte** [comment]
How the hell did you manage to make it try to send over 2 MB of data????

**Comment by frank89722** [comment]
A player on my server having an AE system with around a hundred interfaces for auto crafting.
