### ISSUE TITLE
Game crash when stepping on an ME cable

### ISSUE THREAD

**Issue by Piikle** [AppliedEnergistics/Applied-Energistics-2#5321]
When I step on any kind of ME cable, it crashes my game and the only way I found to fix this is removing AE2 and rejoining then re-adding it again I have tried removing optifine to see if it would make any difference but no change here is the crash log:

java.lang.NullPointerException: Unexpected error
	at appeng.block.AEBaseTileBlock.getTileEntity(AEBaseTileBlock.java:102) ~[?:8.4.0] {re:classloading}
	at appeng.block.networking.CableBusBlock.func_220071_b(CableBusBlock.java:393) ~[?:8.4.0] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215685_b(AbstractBlock.java:545) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_196952_d(AbstractBlock.java:541) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at baritone.hn.h(Unknown Source) ~[?:1.6.3] {re:classloading}
	at baritone.hn.c(Unknown Source) ~[?:1.6.3] {re:classloading}
	at baritone.hn.b(Unknown Source) ~[?:1.6.3] {re:classloading}
	at baritone.hn.b(Unknown Source) ~[?:1.6.3] {re:classloading}
	at baritone.em.a(Unknown Source) ~[?:1.6.3] {re:classloading}
	at baritone.em.a(Unknown Source) ~[?:1.6.3] {re:classloading}
	at baritone.hf.a(Unknown Source) ~[?:1.6.3] {re:classloading}
	at baritone.hf$$Lambda$8472/498929737.accept(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890) ~[?:1.8.0_51] {}
	at baritone.hf.a(Unknown Source) ~[?:1.6.3] {re:classloading}
	at net.minecraft.client.Minecraft.handler$zzh000$runTick(Minecraft.java) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.baritone.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1448) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.baritone.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.baritone.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.baritone.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.24.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$488/1917607102.call(Unknown Source) [forge-1.16.5-36.1.24.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

**Comment by Piikle** [comment]
i had baritone in it lol i am blind

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
https://github.com/cabaletta/baritone/issues/2148
