### ISSUE TITLE
Moving Recipes from REI to Crafting Grid Fails.

### ISSUE THREAD

**Issue by Radagast** [AppliedEnergistics/Applied-Energistics-2#5518]
### Describe the bug

From the  AE2 crafting table interface select an item to craft. When the recipe appears select the Move button. The crafting grid remains empty.

### How to reproduce the bug

As above

### Expected behavior

The Crafting grid should be populated with the items required to make the craft.

### Additional details

AoF4 1/ Ae2 9.0.0 -alpha2

Log details:

```
[09:33:59] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: Cannot invoke "appeng.api.inventories.InternalInventory.size()" because "craftMatrix" is null
	at appeng.core.sync.packets.JEIRecipePacket.serverPacketData(JEIRecipePacket.java:175) ~[appliedenergistics2-9.0.0-alpha.2.jar:?]
	at appeng.core.sync.network.ServerNetworkHandler.lambda$handlePacketFromClient$3(ServerNetworkHandler.java:93) ~[appliedenergistics2-9.0.0-alpha.2.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-client-1.17.1.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-client-1.17.1.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-client-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788) ~[intermediary-client-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[intermediary-client-1.17.1.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-client-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[intermediary-client-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) ~[intermediary-client-1.17.1.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[intermediary-client-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:749) ~[intermediary-client-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[intermediary-client-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-client-1.17.1.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[09:34:31] [Server thread/INFO]: Saving and pausing game...
[09:34:31] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Aof4.Creative]'/minecraft:overworld
[09:34:31] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Aof4.Creative]'/minecraft:the_nether
[09:34:31] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Aof4.Creative]'/minecraft:the_end
[09:34:31] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Aof4.Creative]'/appliedenergistics2:spatial_storage
[09:34:31] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Aof4.Creative]'/minershorizon:miners_horizon

```

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/WAwiRin6

**Comment by mindforger** [comment]
Sorry, my phone acted up
