### ISSUE TITLE
The formation plane doesn't place sapplings from the network ( but blocks yes)

### ISSUE THREAD

**Issue by EnderProyects** [AppliedEnergistics/Applied-Energistics-2#5644]
### Describe the bug

I was doing tests of 1.17, and I was looking to make an automatic tree farm, the thing is that there is a formation plane placing sapplings and these do not take them from the network, when I think it should...

### How to reproduce the bug

Formation plane with any sappling in front of grass, if the sappling are in a chest with a storage bus it works fine, but not in a disk

### Expected behavior

Placing the sappling

### Additional details

I was using only the applied energistics 2 mod and the vanilla

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

```
---- Minecraft Crash Report ---- // Uh... Did I do that?  Time: 11/6/21, 1:27 AM Description: Manually triggered debug crash  java.lang.Throwable 	at net.minecraft.class_309.method_1474(class_309.java:489) 	at net.minecraft.class_310.method_1574(class_310.java:1803) 	at net.minecraft.class_310.method_1523(class_310.java:1081) 	at net.minecraft.class_310.method_1514(class_310.java:728) 	at net.minecraft.client.main.Main.main(Main.java:217) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.base/java.lang.reflect.Method.invoke(Method.java:568) 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568) 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.base/java.lang.reflect.Method.invoke(Method.java:568) 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) 	at org.multimc.EntryPoint.listen(EntryPoint.java:143) 	at org.multimc.EntryPoint.main(EntryPoint.java:34)   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Thread: Render thread Stacktrace: 	at net.minecraft.class_309.method_1474(class_309.java:489)  -- Affected level -- Details: 	All players: 1 total; [class_746['Ender_Proyects'/155, l='ClientLevel', x=187.28, y=85.88, z=123.24]] 	Chunk stats: 841, 576 	Level dimension: minecraft:overworld 	Level spawn location: World: (176,63,116), Section: (at 0,15,4 in 11,3,7; chunk contains blocks 176,0,112 to 191,255,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511) 	Level time: 79472 game time, 81253 day time 	Server brand: fabric 	Server type: Integrated singleplayer server Stacktrace: 	at net.minecraft.class_638.method_8538(class_638.java:370) 	at net.minecraft.class_310.method_1587(class_310.java:2399) 	at net.minecraft.class_310.method_1514(class_310.java:747) 	at net.minecraft.client.main.Main.main(Main.java:217) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.base/java.lang.reflect.Method.invoke(Method.java:568) 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568) 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.base/java.lang.reflect.Method.invoke(Method.java:568) 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) 	at org.multimc.EntryPoint.listen(EntryPoint.java:143) 	at org.multimc.EntryPoint.main(EntryPoint.java:34)  -- Last reload -- Details: 	Reload number: 1 	Reload reason: initial 	Finished: Yes 	Packs: Default, Fabric Mods  -- System Details -- Details: 	Minecraft Version: 1.17.1 	Minecraft Version ID: 1.17.1 	Operating System: Windows 10 (amd64) version 10.0 	Java Version: 17.0.1, Oracle Corporation 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation 	Memory: 625942920 bytes (596 MiB) / 1929379840 bytes (1840 MiB) up to 10586423296 bytes (10096 MiB) 	CPUs: 16 	Processor Vendor: GenuineIntel 	Processor Name: Intel(R) Core(TM) i9-9900 CPU @ 3.10GHz 	Identifier: Intel64 Family 6 Model 158 Stepping 13 	Microarchitecture: Coffee Lake 	Frequency (GHz): 3.10 	Number of physical packages: 1 	Number of physical CPUs: 8 	Number of logical CPUs: 16 	Graphics card #0 name: Intel(R) UHD Graphics 630 	Graphics card #0 vendor: Intel Corporation (0x8086) 	Graphics card #0 VRAM (MB): 1024.00 	Graphics card #0 deviceId: 0x3e98 	Graphics card #0 versionInfo: DriverVersion=27.20.100.8935 	Graphics card #1 name: NVIDIA GeForce GTX 1050 	Graphics card #1 vendor: NVIDIA (0x10de) 	Graphics card #1 VRAM (MB): 2048.00 	Graphics card #1 deviceId: 0x1c81 	Graphics card #1 versionInfo: DriverVersion=30.0.14.7196 	Memory slot #0 capacity (MB): 8192.00 	Memory slot #0 clockSpeed (GHz): 2.13 	Memory slot #0 type: DDR4 	Memory slot #1 capacity (MB): 8192.00 	Memory slot #1 clockSpeed (GHz): 2.13 	Memory slot #1 type: DDR4 	Memory slot #2 capacity (MB): 8192.00 	Memory slot #2 clockSpeed (GHz): 2.13 	Memory slot #2 type: DDR4 	Memory slot #3 capacity (MB): 8192.00 	Memory slot #3 clockSpeed (GHz): 2.13 	Memory slot #3 type: DDR4 	Virtual memory max (MB): 40424.04 	Virtual memory used (MB): 18183.18 	Swap memory total (MB): 7790.00 	Swap memory used (MB): 289.91 	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx10096m 	Fabric Mods:  		appliedenergistics2: Applied Energistics 2 9.0.0-beta.1 		fabric: Fabric API 0.41.3+1.17 		fabric-api-base: Fabric API Base 0.3.0+a02b446318 		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+cbda931818 		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.1+ffbe6d8f18 		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318 		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18 		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18 		fabric-containers-v0: Fabric Containers (v0) 0.1.12+cbda931818 		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+cbda931818 		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018 		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.12+ffbe6d8f18 		fabric-entity-events-v1: Fabric Entity Events (v1) 1.3.0+57bef5a318 		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.10+fc40aa9d18 		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18 		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+cbda931818 		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+cbda931818 		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.0+ef17126d18 		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+cbda931818 		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18 		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318 		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318 		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18 		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318 		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+cbda931818 		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318 		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18 		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+cbda931818 		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318 		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318 		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.12+81e15a8918 		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+cbda931818 		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+cbda931818 		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.4+7931163218 		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318 		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4658223018 		fabric-rendering-v0: Fabric Rendering (v0) 1.1.5+7931163218 		fabric-rendering-v1: Fabric Rendering (v1) 1.9.0+7931163218 		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18 		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+cbda931818 		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+cbda931818 		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18 		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+81e15a8918 		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318 		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118 		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.4.1+ffbe6d8f18 		fabricloader: Fabric Loader 0.12.4 		java: Java HotSpot(TM) 64-Bit Server VM 17 		minecraft: Minecraft 1.17.1 		team_reborn_energy: Energy 2.0.0-beta1 	Launched Version: MultiMC5 	Backend library: LWJGL version 3.2.2 build 10 	Backend API: NVIDIA GeForce GTX 1050/PCIe/SSE2 GL version 3.2.0 NVIDIA 471.96, NVIDIA Corporation 	Window size: 1920x1080 	GL Caps: Using framebuffer using OpenGL 3.2 	GL debug messages:  	Using VBOs: Yes 	Is Modded: Definitely; Client brand changed to 'fabric' 	Type: Integrated Server (map_client.txt) 	Graphics mode: fancy 	Resource Packs: Fabric Mods 	Current Language: English (US) 	CPU: 16x Intel(R) Core(TM) i9-9900 CPU @ 3.10GHz 	Player Count: 1 / 8; [class_3222['Ender_Proyects'/155, l='ServerLevel[New World]', x=187.28, y=85.88, z=123.24]] 	Data Packs: vanilla, Fabric Mods
```

**Comment by Technici4n** [comment]
Formation planes work as passive storage, like a storage bus but placing items in the world.

You may have to increase the priority of the formation plane as otherwise the ME network prefers storage locations that already contain the item.

**Comment by EnderProyects** [comment]
Yea, I know  but that not the thing, the formation plane has more priority than the drives, and I allso try to remove all the sapplings, and placed again in the network, and doesn't work

**Comment by urmet** [comment]
formation plane can't put saplings "down" in front of it. you need a block to place against. I guess that's the issue you are facing
![2021-11-06_21 24 49](https://user-images.githubusercontent.com/1254293/140621477-939fa35e-ae1c-495f-9264-187f8e09b42f.png)

**Comment by EnderProyects** [comment]
I also know that, but it's not the case, it has a dispenser with bonemeal in front of it

**Comment by EnderProyects** [comment]
![image](https://user-images.githubusercontent.com/45178400/140628704-61ab1c53-946c-4d4e-95f3-a1f96cb01e8c.png)
So there is a network, and this attached to it, formation plane for sappling, an anhilation for a subnetwork only for logs

**Comment by shartte** [comment]
This works without any issues for me:

![grafik](https://user-images.githubusercontent.com/1261399/140806682-d8f51ec3-88be-4226-823c-ba8979e94f75.png)

**Comment by EnderProyects** [comment]
Well, thats sad, xd, so I will think that I can close this, idk...

**Comment by shartte** [comment]
@EnderProyects: Can you try without the annihilation plane, and could you also please try with just an interface attached to the formation plane? (and placing saplings in it)

**Comment by EnderProyects** [comment]
The annhilation plane is atached to a subnetwork that can´t storage sapplings, so is not that, allso I planted it my self, ando okey, I will try with the interface

**Comment by EnderProyects** [comment]
![image](https://user-images.githubusercontent.com/45178400/140809898-34566861-a25a-46a1-9f5f-cf1f9cff15c1.png)
Well... some changes and it works better xd
