### ISSUE TITLE
java.lang.NullPointerException - "renderer" is null

### ISSUE THREAD

**Issue by MelcomVE** [AppliedEnergistics/Applied-Energistics-2#5717]
### Describe the bug

Applied Energetics: 9.0.0-beta.2
Fabric API: 0.43.1+1.17 (Also tried 0.41.1+1.17 as  listed in the Gradle file)
Fabric Loader: 0.12.5
Minecraft Version: 1.17.1

Launching Minecraft produces the warnings shown below, This breaks the models for all the pipes displaying pink blocks.
I do know how to rebuild the jar just curious if someone has a fix I can, for now, apply to the project or maybe create a PR with the fix in it.

Basically, everything under the facade item tab is broken.

I tried an if statement to set the renderer again but it stays null

[02:33:41] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=12,waterlogged=true': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:41] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:part/item_annihilation_plane': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:41] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:part/fluid_annihilation_plane': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:41] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=11,waterlogged=true': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:41] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:part/item_annihilation_plane_on': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:41] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=0,waterlogged=false': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:41] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=1,waterlogged=false': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:41] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:part/fluid_annihilation_plane_on': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:41] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:part/item_formation_plane': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:41] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=10,waterlogged=true': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:41] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=13,waterlogged=true': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:41] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=4,waterlogged=false': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:41] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:quartz_vibrant_glass#': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.materialFinder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null
[02:33:41] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=3,waterlogged=false': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:41] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=14,waterlogged=true': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:41] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=2,waterlogged=false': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:42] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=15,waterlogged=true': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:42] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:part/item_identity_annihilation_plane': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:42] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=6,waterlogged=false': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:42] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=8,waterlogged=false': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:42] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=7,waterlogged=false': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:43] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=5,waterlogged=false': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:43] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=9,waterlogged=false': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:43] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:drive#': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:43] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=0,waterlogged=true': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:43] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=1,waterlogged=true': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:43] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=10,waterlogged=false': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:43] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=3,waterlogged=true': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:43] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=2,waterlogged=true': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:43] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:part/item_identity_annihilation_plane_on': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:43] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:part/item_formation_plane_on': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:43] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:facade#inventory': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "this.renderer" is null
[02:33:43] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:part/fluid_formation_plane_on': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:43] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=5,waterlogged=true': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:43] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=12,waterlogged=false': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:43] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=13,waterlogged=false': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:43] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=14,waterlogged=false': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:43] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=11,waterlogged=false': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:43] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=6,waterlogged=true': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:43] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=4,waterlogged=true': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:43] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=9,waterlogged=true': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:43] [pool-5-thread-1/ERROR]: Couldn't get pending invite count
net.minecraft.class_4355: Could not connect to Realms: Connect timed out
	at net.minecraft.class_4341.method_20998(class_4341.java:439) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_4341.method_21030(class_4341.java:325) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_4341.method_21029(class_4341.java:320) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_4360.method_33413(class_4360.java:215) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_5784.run(class_5784.java:32) [intermediary-minecraft-1.17.1-client.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[02:33:43] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=8,waterlogged=true': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:43] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=7,waterlogged=true': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:43] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:cable_bus#light_level=15,waterlogged=false': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:43] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:part/fluid_formation_plane': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because "renderer" is null
[02:33:43] [Render thread/WARN]: Unable to bake model: 'appliedenergistics2:quartz_glass#': java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.materialFinder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null

### How to reproduce the bug

I'm not exactly sure, I basically have the versions shown at the top and it causes these pink blocks

### Expected behavior

Items under the facade item tab should not be broken pink textures

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/gCxwcXwt

**Comment by xanthian** [comment]
You probably need indium?

**Comment by shartte** [comment]
Yeah, we don't support sodium directly because it has no support for Fabric's rendering API. I think indium should fix this.

**Comment by MelcomVE** [comment]
Ahhh, thank you very much for the speedy responses.

That did indeed fix it having indium + (iris-sodium)

Much appreciated
