### ISSUE TITLE
CTD when in REI and presing "i" (not in any keybind) = Duplicate registration for ae2:qnb

### ISSUE THREAD

**Issue by Panderine** [AppliedEnergistics/Applied-Energistics-2#6045]
### Describe the bug

Using v.10.1.0-beta1

`[17:27:19] [Render thread/ERROR]: Unhandled game exception
java.lang.IllegalStateException: Duplicate registration for ae2:qnb
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22) ~[?:?]
	at net.minecraft.client.gui.screen.ingame.HandledScreens.register(HandledScreens:76) ~[?:?]
	at net.fabricmc.fabric.api.client.screenhandler.v1.ScreenRegistry.register(ScreenRegistry.java:66) ~[fabric-screen-handler-api-v1-1.1+d7c144a83a-571bfbc29f94bdc1.jar:?]
	at appeng.init.client.InitScreens.register(InitScreens.java:197) ~[appliedenergistics2-10.1.0-beta.1.jar:?]
	at appeng.init.client.InitScreens.init(InitScreens.java:120) ~[appliedenergistics2-10.1.0-beta.1.jar:?]
	at appeng.core.AppEngClient.postClientSetup(AppEngClient.java:204) ~[appliedenergistics2-10.1.0-beta.1.jar:?]
	at appeng.core.AppEngClient.clientSetup(AppEngClient.java:177) ~[appliedenergistics2-10.1.0-beta.1.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientLifecycleEvents.lambda$static$0(ClientLifecycleEvents.java:38) ~[fabric-lifecycle-events-v1-1.4.1+d7c144a83a-ca9aa8904b8e52a1.jar:?]
	at net.minecraft.client.MinecraftClient.handler$cme000$onStart(MinecraftClient:11008) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:712) ~[?:?]
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37) ~[notenoughcrashes-4.1.4+1.18.1-fabric.jar:?]
	at net.minecraft.client.MinecraftClient.modify$eom000$atTheEndOfFirstCatchBeforePrintingCrashReport(MinecraftClient:17535) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:755) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]`

### How to reproduce the bug

Open REI inventory. 
Press "i"

### Expected behavior

not to crash

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://paste.ee/p/SP30h

**Comment by Panderine** [comment]
This is not and AE2 issue. It's a combination of REI, Villager Guards and Inspectio ... Sorry!
