### ISSUE TITLE
Crash while re-entering the Nether which has a QNB.

### ISSUE THREAD

**Issue by magic0whi** [AppliedEnergistics/Applied-Energistics-2#6046]
### Describe the bug

Crash occur when I re-entering the Nether which has a (activated) QNB.
Here are the key errors in latest.log:
```log
[14:52:00] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking grid on end of server tick
	at appeng.hooks.ticking.TickHandler.onServerTickEnd(TickHandler.java:296) ~[appliedenergistics2-10.0.0.jar:?]
	at appeng.hooks.ticking.TickHandler.lambda$init$1(TickHandler.java:93) ~[appliedenergistics2-10.0.0.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$2(ServerTickEvents.java:62) ~[fabric-lifecycle-events-v1-1.4.1+c15ca33565-3981c367624a3e92.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zee000$onEndTick(MinecraftServer.java:1793) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:861) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "appeng.api.networking.IGridNode.beginVisit(appeng.api.networking.IGridVisitor)" because the return value of "appeng.me.Grid.getPivot()" is null
	at appeng.me.service.PathingService.onServerEndTick(PathingService.java:117) ~[appliedenergistics2-10.0.0.jar:?]
	at appeng.me.Grid.onServerEndTick(Grid.java:261) ~[appliedenergistics2-10.0.0.jar:?]
	at appeng.hooks.ticking.TickHandler.onServerTickEnd(TickHandler.java:292) ~[appliedenergistics2-10.0.0.jar:?]
	... 8 more
```
Note: This bug can be reproduce in both 10.0.0 and 10.1.0-beta.1

### How to reproduce the bug

Just create a 'New World', make a simple network (with 1 controller, 1 64K item component) and link it to the QNB in Nether.
Then back to the Overworld, and re-entering the Nether again, crash will occur.

### Expected behavior

Everything should be fine when I entering the Nether which has a QNB nearing the Nether Portal.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/6D85WecE

**Comment by magic0whi** [comment]
I record a short video for easy understanding. (the recording overed when game window is being closed forcibly by a crash)

https://user-images.githubusercontent.com/28147340/151935256-be37f402-2e74-4063-b8ab-836dfba6bc11.mp4

:

**Comment by mindforger** [comment]
sorry for OT ... but just for my sanity, is the video blank for anybody else or my browser failing?

**Comment by magic0whi** [comment]
> sorry for OT ... but just for my sanity, is the video blank for anybody else or just my browser(FF) failing?

This video was encoded by 10bit HEVC, so if your are using the Windows without a HEVC extension installed, it may don't play.

**Comment by Technici4n** [comment]
I am unable to reproduce:
![image](https://user-images.githubusercontent.com/13494793/161150280-d784d9bb-4b29-40ad-866a-24c4a771f008.png)

I am also unable to play that video, please provide it under a format that can be read without having to install some extension.

**Comment by ManuelUSB** [comment]
I have the same bug in appliedenergistics2 9.0.0-beta.2, Minecraft 1.17, all of fabric 4. Dont know if its the QNB that does it.

I had a complicated network in overworld that had a QNB, and a very simple network in Miners Horizon dimension with a QNB. All was well for several days. And one day, without changes to the network, when I logged into minecraft, in the overworld, it crashed with that error.

I removed the QNB after seeing this report, but it's difficult to tell if it was the coulprit. I wasn't travelling through dimensions or anything. Though that other dimension does have a chunk loader

[10:37:23] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking grid on end of server tick
	at appeng.hooks.ticking.TickHandler.onServerTickEnd(TickHandler.java:286) ~[appliedenergistics2-9.0.0-beta.2.jar:?]
	at appeng.hooks.ticking.TickHandler.lambda$init$1(TickHandler.java:89) ~[appliedenergistics2-9.0.0-beta.2.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$2(ServerTickEvents.java:62) ~[fabric-lifecycle-events-v1-1.4.6+0392f3a618-e676704bc6b88232.jar:?]
	at net.minecraft.server.MinecraftServer.handler$cld001$onEndTick(MinecraftServer.java:6327) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:873) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:96) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "appeng.api.networking.IGridNode.beginVisit(appeng.api.networking.IGridVisitor)" because the return value of "appeng.me.Grid.getPivot()" is null
	at appeng.me.service.PathingService.onServerEndTick(PathingService.java:97) ~[appliedenergistics2-9.0.0-beta.2.jar:?]
	at appeng.me.Grid.onServerEndTick(Grid.java:261) ~[appliedenergistics2-9.0.0-beta.2.jar:?]
	at appeng.hooks.ticking.TickHandler.onServerTickEnd(TickHandler.java:282) ~[appliedenergistics2-9.0.0-beta.2.jar:?]
	... 8 more

Minecraft version:
1.17

Loader version:
Fabric

Crash Log
https://pastebin.com/e5RHzWHh

**Comment by Technici4n** [comment]
Was the crash reproducible every time you logged back on? Also, we don't support 1.17 anymore.

**Comment by ManuelUSB** [comment]
Just the one time, and I had logged in multiple times without making changes to the network, so it must be a very peculiar bug, hard to reproduce.

I know 1.17 is no longer supported, just wanted to drop in my two cents that the bug does exist and apparently is still kicking in 1.18 if magic0whi experienced it. If I find a way to reproduce it I'll let you know.

And thanks for the mod, it's awesome

**Comment by Technici4n** [comment]
The next release (likely in a few days?) will add an option to `enableGridLog` (that's the config option name iirc?). If anyone experiences this again with the new release (soon:tm:), please reproduce it with that option enabled, and send us both the server log and the crash report.

**Comment by magic0whi** [comment]
Hi there, I've re-encode the recorded video into H264. Now it might be visible on normal web browser.

https://user-images.githubusercontent.com/28147340/164959553-26898835-6a70-4d2f-832e-0fb9de53d874.mp4

**Comment by Technici4n** [comment]
Ah, nice! Yes that's a problem. Could you reproduce it with the latest AE2 and `gridLog` set to true in the config?

**Comment by magic0whi** [comment]
> Ah, nice! Yes that's a problem. Could you reproduce it with the latest AE2 and `gridLog` set to true in the config?

I tried the lastest version in 1,18.2, the problem disappeared. But here comes a new problem, the QNB cannot cross dimension to connect my main network from World to Nether

**Comment by Technici4n** [comment]
Could be that the part of the network in the overworld is not loaded.
