### ISSUE TITLE
Sometimes autocraft fails to start due to an exception

### ISSUE THREAD

**Issue by MaksExtraIdiot** [AppliedEnergistics/Applied-Energistics-2#6075]
### Describe the bug

Sometimes when trying to start autocraft, the following appears in the chat:
```
Error: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.IllegalStateException: Failed to extract from parent. This is a bug!
```

On the server it says:
```
[20:41:10] [AE Crafting Calculator/INFO]: Exception during crafting calculation.
java.lang.IllegalStateException: Failed to extract from parent. This is a bug!
	at appeng.crafting.inv.CraftingSimulationState.applyDiff(CraftingSimulationState.java:177) ~[appliedenergistics2-10.0.0-alpha.7.jar:?]
	at appeng.crafting.CraftingTreeNode.request(CraftingTreeNode.java:240) ~[appliedenergistics2-10.0.0-alpha.7.jar:?]
	at appeng.crafting.CraftingTreeProcess.request(CraftingTreeProcess.java:113) ~[appliedenergistics2-10.0.0-alpha.7.jar:?]
	at appeng.crafting.CraftingTreeNode.request(CraftingTreeNode.java:212) ~[appliedenergistics2-10.0.0-alpha.7.jar:?]
	at appeng.crafting.CraftingCalculation.computeCraft(CraftingCalculation.java:100) ~[appliedenergistics2-10.0.0-alpha.7.jar:?]
	at appeng.crafting.CraftingCalculation.run(CraftingCalculation.java:79) ~[appliedenergistics2-10.0.0-alpha.7.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

### How to reproduce the bug

I don't know what causes it. It is enough just to start autocraft anything and with some chance it will happen.

### Expected behavior

Autocraft works fine, items are crafting.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://gist.github.com/MaksExtraIdiot/156821578c4c55e136510b82b51de545

**Comment by shartte** [comment]
@MaksExtraIdiot You're on a relatively old version (10.0.0-alpha.7). There were a lot of fixes since then.

Please try to update your version and see if this keeps happening.

**Comment by MaksExtraIdiot** [comment]
There is no problem with the new version. Sorry to bother you
