### ISSUE TITLE
[1.16.5] Spatial storage cells do not work in Biomes O Plenty world type

### ISSUE THREAD

**Issue by thedarkcolour** [AppliedEnergistics/Applied-Energistics-2#6084]
### Describe the bug

Powering the Spatial IO port with a valid SCS and network prints this to the log:
```
[23:00:08] [Server thread/WARN]: Exception: 
java.lang.IllegalStateException: The storage cell world is missing.
	at appeng.spatial.SpatialStoragePlotManager.getWorld(SpatialStoragePlotManager.java:51) ~[appliedenergistics2:8.4.7]
	at appeng.spatial.SpatialStoragePlotManager.getWorldData(SpatialStoragePlotManager.java:57) ~[appliedenergistics2:8.4.7]
	at appeng.spatial.SpatialStoragePlotManager.allocatePlot(SpatialStoragePlotManager.java:70) ~[appliedenergistics2:8.4.7]
	at appeng.items.storage.SpatialStorageCellItem.doSpatialTransition(SpatialStorageCellItem.java:141) ~[appliedenergistics2:8.4.7]
	at appeng.tile.spatial.SpatialIOPortTileEntity.call(SpatialIOPortTileEntity.java:145) ~[appliedenergistics2:8.4.7]
	at appeng.tile.spatial.SpatialIOPortTileEntity.call(SpatialIOPortTileEntity.java:54) ~[appliedenergistics2:8.4.7]
	at appeng.hooks.ticking.TickHandler.processQueue(TickHandler.java:439) ~[appliedenergistics2:8.4.7]
	at appeng.hooks.ticking.TickHandler.onServerTick(TickHandler.java:318) ~[appliedenergistics2:8.4.7]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostServerTick(BasicEventHooks.java:120) ~[forge:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:828) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
```
when using these mods:
BiomesOPlenty-1.16.4-3.0.0.431-universal
appliedenergistics2-8.4.7 (latest version as of reporting)

### How to reproduce the bug

Create a new world with Biomes O Plenty world type,
Create a SCS like the following:
![image](https://user-images.githubusercontent.com/30441001/155833729-ff742a5f-f1b0-47d0-b6f0-ba461a2c74bb.png)
![image](https://user-images.githubusercontent.com/30441001/155833755-406a3660-2b66-4f3c-949a-ac3bbbc892b7.png)
Using a Creative Energy Cell, ME Controller, Spatial IO Port, Fluix ME Smart Cable, Lever, and 8 Spatial Pylons.

### Expected behavior

The two leaves and one oak log are removed from the world and the 2^3 drive moves to the right side of the GUI.

### Additional details

I noticed that the spatial storage works after re-entering the world, but it does not if you enter the world for the first time. My log has an earlier world where the spatial cells work and a newly created world that prints the error.

### Which minecraft version are you using?

1.16

### On which mod loaders does it happen?

Forge

### Crash log

https://gist.github.com/thedarkcolour/35d9f77ff44b5e36e3833d1d788efdbe

**Comment by shartte** [comment]
At this point I am not sure we can do much about it. You're already running the version that re-adds the missing dimension, but for some reason this still doesn't seem to help, hmm.

> [23:05:02] [Render thread/WARN]: AE2 spatial storage dimension missing. It will be re-added.

> I noticed that the spatial storage works after re-entering the world

Do you mean to say that the "fixup" actually works, but it gets lost again if you leave the world?
Keep in mind you haven't actually provided the full modlist too. If you create a forced crash (the F3+C shortcut described when you open an issue here), that would contain the full list.

But I have to  temper your expectations here. The automatic re-adding of the dimension is kinda all we could do since we don't have a good lead on why this keeps happening.

**Comment by shartte** [comment]
If you load that world later, does the spatial dimension stay around? Or does it disappear again until you rejoin later?

**Comment by thedarkcolour** [comment]
It stays around after rejoining.

**Comment by Pandorazai** [comment]
I edited my world's level.dat file with NBTExplorer and was able to fix the problem by doing the following:

Browse to level.dat -> Data -> WorldGenSettings -> dimensions
Create a Compound tag named appliedenergistics2:spatial_storage (at the same level as the other dimensions)
Inside, add a String tag named "type" and set it to appliedenergistics2:spatial_storage
Add another Compound tag inside named generator, and inside that add another String tag named "type" and set it to appliedenergistics2:spatial_storage.
The result should appear as follows:
```
[-] [#] dimensions: 5 entries
 |  [-] [#] appliedenergistics2:spatial_storage: 2 entries
 |   |  [-] [#] generator: 1 entry
 |   |   |   \- [A] type: appliedenergistics2:spatial_storage
 |   |   \- [A] type: appliedenergistics2:spatial_storage
 |  [+] [#] minecraft:overworld: 2 entries
...
```
