### ISSUE TITLE
AE2 Pattern Terminal Does not accept any encoded patterns

### ISSUE THREAD

**Issue by joshuasuperboy** [AppliedEnergistics/Applied-Energistics-2#6479]
When ever i try to put an encoded pattern into the AE2 pattern terminal. The pattern terminal will not accept any sort of encoded pattern. I have included the log below. I did f3+c the game then i sent the log. I do not know what mod is causing this issue. The logs might say something of what is happening so i sent them. My game does not crash ether while trying to put patterns in the AE2 pattern terminal.
Error will be some where at the bottom of the log.
Error will be in the log and if you want just the error the error will be here: <details>    <summary>Error Log: </summary>    [00:46:20] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: appeng/container/implementations/ContainerInterfaceTerminal$Anonymous$6844d1222f1e482a8ff9ff7456b3e32b
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_333]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_333]
	at net.minecraft.util.Util.func_181617_a(Util.java:48) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_333]
Caused by: java.lang.NoClassDefFoundError: appeng/container/implementations/ContainerInterfaceTerminal$Anonymous$6844d1222f1e482a8ff9ff7456b3e32b
	at appeng.container.implementations.ContainerInterfaceTerminal.doAction(ContainerInterfaceTerminal.java:699) ~[ContainerInterfaceTerminal.class:?]
	at appeng.core.sync.packets.PacketInventoryAction.serverPacketData(PacketInventoryAction.java:155) ~[PacketInventoryAction.class:?]
	at appeng.core.sync.network.AppEngServerPacketHandler$1.call(AppEngServerPacketHandler.java:57) ~[AppEngServerPacketHandler$1.class:?]
	at appeng.core.sync.AppEngPacket.func_148833_a(AppEngPacket.java:126) ~[AppEngPacket.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_333]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_333]
	at net.minecraft.util.Util.func_181617_a(Util.java:47) ~[h.class:?]
	... 5 more  </details>
- Environment: 
- Forge Version: 1.12.2-14.23.5.2860
- Minecraft version: 1.12.2
- Log: [latest.log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/9263472/latest.log)

**Comment by joshuasuperboy** [comment]
I figured out the issue. The issue was caused by AE2 Utilities.
