### ISSUE TITLE
Display Issues with GUIs and Terminal

### ISSUE THREAD

**Issue by SpCoGov** [AppliedEnergistics/Applied-Energistics-2#7362]
### Describe the bug

My nearly all GUI are not displaying correctly, such as the Drive and Wireless Access Point interfaces. Only after clicking on a GUI once can the items or text inside be visible. Moreover, my Terminal GUI only opens and displays items correctly the first time. If I open it a second time, none of the items are displayed. I have also checked the log and did not find any exceptions being thrown.

### How to reproduce the bug

Right-clicking on blocks like the Drive

### Expected behavior

No need for me to click the GUI, Cells inside the Drive can be displayed

### Additional details

In fact, I've been porting Applied Energistics for Fabric 1.20 to Minecraft without Fabric and Forge. I'm trying to figure out the cause of this bug and would appreciate any assistance.

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/5fHrJyrk

**Comment by SpCoGov** [comment]
`---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2023-08-30 18:12:09
Description: Manually triggered debug crash

java.lang.Throwable: Manually triggered debug crash
	at net.minecraft.client.KeyboardHandler.tick(KeyboardHandler.java:500)
	at net.minecraft.client.Minecraft.tick(Minecraft.java:1854)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1059)
	at net.minecraft.client.Minecraft.run(Minecraft.java:680)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at mcp.client.Start.main(Start.java:16)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.KeyboardHandler.tick(KeyboardHandler.java:500)

-- Manual crash details --
Details:
	Modules:
		ADVAPI32.dll:Windows 32 API:10.0.25940.1000 (WinBuild.160101.0800):Microsoft Corporation
		AUDIOSES.DLL:10.0.25940.1000 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dl API32:10.0.25940.1000 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		CoreMessaging.dll:Microsoft CoreMessaging Dll:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		CoreUIComponents.dll:Microsoft Core UI Components Dll:10.0.25936.1000:Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		DEVOBJ.dll:Device Information Set DLL:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS API DLL:10.0.25940.1000 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		GLU32.dll:OpenGL DLL:10.0.25940.1000 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP API:10.0.25940.1000 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT API DLL:10.0.25937.1000 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT API DLL:10.0.25937.1000 (WinBuild.160101.0800):Microsoft Corporation
		MMDevApi.dll:MMDevice API:10.0.25940.1000 (WinBuild.160101.0800):Microsoft Corporation
		MSCTF.dll:MSCTF DLL:10.0.25940.1000 (WinBuild.160101.0800):Microsoft Corporation
Caused by: java.lang.Throwable: Manually triggered debug crash

		MpOav.dll:IOfficeAntiVirus Module:4.18.23070.1004 (bb9bcf4b5a81795c3d7eff6d093b19bf6dc550ed):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		OLEAUT32.dll:OLEAUT32.DLL:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		OpenAL.dll:Main implementation library:1.21.1:
		PSAPI.DLL:Process Status Helper:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.25940.1000 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell 公用 DLL:10.0.25938.1000 (WinBuild.160101.0800):Microsoft Corporation
		UMPDC.dll:User Mode Power Dependency Coordinator:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.25940.1000 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.16.27031.1 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.25940.1000 (WinBuild.160101.0800):Microsoft Corporation
		WINSTA.dll:Winstation Library:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		WINTRUST.dll:Microsoft Trust Verification APIs:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32 位 DLL:10.0.25940.1000 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.25940.1000 (WinBuild.160101.0800):Microsoft Corporation
		WTSAPI32.dll:Windows Remote Desktop Session Host Server SDK APIs:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		awt.dll:OpenJDK Platform binary:17.0.8.0:Amazon.com Inc.
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		cfgmgr32.dll:Configuration Manager DLL:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		cryptnet.dll:Crypto Network Related API:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		dinput8.dll:Microsoft DirectInput:10.0.25940.1000 (WinBuild.160101.0800):Microsoft Corporation
		drvstore.dll:Driver Store API:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		dxcore.dll:DXCore:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		fastprox.dll:WMI Custom Marshaller:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW
		icm32.dll:Microsoft Color Management Module (CMM):10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		inputhost.dll:InputHost:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		java.dll:OpenJDK Platform binary:17.0.8.0:Amazon.com Inc.
		java.exe:OpenJDK Platform binary:17.0.8.0:Amazon.com Inc.
		jemalloc.dll
		jimage.dll:OpenJDK Platform binary:17.0.8.0:Amazon.com Inc.
		jli.dll:OpenJDK Platform binary:17.0.8.0:Amazon.com Inc.
		jna3375540816143261716.dll:JNA native library:6.1.4:Java(TM) Native Access (JNA)
		jsvml.dll:OpenJDK Platform binary:17.0.8.0:Amazon.com Inc.
		jvm.dll:OpenJDK 64-Bit server VM:17.0.8.0:Amazon.com Inc.
		kernel.appcore.dll:AppModel API Host:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		lwjgl_opengl.dll
		lwjgl_stb.dll
		management.dll:OpenJDK Platform binary:17.0.8.0:Amazon.com Inc.
		management_ext.dll:OpenJDK Platform binary:17.0.8.0:Amazon.com Inc.
		msasn1.dll:ASN.1 Runtime APIs:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		msvcp140.dll:Microsoft® C Runtime Library:14.16.27033.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:17.0.8.0:Amazon.com Inc.
		nio.dll:OpenJDK Platform binary:17.0.8.0:Amazon.com Inc.
		nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		ntdll.dll:NT 层 DLL:10.0.25937.1000 (WinBuild.160101.0800):Microsoft Corporation
		nvoglv64.dll:NVIDIA Compatible OpenGL ICD:31.0.15.4537:NVIDIA Corporation
		nvspcap64.dll:NVIDIA Game Proxy:3.27.0.112:NVIDIA Corporation
		opengl32.dll:OpenGL Client DLL:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		pfclient.dll:SysMain Client:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		resourcepolicyclient.dll:Resource Policy Client:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:17.0.8.0:Amazon.com Inc.
		textinputframework.dll:"TextInputFramework.DYNLINK":10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		verify.dll:OpenJDK Platform binary:17.0.8.0:Amazon.com Inc.
		wbemcomn.dll:WMI:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		wbemprox.dll:WMI:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		wbemsvc.dll:WMI:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		win32u.dll:Win32u:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		windows.staterepositorycore.dll:Windows StateRepository API Core:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage API:10.0.25940.1000 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		wshunix.dll:AF_UNIX Winsock2 Helper DLL:10.0.25936.1000 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:17.0.8.0:Amazon.com Inc.
Stacktrace:
	at net.minecraft.client.KeyboardHandler.tick(KeyboardHandler.java:500)
	at net.minecraft.client.Minecraft.tick(Minecraft.java:1854)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1059)
	at net.minecraft.client.Minecraft.run(Minecraft.java:680)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at mcp.client.Start.main(Start.java:16)

-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['TestPlayer'/662, l='ClientLevel', x=-55.69, y=67.00, z=-306.72]]
	Chunk stats: 961, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (-39,65,-314), Section: (at 9,1,6 in -3,4,-20; chunk contains blocks -48,-64,-320 to -33,319,-305), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 2119182 game time, 1177321 day time
	Server brand: vanilla
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.fillReportDetails(ClientLevel.java:448)
	at net.minecraft.client.Minecraft.fillReport(Minecraft.java:2374)
	at net.minecraft.client.Minecraft.run(Minecraft.java:697)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at mcp.client.Start.main(Start.java:16)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Amazon.com Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Amazon.com Inc.
	Memory: 1853641216 bytes (1767 MiB) / 3313500160 bytes (3160 MiB) up to 8560574464 bytes (8164 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800X 8-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.80
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3080 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2208
	Graphics card #0 versionInfo: DriverVersion=31.0.15.4537
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.33
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.33
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 3.33
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 3.33
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 53133.64
	Virtual memory used (MB): 41682.59
	Swap memory total (MB): 20480.00
	Swap memory used (MB): 2265.41
	JVM Flags: 0 total; 
	Launched Version: mcp
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 545.37, NVIDIA Corporation
	Window size: 3840x2054
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Very likely; Client jar signature invalidated; Server jar signature invalidated
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: en_us
	CPU: 16x AMD Ryzen 7 5800X 8-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['TestPlayer'/662, l='ServerLevel[TestLevel]', x=-55.69, y=67.00, z=-306.72]]
	Data Packs: vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
#@!@# Game crashed! Crash report saved to: #@!@# G:\MyCodes\Minecraft\run\.\crash-reports\crash-2023-08-30_18.12.09-client.txt`

**Comment by SpCoGov** [comment]
https://pastebin.com/5fHrJyrk

**Comment by SpCoGov** [comment]
I found the issue, and the reason was that I forgot to execute the entrypoints method in my own FabricAPI-screenhandler.
