### ISSUE TITLE
Numerous crash issues with AE2 and REI - Roughly Searchable. Fabric 1.18.2

### ISSUE THREAD

**Issue by PlayfulPiano** [AppliedEnergistics/Applied-Energistics-2#7451]
### Describe the bug

For the past few days while I've been using AE2, I've been in a few situations when interacting with REI that I experience a game crash.

In every case, it gives the following crash error, and stacktrace.

```
java.lang.IllegalStateException: Pose stack not empty
	at net.minecraft.class_761.method_22979(class_761.java:1553)
	at net.minecraft.class_761.method_22710(class_761.java:1369)
	at net.minecraft.class_757.method_3188(class_757.java:1034)
	at net.minecraft.class_757.method_3192(class_757.java:813)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
```
```
Stacktrace:
	at net.minecraft.class_761.method_22979(class_761.java:1553)
	at net.minecraft.class_761.method_22710(class_761.java:1369)
	at net.minecraft.class_757.method_3188(class_757.java:1034)
```

### How to reproduce the bug

Situations where this crash has occurred:
- REI Quick-Crafting (Ctrl+Click) a Charger, ME Interface, Energy Cell, or Inscriber
- Typing letters while in the middle of a search (inconsistent)
- Shift Clicking Storage Cells in and out of an ME IO Port (inconsistent)

Situations where this crash has **NOT** occurred:
- Opening up AE2 Machines / UIs
- REI Quick-Crafting (Ctrl+Click) Annihilation Cores, Formation Cores, Illumination Panels, Item Storage Components, or Quartz Glass 

Note: For crash cases, the game does save the last position items were in. For example if you have Visual Workbench installed, then a quick-craft crash at a crafting table would have the items you quick-crafted in the workbench when you reload the world. Same goes for the ME Crafting Interface.
No data seems to be lost from these crashes, for now at least.

### Expected behavior

The expected behavior is whatever action going on occurs without a crash.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://paste.ee/p/9Rhkd (this has both the crash & latest.log attached)

**Comment by PlayfulPiano** [comment]
Big Update: Conflict is specifically the mod "Roughly Searchable". If the functionality of this mod is disabled, then the crash does not happen.
https://legacy.curseforge.com/minecraft/mc-mods/roughly-searchable

**Comment by Technici4n** [comment]
Probably their fault then.
