### ISSUE TITLE
 Detonate a AE2 Tiny TNT near a disguised pipe can crash server

### ISSUE THREAD

**Issue by J4ckTh3R1pper** [AppliedEnergistics/Applied-Energistics-2#7522]
### Describe the bug

The server crashed

### How to reproduce the bug

Detonate A tiny TNT with a Modern Industrialization pipe within its blast radius.

### Expected behavior

Nothing happens

### Additional details

MI version: 1.6.16, AE2 version: 12.9.8, Using the latest StaTech Industry modpack.

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Fabric

### Crash log

https://gist.github.com/J4ckTh3R1pper/3d0a38e275d3de6fe5251a41caf3f16e

**Comment by Technici4n** [comment]
```
java.lang.NullPointerException: Cannot invoke "aztech.modern_industrialization.pipes.impl.PipeBlockEntity.getNodes()" because "pipeEntity" is null
	at aztech.modern_industrialization.pipes.impl.PipeBlock.getDroppedStacks(PipeBlock.java:239)
	at net.minecraft.AbstractBlock$Settingsclass_4971.getDroppedStacks(AbstractBlock.java:960)
	at net.minecraft.block.Block.getDroppedStacks(Block.java:329)
	at net.minecraft.block.Block.dropStacks(Block.java:351)
	at appeng.entity.TinyTNTPrimedEntity.explode(TinyTNTPrimedEntity.java:178)
	at appeng.entity.TinyTNTPrimedEntity.tick(TinyTNTPrimedEntity.java:123)
```

It looks like AE2 is calling the wrong `Block.dropResources` override, and therefore MI doesn't get the BE in the loot context.

**Comment by Technici4n** [comment]
Defensive programming... 😉
