### ISSUE TITLE
`java.lang.IllegalAccessError` on start

### ISSUE THREAD

**Issue by Plexi09** [AppliedEnergistics/Applied-Energistics-2#7773]
### Describe the bug

When i launch my server with AE2, i get this:

```
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.20/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
        ... 7 more
Caused by: java.lang.IllegalAccessError: class appeng.block.misc.MysteriousCubeBlock tried to access private method 'boolean net.minecraft.world.level.block.Blocks.m_50805_(net.minecraft.world.level.block.state.BlockState, net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos)' (appeng.block.misc.MysteriousCubeBlock is in module ae2@15.0.23 of loader 'TRANSFORMER' @43ecfeb5; net.minecraft.world.level.block.Blocks is in module minecraft@1.20.1 of loader 'TRANSFORMER' @43ecfeb5)
        at TRANSFORMER/ae2@15.0.23/appeng.block.misc.MysteriousCubeBlock.<clinit>(MysteriousCubeBlock.java:24)
        at TRANSFORMER/ae2@15.0.23/appeng.core.definitions.AEBlocks.block(AEBlocks.java:273)
        at TRANSFORMER/ae2@15.0.23/appeng.core.definitions.AEBlocks.block(AEBlocks.java:263)
        at TRANSFORMER/ae2@15.0.23/appeng.core.definitions.AEBlocks.<clinit>(AEBlocks.java:157)
        at TRANSFORMER/ae2@15.0.23/appeng.core.AppEngBootstrap.runEarlyStartup(AppEngBootstrap.java:73)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Bootstrap.handler$bcl000$initRegistries(Bootstrap.java:541)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:57)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Main.main(Main.java:121)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 12 more
        ```

### How to reproduce the bug

Install AE2 and launch a dedicated server

### Expected behavior

expected the server to start

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

The server does not create a crash report

**Comment by Plexi09** [comment]
log file: https://pastebin.com/DF9FJWPp
