### ISSUE TITLE
Game crash due to illegal access error

### ISSUE THREAD

**Issue by OracularSpy** [AppliedEnergistics/Applied-Energistics-2#7829]
### Describe the bug

Caused by: java.lang.IllegalAccessError: class appeng.block.misc.MysteriousCubeBlock tried to access private method 'boolean net.minecraft.world.level.block.Blocks.m_50805_(net.minecraft.world.level.block.state.BlockState, net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos)' (appeng.block.misc.MysteriousCubeBlock is in module ae2@15.1.0 of loader 'TRANSFORMER' @1df9186f; net.minecraft.world.level.block.Blocks is in module minecraft@1.20.1 of loader 'TRANSFORMER' @1df9186f)
	at TRANSFORMER/ae2@15.1.0/appeng.block.misc.MysteriousCubeBlock.<clinit>(MysteriousCubeBlock.java:24)
	at TRANSFORMER/ae2@15.1.0/appeng.core.definitions.AEBlocks.block(AEBlocks.java:276)
	at TRANSFORMER/ae2@15.1.0/appeng.core.definitions.AEBlocks.block(AEBlocks.java:266)
	at TRANSFORMER/ae2@15.1.0/appeng.core.definitions.AEBlocks.<clinit>(AEBlocks.java:158)
	at TRANSFORMER/ae2@15.1.0/appeng.core.AppEngBootstrap.runEarlyStartup(AppEngBootstrap.java:73)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Bootstrap.handler$bcb000$initRegistries(Bootstrap.java:541)

### How to reproduce the bug

launch minecraft forge 1.20.1

### Expected behavior

generic successful launch of the game

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

https://pastebin.com/DzF77fSX

**Comment by 62832** [comment]
```
[09:13:05] [main/ERROR]: Missing or unsupported mandatory dependencies:
    Mod ID: 'forge', Requested by: 'bettergolem', Expected range: '[47.2.20,)', Actual version: '47.2.0'
[09:13:05] [main/ERROR]: Unsupported installed optional dependencies:
    Mod ID: 'curios', Requested by: 'quark', Expected range: '[5.6.1+1.20.1,)', Actual version: '5.3.5+1.20.1'
```

Update your versions of Forge and Curios.
