### ISSUE TITLE
Being kicked from a server due to a ticking exception on player.

### ISSUE THREAD

**Issue by Timbo3Bak** [AppliedEnergistics/Applied-Energistics-2#8057]
### Describe the bug

Upon joining a friend's hosted server I get immediately kicked. The first time I was kicked I got the error: you have been kicked due to a ticking exception on the player. Please remove the culprit mod or contact an admin. After that it's just been connection reset. The server seems to be getting this error message though: you have been kicked due to a ticking exception on the player. Please remove the culprit mod or contact an admin.  In the latest.log, it spams "Manager is null" on the client side if that's at all relevant.

A server side error my friend sent me:
```
Caused by: java.lang.NullPointerException: Cannot invoke "appeng.api.networking.IGrid.getEnergyService()" because "this.targetGrid" is null
        at de.mari_023.ae2wtlib.terminal.WTMenuHost.isQuantumLinked(WTMenuHost.java:120) ~[ae2wtlib-15.1.3-fabric.jar:?]
        at de.mari_023.ae2wtlib.terminal.WTMenuHost.rangeCheck(WTMenuHost.java:96) ~[ae2wtlib-15.1.3-fabric.jar:?]
        at de.mari_023.ae2wtlib.wct.CraftingTerminalHandler.getMenuHost(CraftingTerminalHandler.java:80) ~[ae2wtlib-15.1.3-fabric.jar:?]
        at de.mari_023.ae2wtlib.wct.CraftingTerminalHandler.inRange(CraftingTerminalHandler.java:115) ~[ae2wtlib-15.1.3-fabric.jar:?]
        at de.mari_023.ae2wtlib.AE2wtlibEvents.insertStackInME(AE2wtlibEvents.java:75) ~[ae2wtlib-15.1.3-fabric.jar:?]
        at net.minecraft.entity.player.PlayerInventory.handler$zjn000$ae2wtlib$insertStackInME(PlayerInventory.java:1189) ~[server-intermediary.jar:?]
        at net.minecraft.entity.player.PlayerInventory.insertStack(PlayerInventory.java) ~[server-intermediary.jar:?]
        at net.minecraft.entity.ItemEntity.onPlayerCollision(ItemEntity.java:360) ~[server-intermediary.jar:?]
        at net.minecraft.entity.player.PlayerEntity.collideWithEntity(PlayerEntity.java:627) ~[server-intermediary.jar:?]
        at net.minecraft.entity.player.PlayerEntity.tickMovement(PlayerEntity.java:600) ~[server-intermediary.jar:?]
        at net.minecraft.entity.LivingEntity.tick(LivingEntity.java:2419) ~[server-intermediary.jar:?]
        at net.minecraft.entity.player.PlayerEntity.tick(PlayerEntity.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.server.network.ServerPlayerEntity.playerTick(ServerPlayerEntity.java:510) ~[server-intermediary.jar:?]
```

### How to reproduce the bug

Join the server, upon loading in, you get kicked with a connection reset. 

### Expected behavior

To be able to join the server.

### Additional details

I'm playing the Prominence 2 RPG modpack. I've been fine for the past couple of weeks and have been able to log in normally. Possible relevant information:
I'm in the nether. Server just started and I think I'm the first one on since it booted up. I have a wireless AE2 terminal linked with quantum singularities. I'm using POWAH's power distributor to wireless charge it. The main AE2 systems and the POWAH stuff are being forceloaded using FTB teams chunk claiming.

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Fabric

### Crash log

https://gist.github.com/Timbo3Bak/bf82fe5b348811074a867ab4822a4815

**Comment by Timbo3Bak** [comment]
Ok I did some testing. I wiped my inventory and it seems to have fixed it. Seems to have been caused by a corrupted item, possibly the wireless terminal? I used NBTexplorer to wipe it.
