### ISSUE TITLE
Null pointer exception when connecting ME conduits from EnderIO to network with security terminal

### ISSUE THREAD

**Issue by HiTECNOLOGYs** [AppliedEnergistics/Applied-Energistics-2#807]
The following errors appear in server log:
```
[21:41:00] [Server thread/ERROR] [AE2:S]: Error: java.lang.NullPointerException : null
[21:41:00] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[21:41:00] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at appeng.me.GridNode$MachineSecurityBreak.call(GridNode.java:614)
[21:41:00] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at appeng.me.GridNode$MachineSecurityBreak.call(GridNode.java:602)
[21:41:00] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at appeng.hooks.TickHandler.processQueue(TickHandler.java:287)
[21:41:00] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at appeng.hooks.TickHandler.onTick(TickHandler.java:271)
[21:41:00] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at cpw.mods.fml.common.eventhandler.ASMEventHandler_369_TickHandler_onTick_TickEvent.invoke(.dynamic)
[21:41:00] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[21:41:00] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
[21:41:00] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:268)
[21:41:00] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:620)
[21:41:00] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[21:41:00] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[21:41:00] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[21:41:00] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

Version of AE: rv2-beta-7
Version of EnderIO: 2.2.6.325

Things started working after breaking ST and replacing all the conduits that doesn't work, then installing terminal back. I'm not sure who to blame, so I also filed a bug at EnderIO's tracker: https://github.com/CrazyPants/EnderIO/issues/1782

**Comment by yueh** [comment]
ME conduits are mostly a WIP feature and do not work well with AE2 currently.

**Comment by HiTECNOLOGYs** [comment]
I see. I'll keep this issue up to date in case I find out more information that can help pinpointing the problem.
