### ISSUE TITLE
NullPointerException в Applied Energistics 2: ошибка при вызове Supplier

### ISSUE THREAD

**Issue by den4a** [AppliedEnergistics/Applied-Energistics-2#8237]
### Describe the bug

 При запуске сборки Minecraft с модом Applied Energistics 2 возникает ошибка NullPointerException. Проблема, по-видимому, связана с возвращением null от Supplier в коде мода, что вызывает сбой в работе мода.
 
 Контекст:
Версия Minecraft: 1.20.1
Версия Applied Energistics 2: LAST 15.2.13
Ошибка возникает на стороне сервера (в консоли спамит этим сообщением)
Сборка All the Mods 9 - No Frills, включая Applied Energistics 2 и другие моды.

### How to reproduce the bug

[23:49:50 WARN]: Catching
java.lang.NullPointerException: Supplier should not return null value
        at net.minecraftforge.common.util.LazyOptional.getValue(LazyOptional.java:101) ~[forge-1.20.1-47.2.20-universal.jar%23796!/:?]
        at net.minecraftforge.common.util.LazyOptional.orElse(LazyOptional.java:221) ~[forge-1.20.1-47.2.20-universal.jar%23796!/:?]
        at appeng.util.BlockApiCache.find(BlockApiCache.java:29) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.helpers.patternprovider.PatternProviderTargetCache.find(PatternProviderTargetCache.java:40) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.helpers.patternprovider.PatternProviderLogic.findAdapter(PatternProviderLogic.java:461) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.helpers.patternprovider.PatternProviderLogic.pushPattern(PatternProviderLogic.java:325) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.crafting.execution.CraftingCpuLogic.executeCrafting(CraftingCpuLogic.java:211) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.crafting.execution.CraftingCpuLogic.tickCraftingLogic(CraftingCpuLogic.java:156) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.me.service.CraftingService.onServerEndTick(CraftingService.java:152) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.me.Grid.onServerEndTick(Grid.java:236) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.hooks.ticking.TickHandler.onServerTickEnd(TickHandler.java:325) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.hooks.ticking.TickHandler.onServerTick(TickHandler.java:299) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2386!/:?]
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2386!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2386!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2386!/:?]
        at net.minecraftforge.event.ForgeEventFactory.onPostServerTick(ForgeEventFactoryMixin.java:950) ~[forge-1.20.1-47.2.20-universal.jar%23796!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:835) ~[server-1.20.1-20230612.114412-srg.jar%23791!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2070) ~[server-1.20.1-20230612.114412-srg.jar%23791!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23791!/:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[23:49:57 WARN]: Catching
java.lang.NullPointerException: Supplier should not return null value
        at net.minecraftforge.common.util.LazyOptional.getValue(LazyOptional.java:101) ~[forge-1.20.1-47.2.20-universal.jar%23796!/:?]
        at net.minecraftforge.common.util.LazyOptional.orElse(LazyOptional.java:221) ~[forge-1.20.1-47.2.20-universal.jar%23796!/:?]
        at appeng.util.BlockApiCache.find(BlockApiCache.java:29) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.helpers.patternprovider.PatternProviderTargetCache.find(PatternProviderTargetCache.java:40) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.helpers.patternprovider.PatternProviderLogic.findAdapter(PatternProviderLogic.java:461) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.helpers.patternprovider.PatternProviderLogic.pushPattern(PatternProviderLogic.java:325) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.crafting.execution.CraftingCpuLogic.executeCrafting(CraftingCpuLogic.java:211) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.crafting.execution.CraftingCpuLogic.tickCraftingLogic(CraftingCpuLogic.java:156) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.me.service.CraftingService.onServerEndTick(CraftingService.java:152) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.me.Grid.onServerEndTick(Grid.java:236) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.hooks.ticking.TickHandler.onServerTickEnd(TickHandler.java:325) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.hooks.ticking.TickHandler.onServerTick(TickHandler.java:299) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2386!/:?]
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2386!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2386!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2386!/:?]
        at net.minecraftforge.event.ForgeEventFactory.onPostServerTick(ForgeEventFactoryMixin.java:950) ~[forge-1.20.1-47.2.20-universal.jar%23796!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:835) ~[server-1.20.1-20230612.114412-srg.jar%23791!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2070) ~[server-1.20.1-20230612.114412-srg.jar%23791!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23791!/:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[23:50:25 WARN]: Catching
java.lang.NullPointerException: Supplier should not return null value
        at net.minecraftforge.common.util.LazyOptional.getValue(LazyOptional.java:101) ~[forge-1.20.1-47.2.20-universal.jar%23796!/:?]
        at net.minecraftforge.common.util.LazyOptional.orElse(LazyOptional.java:221) ~[forge-1.20.1-47.2.20-universal.jar%23796!/:?]
        at appeng.util.BlockApiCache.find(BlockApiCache.java:29) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.helpers.patternprovider.PatternProviderTargetCache.find(PatternProviderTargetCache.java:40) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.helpers.patternprovider.PatternProviderLogic.findAdapter(PatternProviderLogic.java:461) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.helpers.patternprovider.PatternProviderLogic.pushPattern(PatternProviderLogic.java:325) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.crafting.execution.CraftingCpuLogic.executeCrafting(CraftingCpuLogic.java:211) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.crafting.execution.CraftingCpuLogic.tickCraftingLogic(CraftingCpuLogic.java:156) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.me.service.CraftingService.onServerEndTick(CraftingService.java:152) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.me.Grid.onServerEndTick(Grid.java:236) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.hooks.ticking.TickHandler.onServerTickEnd(TickHandler.java:325) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.hooks.ticking.TickHandler.onServerTick(TickHandler.java:299) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2386!/:?]
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2386!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2386!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2386!/:?]
        at net.minecraftforge.event.ForgeEventFactory.onPostServerTick(ForgeEventFactoryMixin.java:950) ~[forge-1.20.1-47.2.20-universal.jar%23796!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:835) ~[server-1.20.1-20230612.114412-srg.jar%23791!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2070) ~[server-1.20.1-20230612.114412-srg.jar%23791!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23791!/:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[23:50:32 WARN]: Catching
java.lang.NullPointerException: Supplier should not return null value
        at net.minecraftforge.common.util.LazyOptional.getValue(LazyOptional.java:101) ~[forge-1.20.1-47.2.20-universal.jar%23796!/:?]
        at net.minecraftforge.common.util.LazyOptional.orElse(LazyOptional.java:221) ~[forge-1.20.1-47.2.20-universal.jar%23796!/:?]
        at appeng.util.BlockApiCache.find(BlockApiCache.java:29) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.helpers.patternprovider.PatternProviderTargetCache.find(PatternProviderTargetCache.java:40) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.helpers.patternprovider.PatternProviderLogic.findAdapter(PatternProviderLogic.java:461) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.helpers.patternprovider.PatternProviderLogic.pushPattern(PatternProviderLogic.java:325) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.crafting.execution.CraftingCpuLogic.executeCrafting(CraftingCpuLogic.java:211) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.crafting.execution.CraftingCpuLogic.tickCraftingLogic(CraftingCpuLogic.java:156) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.me.service.CraftingService.onServerEndTick(CraftingService.java:152) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.me.Grid.onServerEndTick(Grid.java:236) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.hooks.ticking.TickHandler.onServerTickEnd(TickHandler.java:325) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.hooks.ticking.TickHandler.onServerTick(TickHandler.java:299) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2386!/:?]
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2386!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2386!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2386!/:?]
        at net.minecraftforge.event.ForgeEventFactory.onPostServerTick(ForgeEventFactoryMixin.java:950) ~[forge-1.20.1-47.2.20-universal.jar%23796!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:835) ~[server-1.20.1-20230612.114412-srg.jar%23791!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2070) ~[server-1.20.1-20230612.114412-srg.jar%23791!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23791!/:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[23:50:40 WARN]: Catching
java.lang.NullPointerException: Supplier should not return null value
        at net.minecraftforge.common.util.LazyOptional.getValue(LazyOptional.java:101) ~[forge-1.20.1-47.2.20-universal.jar%23796!/:?]
        at net.minecraftforge.common.util.LazyOptional.orElse(LazyOptional.java:221) ~[forge-1.20.1-47.2.20-universal.jar%23796!/:?]
        at appeng.util.BlockApiCache.find(BlockApiCache.java:29) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.helpers.patternprovider.PatternProviderTargetCache.find(PatternProviderTargetCache.java:40) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.helpers.patternprovider.PatternProviderLogic.findAdapter(PatternProviderLogic.java:461) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.helpers.patternprovider.PatternProviderLogic.pushPattern(PatternProviderLogic.java:325) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.crafting.execution.CraftingCpuLogic.executeCrafting(CraftingCpuLogic.java:211) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.crafting.execution.CraftingCpuLogic.tickCraftingLogic(CraftingCpuLogic.java:156) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.me.service.CraftingService.onServerEndTick(CraftingService.java:152) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.me.Grid.onServerEndTick(Grid.java:236) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.hooks.ticking.TickHandler.onServerTickEnd(TickHandler.java:325) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at appeng.hooks.ticking.TickHandler.onServerTick(TickHandler.java:299) ~[appliedenergistics2-forge-15.2.13.jar%23504!/:15.2.13]
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2386!/:?]
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2386!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2386!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2386!/:?]
        at net.minecraftforge.event.ForgeEventFactory.onPostServerTick(ForgeEventFactoryMixin.java:950) ~[forge-1.20.1-47.2.20-universal.jar%23796!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:835) ~[server-1.20.1-20230612.114412-srg.jar%23791!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2070) ~[server-1.20.1-20230612.114412-srg.jar%23791!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23791!/:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

### Expected behavior

Не понимаю зачем это поле, ну ладно )

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

https://logs.hosting-minecraft.pro/idixuroker

**Comment by 62832** [comment]
Please keep issue submissions in English, as none of us involved with development speak any Russian. Also, please don't truncate the crash log when submitting the issue.
