### ISSUE TITLE
NPE ticking entity in ContainerCraftConfirm

### ISSUE THREAD

**Issue by heatseeker0** [AppliedEnergistics/Applied-Energistics-2#860]
Just got this server crash. It happened when a player was browsing through his wireless terminal and wanted to craft something.

AE version: appliedenergistics2-rv2-beta-8
Server: cauldron-1.7.10-1.1236.05.212

java.lang.NullPointerException: Ticking entity
        at appeng.container.implementations.ContainerCraftConfirm.getGrid(ContainerCraftConfirm.java:352)
        at appeng.container.implementations.ContainerCraftConfirm.func_75142_b(ContainerCraftConfirm.java:156)
        at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:311)
        at net.minecraft.world.World.func_72866_a(World.java:2647)
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
        at net.minecraft.world.World.func_72870_g(World.java:2600)
        at net.minecraft.world.World.func_72939_s(World.java:2412)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
        at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
        at appeng.container.implementations.ContainerCraftConfirm.getGrid(ContainerCraftConfirm.java:352)
        at appeng.container.implementations.ContainerCraftConfirm.func_75142_b(ContainerCraftConfirm.java:156)
        at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:311)
        at net.minecraft.world.World.func_72866_a(World.java:2647)
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
        at net.minecraft.world.World.func_72870_g(World.java:2600)

**Comment by yueh** [comment]
Sorry, but no support for cauldron.

**Comment by heatseeker0** [comment]
This doesn't look like it crashes because of Cauldron. I restarted the server with nothing but Forge and upon attempting to restart the server I get this:

Time: 2/7/15 12:49 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
        at appeng.core.Registration.preInitialize(Registration.java:446)
        at appeng.core.AppEng.preInit(AppEng.java:122)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSu
bscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
        at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
        at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
        at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:319)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:170)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620)
        at java.lang.Thread.run(Thread.java:745)

**Comment by yueh** [comment]
For future reference.

The first log is probably an issue with cauldron.
The second is caused by disabled paintballs, also see #675
