### ISSUE TITLE
Server crash immediately after startup.

### ISSUE THREAD

**Issue by Tsyklop** [AppliedEnergistics/Applied-Energistics-2#880]
Couldron 213. AE2 rv2 beta8

java.lang.NoClassDefFoundError: net/minecraft/world/World$3
	at net.minecraft.world.World.func_147460_e(World.java:1090)
	at net.minecraft.world.World.func_147459_d(World.java:1011)
	at appeng.util.BlockUpdate.call(BlockUpdate.java:42)
	at appeng.hooks.TickHandler.processQueue(TickHandler.java:287)
	at appeng.hooks.TickHandler.onTick(TickHandler.java:271)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_269_TickHandler_onTick_TickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:273)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:914)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Unknown Source)

**Comment by Tsyklop** [comment]
Region Fixer not help me.

**Comment by yueh** [comment]
No support for cauldron.

**Comment by Tsyklop** [comment]
why?

**Comment by Cisien** [comment]
Cauldron and similar modify how a forge server behaves in a way that is hard to support. Because of this, we have taken the stance of not supporting cauldron. In fact, if cauldron is causing problems, then you should inform them so they can address it.

If you can reproduce your problem on a standard forge server, then re-open this issue with the forge log or crash log.

**Comment by KamranMackey** [comment]
@yueh When are you guys going to resume development on AE2? Last commit was 8 days ago.

**Comment by Tsyklop** [comment]
it's just a bug appears . He has appeared with time and I suspect it is associated with some sort of block that leads to a drop in the server.
