### ISSUE TITLE
Channels=False java.lang.NullPointerException : null

### ISSUE THREAD

**Issue by Iomega0318** [AppliedEnergistics/Applied-Energistics-2#896]
I get the following error using rv2-beta-8:
*[Server thread/ERROR] [AE2:S/appliedenergistics2]: Error: java.lang.NullPointerException : null*
This happens when disabling channels, note that this only seems to effect the server, I can play in single player just fine but when using it on a server it fails.

I tired searching for a fix or something but didn't find anything..

**Comment by yueh** [comment]
Post the full log.

And also do not expect that disabling channels for the client will work with a different server configuration.

**Comment by yueh** [comment]
Inactive, reopen when you can provide more feedback.

**Comment by Iomega0318** [comment]
Sorry been super busy, here is the output from the console when I set the Network Channels to False:
```
[09:12:45] [Server thread/INFO] [AE2:S]: Initialization ( started )
[09:12:45] [Server thread/ERROR] [AE2:S]: Error: java.lang.NullPointerException: null
java.lang.NullPointerException
        at appeng.core.features.ColoredItemDefinition.allStacks(ColoredItemDefinition.java:89)
        at appeng.recipes.AEItemResolver.resolveItemByName(AEItemResolver.java:78)
        at appeng.core.features.registries.RecipeHandlerRegistry.resolveItem(RecipeHandlerRegistry.java:83)
        at appeng.recipes.Ingredient.<init>(Ingredient.java:89)
        at appeng.recipes.RecipeHandler.findIngredient(RecipeHandler.java:639)
        at appeng.recipes.RecipeHandler.parseLines(RecipeHandler.java:619)
        at appeng.recipes.RecipeHandler.processTokens(RecipeHandler.java:486)
        at appeng.recipes.RecipeHandler.parseRecipes(RecipeHandler.java:417)
        at appeng.core.Registration.initialize(Registration.java:551)
        at appeng.core.AppEng.init(AppEng.java:146)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
        at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)
        at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
        at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```
What is super weird though is if I copy the server to my desktop computer I can run it fine with it set to false, it just wont work on my server.
